# Создадим словарь английских слов к книге "Идентификация Борна"
def main():
    file=open(r'C:\Users\LENOVO\Desktop\СЛОВАРЬ_БОРН.txt','w')
    file.write("СЛОВО   ПЕРЕВОД\n")
    file.write("\n")
    file.write("CONTRADICTIONS  ПРОТИВОРЕЧИЯ\n")
    file.write("APPEAR  ПОЯВЛЯТЬСЯ\n")
    file.write("MASS   МАССА\n")
    file.write("SUBSURFACE   ПОДПОВРЕХНОСТНОЕ\n")
    file.write("VIOLENCE   НАСИЛИЕ\n")
    file.write("ALIVE  ВЖИВЫХ\n")
    file.write("PENSIVENESS  ЗАДУМЧИВОСТЬ\n")
    file.write("RARELY   РЕДКО\n")
    file.write("PROVOKE  ВЫЗЫВАТЬ\n")
    file.write("AWARE ОСВЕДОМЛЕННЫЙ\n")
    file.write("IN TERMS С ТОЧКИ ЗРЕНИЯ\n")
    file.write("OCCUPATION  ПРОФЕССИЯ\n")
    file.write("FRIGHTENING  СТРАШНО\n")
    file.write("CLIPBOARD  ПАПКА С ЗАЖИМАМИ\n")
    file.write("CUPBOARD ШКАФ С ПОСУДОЙ\n")
    file.write("DRAWER ВЫДВИЖНОЙ ЯЩИК\n")
    file.write("TENSED НАПРЯЖЕННЫЙ\n")
    file.write("WATERFRONT БЕРЕГ\n")
    file.write("DISMANTL  ДЕМОНТИРОВАТЬ\n")
    file.write("COMPLETELY  ПОЛНОСТЬЮ\n")

    file.close()
main()