#                 ЧЕРНОВОЙ ВАРИАНТ ПРОГРАММЫ ДЛЯ ПОВТОРЕНИЯ СЛОВ НА АНГЛИЙСКОМ ЯЗЫКЕ!
import pickle


def main():
    """
    Программа принимает и сохраняет новые английские слова в словарь.
    :return: None
    """
    # создадим словарь,куда будем сохранять слово/перевод и запишем в файл.
    file = open('/home/andrey/Studying/my_vocabulary3.dat', 'wb')
    vocabulary = {'ШТУКИ/ТЫСЯЧИ/ГРАНД': 'GRAND', 'СТАВКА/КУРС/КОЕФИЦИЕННТ': 'RATE',
                  'УСИЛИТЬ/АКТИВИЗИРОВАТЬ': 'TO STEP UP',
                  'ВРАЖДЕБНОСТЬ': 'HOSTILITY', 'ХАМСТВО': 'RUDENESS', 'ВЯЛЫЙ': 'FLACCID', 'ВЫПЕЧКА': 'PASTRY',
                  'ТЫ РАЗЫГРЫВАЕШЬ МЕНЯ?': 'ARE YOU SHITTING ME?', 'ПРЯМАЯ ЗАВИСИМОСТЬ': 'LINEAR CORRELATION',
                  'КОНТРОЛЬНЫЕ ПОКАЗАТЕЛИ': 'BENCHMARKS', 'НЕОБХОДИМЫЙ/СООТВЕТСТВУЮЩИЙ': 'RELEVANT',
                  'ПРОЦВЕТАТЬ': 'TO THRIVE',
                  'ПОДСЧИТАТЬ/ОПРЕДЕЛИТЬ КОЛИЧЕСТВО': 'TO QUANTIFY', 'НЕРЕШИТЕЛЬНЫЙ': 'HESITANT',
                  'ПРОИЗВОДИТЬ': 'TO MANUFACTURE',
                  'НАПРЯЖЕНИЕ/НАПРЯЖЕННОСТЬ': 'TENSION', 'ПОИСК ДАННЫХ': 'DATA RETRIEVAL',
                  'ОПТОВОЛОКОННЫЙ': 'FIBER-OPTIC',
                  'ВЗАИМОДЕЙСТВИЕ/СИНЕРГИЯ': 'SYNERGY', 'СВОРАЧИВАТЬСЯ/ЗАКРУГЛЯТЬСЯ': 'TO WRAP THIS UP',
                  'ТАЙНА/ЗАГАДКА': 'MYSTERY',
                  'НЕИЗМЕРЯЕМЫЙ': 'UNMEASURED', 'ПРОЦВЕТАНИЕ/БЛАГОПОЛУЧИЕ': 'PROSPERITY', 'НАЗНАЧАТЬ': 'TO DESIGNATE',
                  'ВЫБИТЬ/ВЫРУБИТЬ(ПР.ВЫРУБИТЬ ЭЛЕКТРИЧЕСТВО)': 'TO KNOCK OUT', 'КВАРТАЛЬНЫЙ': 'QUARTERLY',
                  'ПРОГНОЗЫ': 'PROJECTIONS',
                  'ВРАЩЕНИЕ': 'SPIN', 'ТЫ МОЖЕШЬ РАССЧИТЫВАТЬ НА МЕНЯ!': 'YOU CAN COUNT ON ME!',
                  'КОШЕРНАЯ ЕДА': 'KOSHER MEAL',
                  'АКЦИОНЕР': 'SHAREHOLDER', 'ИДЕИ/СООБРАЖЕНИЯ': 'INSIGHTS', 'РАЗВРАЩАТЬ/ИЗВРАЩАТЬ': 'TO PERVERT',
                  'РАСЧЕТ/ПОДСЧЕТ': 'ESTIMATION', 'МНЕ КАЖЕТСЯ...': 'METHINKS', 'КОПАТЬ': 'TO DIG',
                  'ДЖАКУЗИ': 'HOT TUB',
                  'КОПЫТА': 'HOOVES', 'ВЫХОДНОЕ ПОСОБИЕ': 'SEVERANCE', 'ФИНАНСОВЫЙ ДИРЕКТОР': 'CFO',
                  'ПРЕДЪЯВИТЬ ОБВИНЕНИЕ': 'TO INDICT',
                  'ГЕНЕРАЛЬНЫЙ ДИРЕКТОР': 'CEO', 'ЖЕРТВЫ/ЖЕРТВОПРИНОШЕНИЯ': 'SACRIFICES',
                  'В СЛЕДУЮЩИЙ РАЗ': 'RAIN CHECK!',
                  'ДАЙ ПЯТЬ!': 'UP HIGH!', 'ЛУЖАЙКА/ГАЗОН': 'LAWN', 'ИЗЫМАТЬ(ЗА НЕУПЛАТУ)': 'TO REPOSSESS',
                  'ПЕНСИЯ': 'PENSION',
                  'ПОХОРОНЫ': 'FUNERAL', 'НЕУВАЖИТЕЛЬНО': 'DISRESPECTFUL', 'ПОЛОВОЕ СОЗРЕВАНИЕ': 'PUBERTY',
                  'ОТОЙДИ!': 'BACK AWAY!',
                  'МНЕ СТЫДНО!': 'I AM ASHAMED!', 'ПРЕДСТАВЛЯТЬ(ЧЬИ-ТО ИНТЕРЕСЫ)': 'TO REPRESENT',
                  'ПРЕДАННОСТЬ': 'DEVOTION',
                  'СКЛОНИТЬ/ПОКЛОНИТЬСЯ': 'TO BOW', 'ВОЗДУШНЫЙ ЗМЕЙ': 'KITE', 'СЛИШКОМ': 'OVERLY', 'ВИЛКА': 'FORK',
                  'МОТЫЛЬКИ/МОЛЬ': 'MOTHS', 'КАЧЕЛИ': 'PORCH SWING', 'ПЬЯНЫЙ': 'WASTED', 'МЯСНОЙ РУЛЕТ': 'MEAT LOAF',
                  'КРАН/СМЕСИТЕЛЬ': 'FAUCET', 'ВОДА ИЗ-ПОД КРАНА': 'TAP WATER', 'РАСПРОСТРАНЕНИЕ': 'SPREAD',
                  'РАЗВЕЯТЬ': 'TO SCATTER',
                  'ИЗОБРАЖАТЬ': 'TO DEPICT', 'ЧИСТИТЬ(ПР.ОТ КОЖУРЫ БАНАН)': 'TO PEEL', 'СКОРЕЕ': 'RATHER',
                  'ЖЕЛУДИ': 'ACORNS',
                  'ХЛОПЬЯ': 'CEREAL', 'СВЕЧИ ЗАЖИГАНИЯ': 'SPARK PLUGS', 'СМЕНА': 'SHIFT', 'ПРОКЛАДКА/САЛЬНИК': 'GASKET',
                  'ЛОСОСЬ': 'SALMON', 'БЕСПОРЯДОК': 'MESS', 'ПЕРЕХОДНИК': 'ADAPTER', 'АККУРАТНО/ОПРЯТНО': 'NEATLY',
                  'ОГРОМНЫЕ ДЕНЬГИ/СОСТОЯНИЕ': 'FORTUNE', 'БАГАЖ': 'LUGGAGE',
                  'ПРИНЦИП ЕДИНСТВЕННОЙ ОТВЕТСТВЕННОСТИ': 'SINGLE RESPONSIBILITY PRINCIPLE',
                  'ПРИНЦИП ОТКРЫТОСТИ/ЗАКРЫТОСТИ': 'OPEN-CLOSED PRINCIPLE',
                  'ПРИНЦИП ПОДСТАНОВКИ ЛИСКОВ': 'LISKOV SUBSTITUTION PRINCIPLE',
                  'ПРИНЦИП РАЗДЕЛЕНИЯ ИНТЕРФЕЙСА': 'INTERFACE SEGREGATION PRINCIPLE',
                  'ПРИНЦИП ИНВЕРСИИ ЗАВИСИМОСТЕЙ': 'DEPENDENCY INVERSION PRINCIPLE',
                  'ЛЕСТНИЦА': 'LADDER', 'УЕБАНСКИЙ/УЕБИЩЕ': 'FUGLY', 'СОПЛИВЫЙ': 'SNOTTY', 'РУК ДЕЛО': 'HANDIWORK',
                  'СКОВОРОДКА': 'FRYING PAN', 'ЛОТЕРЕЯ': 'RAFFLE', 'ПРИЕМНАЯ СЕМЬЯ': 'FOSTER FAMILY',
                  'ПРИТВОРЯТЬСЯ': 'TO PRETEND',
                  'ЛАСТЫ': 'FLIPPERS', 'СЧАСТЛИВАЯ СЛУЧАЙНОСТЬ': 'FLUKE', 'ЛЫСЫЙ': 'BALD',
                  'ХВАТИТ НЕСТИ ЧУШЬ!': 'CUT THE CRAP!',
                  'ДРЯХЛЫЙ/МОРЩИНИСТЫЙ': 'WRINKLY', 'МЕРЗОСТЬ/ГАДОСТЬ': 'GROSS', 'ФАЛЬШИВЫЙ': 'BOGUS',
                  'ГОРЧИЦА': 'MUSTARD',
                  'ВОСХОЖДЕНИЕ': 'ASCENT', 'ЗАЯВЛЕНИЕ': 'STATEMENT', 'УНАСЛЕДОВАТЬ': 'TO INHERIT', 'ФАРТУК': 'APRON',
                  'ОБМАНУТЬ': 'TO TRICK', 'СКРИПКА': 'FIDDLE', 'БОЛЬНОЕ ГОРЛО': 'STREP THROAT', 'ОБВИСАТЬ': 'TO SAG',
                  'МУСОРНЫЙ БАК': 'DUMPSTER', 'НАСЛЕДНИК': 'HEIR', 'ПОДКРАДАТЬСЯ': 'TO SNUCK UP', 'МЕШОК': 'SACK',
                  'МЯСНИК': 'BUTCHER', 'РЕМОНТ': 'REPAIR', 'ГРЕТЬСЯ': 'TO BASK', 'ВЗНОС/ВКЛАД': 'CONTRIBUTION',
                  'ВЕРАНДА': 'PORCH',
                  'СТРАННО/СТРАННЫЙ': 'ODD', 'ЗАГАР': 'TAN', 'ТРУП': 'CORPSE', 'ЭГОИЗМ': 'SELFISHNESS',
                  'ИГЛА': 'NEEDLE',
                  'БОГОСЛУЖЕНИЕ': 'WORSHIP', 'Я ПОТРЯСЕН!': 'I AM STUNNED!', 'СОЖИТЕЛЬСТВОВАТЬ': 'TO SHACK UP',
                  'ФОРЕЛЬ': 'TROUT', 'ИСКРЕННИЙ': 'SINCERE', 'ПИТОМНИК': 'KENNEL', 'ВПАДАТЬ В СПЯЧКУ': 'TO HIBERNATE',
                  'ПОТОМ/ПОСЛЕ': 'AFTERWARDS', 'РАЗВЕДКА': 'RECON', 'НОВОСЕЛЬЕ': 'HOUSEWARMING', 'ВРЕД/УЩЕРБ': 'HARM',
                  'ОБИДА': 'RESENTMENT', 'НАОБОРОТ': 'CONVERSELY', 'НЕВЫНОСИМЫЙ': 'OBNOXIOUS', 'БАНКИ/КАНИСТРЫ': 'CANS',
                  'ПРОБЕГ': 'MILEAGE', 'ДИАПАЗОН/РЯД': 'RANGE', 'ГИЕНА': 'HYENA', 'ИЗМЕНЯТЬ': 'TO CHEAT',
                  'НАМАТЫВАТЬ(КАТУШКУ)': 'TO REEL',
                  'СРАТЬ': 'TO POO', 'КУРОРТ': 'RESORT', 'ОТРЫВАТЬСЯ/ПРОВОДИТЬ ВРЕМЯ': 'TO LIVE IT UP',
                  'ЭЛЕКТРОСТАНЦИИЯ/ЛОКОМОТИВ': 'POWERHOUSE',
                  'КУХНЯ(ЛОКАЛЬНАЯ)': 'CUISINE', 'НОЧНОЙ КОШМАР': 'NIGHTMARE', 'РЕЗУЛЬТАТИВНОСТЬ': 'EFFICIENCY',
                  'НЫТЬ': 'TO BITCH',
                  'СТРОКА/РЯД': 'ROW', 'СДЕРЖИВАТЬСЯ': 'TO HELD BACK', 'НИКОГДА НЕ СДАВАЙСЯ!': 'NEVER BACK DOWN!',
                  'ЯГОДЫ': 'BERRIES', 'КЛАДБИЩЕ': 'CEMETERY', 'БОГАТСТВО/СОСТОЯНИЕ': 'WEALTH',
                  'НЕЗАМЕНИМЫЙ': 'INDISPENSABLE',
                  'МОЗОЛЬ': 'CALLUS', 'ОТПЕЧАТКИ ПАЛЬЦЕВ': 'FINGERPRINTS', 'КОЛЬЦО': 'RIM',
                  'СТРОИТЕЛЬ': 'CONSTRUCTION WORKER',
                  'ЖУЛЬНИЧЕСТВО': 'HUSTLE', 'ДУБ': 'OAK TREE', 'РАКЕТА': 'MISSILE', 'ЕДИНОРОГ': 'UNICORN',
                  'МЕСТО В СОСТАВЕ': 'ROSTER SPOT', 'БУНТ/МЯТЕЖ': 'RIOT', 'ОТМЕНЕНО/ОТМЕНЕНЫ': 'REVOKED',
                  'ПРОБА/ПОПЫТКА': 'TRYOUT',
                  'Я В ВОСТОРГЕ!': 'I AM THRILLED!', 'АРЕНДОДАТЕЛЬ/ДОМОВЛАДЕЛЕЦ': 'LANDLORD',
                  'ПРОВОКАЦИЯ': 'ENTRAPMENT',
                  'ЭКСКЛЮЗИВНЫЙ/ВЫСОКОКЛАССНЫЙ': 'UPSCALE', 'БЛАГОТВОРИТЕЛЬНОСТЬ': 'CHARITY',
                  'ОБЕСПЕЧЕННЫЙ': 'WELL-OFF',
                  'КЛЮЧИЦА': 'COLLARBONE', 'ЭКИПИРОВКА': 'GEAR', 'БУЛОЧКИ': 'BUNS', 'СУДЬБА/УЧАСТЬ': 'FATE',
                  'ОБРУЧАЛЬНОЕ КОЛЬЦО': 'PROMISE RING',
                  'НАРЯД/КОСТЮМ': 'OUTFIT', 'МЕЛКИЕ РАСХОДЫ/НЕПРЕДВИДЕННЫЕ РАСХОДЫ': 'INCIDENTALS',
                  'СОМНЕНИЯ': 'QUALMS',
                  'УБОГИЙ': 'SHABBY', 'ПОЛАГАЮ/ПРЕДПОЛОГИЮ': 'PRESUME', 'УКАЗ/ПОСТАНОВЛЕНИЕ': 'DECREE',
                  'ПРОЩАЛЬНЫЙ(ПР.КОНЦЕРТ)': 'FAREWELL',
                  'ОБЛОМ': 'BUMMER', 'ИСПОРЧЕННЫЙ/ЗАРАЖЕННЫЙ': 'TAINTED', 'СДЕЛАЙ ПАУЗУ!': 'PINCH IT OFF!',
                  'БРАКОНЬЕР': 'POACHER',
                  'ЩЕДРОСТЬ': 'BOUNTY', 'МРАЧНЫЙ': 'GLOOMY', 'ЛЕСОПИЛКА': 'SAWMILL', 'ЛОБКОВЫЙ ВОЛОС': 'PUBE',
                  'ПРИДУРКИ': 'DORKS',
                  'БАБНИК/ДОНЖУАН': 'PHILANDERER', 'НЕВИННЫЙ/БЕЗВИННЫЙ': 'INNOCENT', 'ЩЕЛЬ': 'CHINK',
                  'ПОДКЛЮЧАТЬ': 'TO PLUG',
                  'ПОЗВОЛЯТЬ СЕБЕ': 'TO AFFORD', 'КОРОЛЕВСКИЙ/ЦАРСКИЙ': 'ROYAL', 'ПООБЩАТЬСЯ': 'TO MINGLE',
                  'РАЗДОБЫТЬ': 'TO RUSTLE UP',
                  'ПРОКОЛОТЬ': 'TO IMPALE', 'ВТОРЖЕНИЕ': 'INVASION', 'ВЫСКОЧКА': 'JUMPED-UP', 'НАСТАИВАТЬ': 'TO INSIST',
                  'КУЧЕРЯВЫЙ': 'CURLY', 'ШАХТА': 'SHAFT', 'КРОМЕШНАЯ ТЬМА': 'PITCH BLACK', 'ШИНА/ПОКРЫШКА': 'TYRE',
                  'РУЛЬ/КОЛЕСО': 'WHEEL',
                  'НЕУДОБСТВО/НЕПРИЯТНОСТЬ': 'NUISANCE', 'МЕТКО': 'APTLY', 'ЖИЗНЕННО ВАЖНЫЙ': 'VITAL',
                  'ПЕРЕХЕТРИТЬ': 'TO OUTWIT',
                  'ЗЛОДЕЙ': 'VILLAIN', 'ЦИКЛ': 'LOOP', 'ЭКЗЕМПЛЯР КЛАССА': 'INSTANCE OFF A CLASS', 'СХВАТКА': 'SCRUM',
                  'ОРАТЬ': 'TO YELL', 'МНЕ ТОЖЕ': 'ME EITHER', 'КОНФИСКОВАТЬ/ИЗЫМАТЬ': 'TO SEIZE',
                  'МГНОВЕННО': 'MOMENTARILY',
                  'ПРЕЛЮДИЯ': 'FOREPLAY', 'ВОСХИЩЕНИЕ': 'ADMIRATION', 'ПОМЕСТЬЕ': 'ESTATE',
                  'ДОВЕРЕННОЕ ЛИЦО': 'TRUSTEE',
                  'ЛЕКАРСТВО ПО РЕЦЕПТУ': 'PRESCRIPTION MEDICATION', 'СОРТИРОВКА СЛИЯНИЕМ': 'MERGE SORT',
                  'ПОИСК В ШИРИНУ': 'BREADTH FIRST SEARCH', 'СОРТИРОВКА ПУЗЫРЬКОМ': 'BUBBLE SORT',
                  'МАЛИНА': 'RASPBERRY',
                  'ЭМОЦИОНАЛЬНЫЕ ВСПЛЕСКИ': 'EMOTIONAL OUTBURSTS', 'ВИНИТЬ': 'TO BLAME', 'САМЫЙ СМЕЛЫЙ': 'BOLDEST',
                  'НЕУЛОВИМЫЙ': 'ELUSIVE', 'СРАЗУ ЖЕ': 'RIGHT AWAY', 'НЕТЕРПИТСЯ': 'CHOMPING AT THE BIT',
                  'ДЕРЗКИЙ': 'BRASH',
                  'МАТРАС': 'FUTON', 'БОСОЙ': 'BAREFOOT', 'ТОЧНЫЙ/ЧЕТКИЙ': 'PRECISE', 'ДРОЖЬ/ТРЕПЕТ': 'TINGLE',
                  'УГОЛЬ': 'COAL',
                  'НАЧИНКИ': 'TOPPINGS', 'СТОНАТЬ/КРЯХТЕТЬ': 'TO GROAN', 'ЛИМУЗИН': 'LIMO', 'ЭВАКУАТОР': 'TOW TRUCK',
                  'СНЕГОУБОРОЧНАЯ МАШИНА': 'SNOWPLOW', 'СЛУГА': 'VALET', 'ВРОЖДЕННЫЙ/ПРИРОДНЫЙ': 'INNATE',
                  'ПОДАВЛЯТЬ': 'TO SQUASH',
                  'СИГАРЕТКУ МОЖНО?': 'CAN I BUM A SMOKE?', 'ЛЕГКИЕ': 'LUNGS', 'ФРИЦ': 'KRAUT',
                  'НЕНОРМАТИВНАЯ ЛЕКСИКА': 'PROFANITY',
                  'КЛИЧКА': 'MONIKER', 'МАКАРОННИК': 'GREASEBALL', 'РОСКОШНЫЙ': 'RITZY',
                  'ЛАДИТЬ\УЖИВАТЬСЯ': 'GET ALONG',
                  'ЖИР': 'GREASE', 'СМЕТЬ': 'TO DARE', 'МОГУЧИЙ': 'MIGHTY', 'НЕБОЛЬШОЙ ПЕРЕРЫВ': 'BRIEF INTERMISSION',
                  'РАВНИНА': 'PLAIN', 'ОСТРЫЙ': 'SHARP', 'ДАВАТЬ ВЗЯТКУ': 'TO BRIBE', 'ФАЛЬШИВЫЙ/ПОДДЕЛЬНЫЙ': 'PHONY',
                  'БАКЛАЖАН': 'EGGPLANT', 'УСТРАИВАТЬ/ПРИСТРАИВАТЬ': 'TO ARRANGE', 'НАСИЛИЕ/ЖЕСТОКОСТЬ': 'VIOLENCE',
                  'ЧУВСТВО СОБСТВЕННОГО ДОСТОИНСТВА': 'DIGNITY', 'ПРЕОБЛАДАТЬ/ДОМИНИРОВАТЬ': 'TO PREVAIL',
                  'ГУБЕРНАТОР': 'GOVERNOR',
                  'ПРИТОРМОЗИ!': 'PULL OVER!', 'СТРАДАТЬ': 'TO SUFFER', 'ПОЧТОВАЯ МАРКА': 'STAMP',
                  'КАШЛЯТЬ': 'TO COUGH',
                  'ПЕРЕМИРИЕ': 'TRUCE', 'ПАЧКА(ПР.НАЛИЧНЫХ)': 'WAD', 'СОКРОВИЩЕ': 'TREASURE', 'БОЧКА': 'BARREL',
                  'УТЕШЕНИЕ': 'CONSOLATION',
                  'ВЗЛОМ': 'BREACH', 'ОРДЕР': 'WARRANT', 'ПРЕДУСМОТРИТЕЛЬНОСТЬ': 'PRUDENCE', 'НАРАЩИВАТЬ': 'TO RAMP UP',
                  'ПРИГОРОДНЫЙ': 'COMMUTER', 'ПРЕНЕБРЕЖИТЕЛЬНЫЙ': 'DISMISSIVE', 'СИБИРСКАЯ ЯЗВА': 'ANTHRAX',
                  'ЗАГРУЖАТЬ/ЗАКАЧИВАТЬ': 'TO UPLOAD',
                  'ИЗБАВИТЬСЯ': 'TO GET RID', 'ОСУЩЕСТВЛЯТЬ/РЕАЛИЗОВЫВАТЬ': 'TO IMPLEMENT', 'ПЛЯТЕЖ': 'PAYMENT',
                  'ИПОТЕКА': 'MORTGAGE', 'ВЗЛАМЫВАТЬ': 'TO CRACK', 'ВРУЧНУЮ': 'MANUALLY',
                  'ПРОТЯНУТЬ РУКУ ПОМОЩИ': 'LEND A HAND',
                  'ИЗМЕНЯЕМЫЕ ТИПЫ ДАННЫХ': 'MUTABLE DATA TYPES', 'НЕИЗМЕНЯЕМЫЕ ТИПЫ ДАННЫХ': 'IMMUTABLE DATA TYPES',
                  'ОБРАБОТКА ИСКЛЮЧЕНИЙ': 'EXCEPTION HANDLING', 'НАСЛЕДОВАНИЕ КЛАССОВ': 'CLASS INHERITANCE',
                  'ИНКАПСУЛЯЦИЯ': 'ENCAPSULATION', 'ООП': 'OBJECT-ORIENTED PROGRAMMING',
                  'СИСТЕМА КОНТРОЛЯ ВЕРСИЙ': 'VERSION CONTROL SYSTEM',
                  'ВЕТКА': 'BRANCH', 'УДАЛЕННЫЙ': 'REMOTE', 'ОГРАЮЛЕНИЕ': 'HEIST', 'МЕСТЬ': 'REVENGE',
                  'КЛАПАН': 'VALVE',
                  'РАЯДОМ С ': 'ALONGSIDE', 'ПЕРЕКЛЮЧИТЬ/ПЕРЕЙТИ': 'TO SWITCH', 'УПРЯМЫЙ': 'STUBBORN',
                  'РАЙОН': 'BOROUGH',
                  'КРЫЛЬЦО': 'STOOP', 'НАЗЛО': 'FOR SPITE', 'КАРТЕЖНИК/АЗАРТНЫЙ ИГРОК': 'GAMBLER',
                  'ОСКОРБЛЕНИЕ': 'OFFENSIVE',
                  'ЧЕРТА(ПР.ТВОЯ ЧЕРТА)': 'TRAIT', 'МЯТЕЖ': 'MUTINY', 'ЖАЛОВАТЬСЯ': 'TO COMPLAIN',
                  'ХОТЯ И...': 'ALBEIT',
                  'ФОЛЬГА': 'TINFOIL', 'ЖАЖДАТЬ/ТРЕБОВАТЬ': 'TO CRAVE', 'ИЗВЕСТНЫЙ/ЗНАМЕНИТЫЙ': 'RENOWNED',
                  'НЕНАВИСТЬ':'HATREDS','РАСТВОРЯТЬСЯ':'TO DISSOLVE','МАЛОЛЕТНИЙ ПРЕСТУПНИК':'JUVIE',
                  'ЗАКРЫТИЕ / ПРЕКРАЩЕНИЕ ПРЕНИЙ':'CLOSURE','БОДРЫЙ/ВЕСЕЛЫЙ':'CHIPPER','ДРАТЬСЯ':'TO STRUGGLE',
                  'ЗАТОЧКА':'SHIV','ГЛАЗУРЬ':'FROSTING','ТРАХАТЬ':'TO HUMP','КРОВЯНАЯ КОЛБАСА':'BLOOD PUDDING',
                  'СПАРИВАНИЕ/СЛУЧКА':'MATING','ИСКОПАЕМЫЙ':'FOSSIL','ПОТЕНЦИАЛ/СПОСОБНОСТЬ':'CAPACITY',
                  'ВЕЧНАЯ ЖИЗНЬ':'EVERLASTING LIFE','ПОЕСТЬ И СМЫТЬСЯ':'DINE AND DASH',
                  'ВОЗМЕЗДИЕ/РАСПЛАТА':'RETRIBUTION','ДАВАТЬ ПРАВО..':'TO ENTITLE TO...','ПРИХОТЬ/ПРИЧУДА':'WHIMSY',
                  'СДАВАТЬ В АРЕНДУ':'TO LEASE OUT','ЗАЖИГАТЬ/ЗАЖЕЧЬ(ТУСОВКА)':'TO SPARK UP',
                  'ТЕКУЩИЙ/ПОСТОЯННЫЙ':'ONGOING','НАЧАТЬ С НАЧАЛА':'START OVER',
                  'ЖИДКИЙ МЕТАЛ':'LIQUID METAL','ПЕРЕЙТИ К ДЕЛУ':'TO CUT TO THE CHASE',
                  'ГУЛЯТЬ':'TO STROLL','ПАХАТЬ':'TO PLOW','ГОЛЫЙ ПО ПОЯС':'SHIRTLESS','РОГАЛИКИ':'BAGELS',
                  'ТЩЕСЛАВИЕ/СВМОЛЮБИЕ':'VANITY','ПЕЧЬ(ЗАВОДСКАЯ)':'FURNACE','РЕБРЫШКИ':'PRIME RIB',
                  'САХАРОЗАМЕНИТЕЛЬ':'SPLENDA','РАЗНООБРАЗИЕ':'DIVERSITY','ПАРИТЬ/ВИТАТЬ':'TO HOVER',
                  'СВОДКА/КРАТКОЕ ИЗЛОЖЕНИЕ':'RUNDOWN','БОРДЕЛЬ':'BROTHEL','РУКАВА':'SLEEVES',
                  'ГЛАВНЫЙ/ЗАВЕДУЮЩИЙ':'IN CHARGE','ЧИСТИТЬ':'TO PURGE','РАСКРЫТЬ(ПОТЕНЦИАЛ)':'TO UNLEASH','НАВОЗ':'MANURE',
                  'ПОЧВА':'SOIL','ПОНЧИКИ':'DONUTS','ВОСПРИИМЧИВЫЙ':'RECEPTIVE','ВЫКУП':'BUYOUT',
                  'ОАСКРЫВАТЬ(ДЕТАЛИ)':'TO REVEAL','ЗАГЛЯНУТЬ ВНУТРЬ СЕБЯ':'TO LOOK INWARD','ПРЕДВЗЯТЫЙ':'BIASED',
                  'ПЛЮСЫ':'PROS','МИНУСЫ':'CONS','СРЕДСТВО/ЛЕКАРСТВО':'REMEDY','ГРЕМУЧАЯ ЗМЕЯ':'RATTLER',
                  'МОЛОЧНАЯ КИСЛОТА':'LACTIC ACID','ИЗВИВАТЬСЯ':'TO SQUIRM','ТЫКАТЬ':'TO POKE',
                  'БРОДЯГИ':'TRAMP','ПРИСТАВАТЬ/ДОСТАВАТЬ':'PESTERING',
                  'УЧЕНИК':'APPRENTICE', 'ОГРОМНЫЙ':'VAST','УНИЧТОЖЕНИЕ/ИСТРЕБЛЕНИЕ':'EXTERMINATION','АНГАР':'HANGAR',
                  'ПРОПАСТЬ':'PRECIPICE','ДО ТЕХ ПОР ПОКА':'AS LONG AS','САЛЬТО':'BACKFLIP',
                  'СЕТИ ПРЯМОГО РАСПРОСТРАНЕНИЯ':'FEEDFORWARD NETWORKS','ГИБКИЙ/ЭЛАСТИЧНЫЙ':'FLEXIBLE',
                  'АКТИВЫ':'ASSETS','ПРИНИМАТЬ УЧАСТИЕ':'TO PARTICIPATE','РЕГУЛИРУЕМЫЙ':'ADJUSTABLE',
                  'ВСТРАИВАТЬ':'TO EMBED','ПОСЛЕДОВАТЕЛЬНОСТЬ/ЦЕПОЧКА':'SEQUENCE',
                  'МАТРИЧНОЕ УМНОЖЕНИЕ':'MATRIX MULTIPLICATION','ПРЕОБРАЗОВЫВАТЬ':'TO CONVERT','ПЕРЕОБУЧЕНИЕ':'RETRAINING',
                  'РАСПОЗНОВАНИЕ ОБЪЕКТОВ':'OBJECT RECOGNITION','Я НЕ ПОНИМАЮ':'I DONT GET IT','СЖИМАТЬ':'TO CLENCH',
                  'ЯГОДИЦЫ':'BUTTOCKS','ПРОБЛЕМА С ПОВЕДЕНИЕМ':'ATTITUDE PROBLEM','ШТАБ-КВАРТИРА':'HEADQUARTER',
                  'ЛУЧШИЙ ВЫПУСКНИК':'VALEDICTORIAN','САРДЕЛЬКА':'WIENER','НЕДООЦЕНЕННЫЙ':'UNDERRATED','ВЫПУСКНОЙ ВЕЧЕР':'PROM',
                  'УМНИК':'WISENHEIMER','УХМЫЛКА':'GRIN','ОБОСРАТЬСЯ':'TO SHIT YOURSELF','КРОВОТЕЧЕНИЕ':'BLEEDER',
                  'СЫЩИК':'INVESTIGATOR','ССЫКУН':'PISSER','АЛКАШ':'ALKY','БУХЛО':'BOOZE',
                  'УТВЕРДИТЕЛЬНЫЙ/ПОЛОЖИТЕЛЬНЫЙ':'AFFIRMATIVE','КАБАК':'GIN MILL','РЕВ/ГУЛ/ГРОХОТ':'ROAR',
                  'ГРАБИТЬ':'TO PILFER','КУРЯТНИК':'HENHOUSE','ЧЕЛЮСТЬ':'JAW','НЕЧЕСТНАЯ ИГРА':'UNFAIR GAME',
                  'ПОЧИК':'KIDNEYS','ВЕРА':'FAITH','ПЛЕМЯННИК':'NEPHEW','МНЕ ГЛУБОКО НАПЛЕВАТЬ':'I DONT GIVE A RATS ASS',
                  'СРЕДНЕВЕКОВЬЕ':'MEDIEVAL','ПРОКАЖЕННЫЙ':'LAPER','СТИПЕНДИЯ':'SCHOLARSHIP',
                  '(ЧТО-ТО/КТО=ТО)УПУСКАЮТСЯ ИЗ ВИДУ ':'OVERLOOKED FOR','ОЧЕВИДНЫЕ НЕДОСТАТКИ':'PERCEIVED FLAWS',
                  'ВНЕШНОСТЬ':'APPEARANCE','НАПЛЕВАТЬ':'TO GIVE A SHIT','БЛИЗОСТЬ(ПР.К ОКЕАНУ)':'PROXIMITY',
                  'ИСТЕКАТЬ/ЗАКАНЧИВАТЬСЯ':'TO EXPIRE','КОНТЕЙНЕРЫ':'BINS','СРЕДНИЙ/УСРЕДНЕННЫЙ':'MEDIAN',
                  'ПЕРЕСТАНОВКА':'PERMUTATION','ТРОТУАР':'SIDEWALK','ИССЛЕДОВАНИЕ':'RESEARCHING','ВОРЧЛИВЫЙ':'GROUCHY',
                  'ВОЛОСАТЫЙ':'HAIRY','ИСКРЕВЛЕНИЕ НОСОВОЙ ПЕРЕГОРОДКИ':'DEVIATED SEPTUM','СОВЕТ':'TIP','В ЛЮБОЕ ВРЕМЯ':'WHENEVER',
                  'НИ С ТОГО НИ С СЕГО':'APROPOS OF NOTHING','РЫДАТЬ':'TO SOB','НОМЕРНОЙ ЗНАК(АВТО)':'LICENSE PLATE',
                  'УГЛЕВОДЫ':'CARBS','ШЛЮПКА':'SKIFF','ГОРШОК(ТУАЛЕТ)':'POTTY','РАСЦВЕТАТЬ/ЦВЕСТИ':'TO BLOOM',
                  'УТОЧНЯТЬ/ПРОЯСНЯТЬ':'TO CLARIFY','БЛЮДЕЧКО':'SAUCER','ТЕМА':'SUBJECT','ЖАРКОЕ В ГОРШОЧКЕ':'POT ROAST',
                  'НЕДОВАРЕННОЕ/НЕДОЖАРЕННОЕ':'UNDERCOOKED','ДОЛГАЯ КРАТКОСРОЧНАЯ ПАМЯТЬ':'LONG SHORT-TERM MEMORY',
                  'ЖМОТ':'MISER','УПРАВЛЯЕМЫЕ РЕКУРЕНТНЫЕ БЛОКИ':'GATED RECURRENT UNITS',
                  'ОПРОС КЛИЕНТОВ': 'CUSTOMER SURVEYS', 'СМУГЛЫЙ': 'DUSKY', 'ЭКСКАВАТОР': 'DIGGER',
                  'АБРАЗИВНЫЙ/РЕЗКИЙ': 'ABRASIVE', 'НЕПРИЯТНЫЙ': 'DISTASTEFUL', 'КРУЖКА/ЧАШКА': 'MUG',
                  'БОРМОТАТЬ/МЯМЛИТЬ': 'TO MUMBLE', 'ОЧАРОВАНИЕ': 'CHARM', 'ВЫСОКОМЕРНЫЙ': 'ARROGANT',
                  'ВРАЖДЕБНЫЙ': 'HOSTILE', 'ГРАНИЦЫ/РАМКИ': 'BOUNDARIES', 'БОМЖ': 'HOBO',
                  'ПЕРЕВЕРНУТЬСЯ': 'TO ROLL OVER', 'УГОЛОК/ЗАКУТОК': 'NOOK', 'НЕКОТОРОЕ ВРЕМЯ': 'FOR WHILE',
                  'СОВЕРШИТЬ БОЛЬШОЙ СКАЧОК': 'TO TAKE A BIG LEAP', 'НЕ ПОКЛАДАЯ РУК': 'TIRELESSLY',
                  'НАВЯЗЧИВЫЙ': 'INTRUSIVE', 'СУТОЧНЫЕ': 'PER DIEM', 'ГЛОТОК': 'SIP', 'ВЗДРЕМНУТЬ': 'TO NAP',
                  'КРАСОВАТЬСЯ/ВЫСТАВЛЯТЬ НА ПОКАЗ': 'TO FLAUNT', 'ОПЬЯНЯЮЩИЙ': 'INTOXICATING',
                  'РАЗВЕДАТЬ': 'TO SCOPE OUT', 'СОКРАЩАТЬСЯ': 'TO SHRINK',
                  'ТРЯПОЧКА/ТРЯПКА': 'RAG', 'ВСПЛЕСК/ВОЛНА': 'SURGE', 'ПОДГОТОВЛЕННОСТЬ/ГОТОВНОСТЬ': 'PREPAREDNESS',
                  'В ЯРОСТИ/ВНЕ СЕБЯ': 'LIVID', 'РАЗВЛЕКАТЬ/ВЕСЕЛИТЬ': 'TO AMUSE',
                  'ВЗЯТЬ НА СЕБЯ/ЗАВЛАДЕТЬ': 'TO TAKE OVER',
                  'ХОРОНИТЬ': 'TO BURY', 'БОЛЬШОЙ АЖИОТАЖ': 'A LOT OF BUZZ', 'ЛУГ': 'MEADOW', 'ЖАРЕННЫЙ': 'ROAST',
                  'КАРЛИК': 'MIDGET', 'ГОЛЫЕ СИСЬКИ': 'BARE BOOBS', 'ВНЕ/ЗА ПРЕДЕЛОМ': 'BEYOUND',
                  'НА ЗАДНЕМ ПЛАНЕ': 'ALL THE WAY IN THE BACK', 'НАБРОСАТЬ/ЗАПИСАТЬ': 'TO JOT DOWN',
                  'СОСУЛЬКА': 'ICICLE',
                  'ВОПРОС ВРЕМЕНИ': 'MATTER OF TIME', 'ВОНЯТЬ': 'TO REEK', 'ПРОНИЦАТЕЛЬНЫЙ': 'INSIGHTFUL',
                  'СУРОВЫЙ/ЖЕСТКИЙ': 'HARSH',
                  'ТРАВЫ': 'HERBS', 'САНИ/САНКИ': 'TOBOGGAN', 'ОТЧАЯНИЕ/БЕЗЫСХОДНОСТЬ': 'DESPAIR',
                  'ИБМИЦИЛ': 'IMBECILE',
                  'ВОСКЛИЦАТЕЛЬНЫЙ ЗНАК': 'EXCLAMATION POINT', 'ОСКОРБИТЕЛЬНО': 'INSULTING',
                  'ААКЦЕНТ/УПОР/ОСОБОЕ ВНИМАНИЕ': 'EMPHASIS',
                  'ПОСЛЕДСТВИЯ': 'CONSEQUENCES', 'ГОРАЗДНО/ЗНАЧИТЕЛЬНО': 'VASTLY',
                  'СУДЕБНЫЙ ПРОЦЕСС': 'LAWSUIT', 'ИСПЫТАТЕЛЬНЫЙ СТРОК': 'PROBATION', 'СТОЛ/ПИСЬМЕННЫЙ СТОЛ': 'DESK',
                  'ХОЛСТ/ПОЛОТНО': 'CANVAS', 'ЗАМАНИВАТЬ': 'TO LURE',
                  'БУДЬ ЗДОРОВ!': 'BLESS YOU!', 'ФИНАНСОВЫЙ ГОД': 'FISCAL YEAR', 'ЯРМАРКА ТРУДА(ВАКАНСИЙ)': 'JOB FAIR',
                  'САМОЗВАНЕЦ': 'IMPOSTER', 'ГАРНИТУРА': 'HEADSET',
                  'ЛИГА ПЛЮЩА': 'IVY LEAGUE', 'СВИДЕТЕЛЬ': 'WITNESS',
                  'НАВЫКИ ПОНИМАНИЯ': 'COMPREHENSION SKILLS',
                  'ПОЛНОЕ ПРАВО/ВСЕ ПОЛНОМОЧИЯ': 'FULL AUTHORITY',
                  'ОРГАНИЗАЦИОННАЯ СТРУКТУРА': 'ORG CHART', 'ЩЕКОТАТЬ': 'TO TICKLE',
                  'НЕ ТРЕБУЮЩЕЕ ОБЪЯСНЕНИЙ': 'SELF-EXPLANATORY',
                  'ЦЕМЕНТ': 'CEMENT', 'МЕЧТА ВСЕЙ ЖИЗНИ': 'LIFELONG DREAM', 'ИНИЦИАЛЫ': 'INITIALS',
                  'УВЕКОВЕЧИТЬ': 'TO IMMORTALIZE', 'ПРИЛАГАТЕЛЬНОЕ': 'ADJECTIVE', 'ЧТОБЫ/ДЛЯ ТОГО': 'IN ORDER',
                  'ЗАРЯЖАТЬ ЭНЕРГИЕЙ': 'TO ENERGIZE', 'ПРОСАЧИВАТЬСЯ': 'TO PRECOLATE', 'ЗАИКАТЬСЯ': 'TO STUTTER',
                  'НАХАЛЬНЫЙ': 'SASSY', 'ЦАРАПИНА': 'SCRATCH', 'АВТОМОБИЛЬ-УНИВЕРСАЛ': 'WAGON',
                  'ЗЕВАТЬ': 'TO YAWN', 'ПОЯС ВЕРНОСТИ': 'CHASTITY BELT', 'С ДРУГОЙ СТОРОНЫ..': 'ON THE FLIP SIDE',
                  'БДИТЕЛЬНЫЙ': 'VIGILANT', 'ДЕЖУРНЫЙ': 'HALL MONITOR', 'ЗАПИХИВАТЬ/ЗАСОВЫВАТЬ': 'TO STUFF',
                  'ИСКЛЮЧАТЬ': 'TO PRECLUDE', 'ШЕЙКА МАТКИ': 'CERVIX', 'СПЕЛЫЙ': 'RIPE', 'ЗАБЛУЖДЕНИЕ': 'DELUSION',
                  'ВЫБОИНЫ': 'POTHOLES', 'ОБЕЗБОЛИТЬ(ВВЕСТИ МЕСТНЫЙ НАРКОЗ)': 'TO NUMB UP', 'АИСТ': 'STORK',
                  'СВЕРТОЧНЫЕ НС': 'CONVOLUTIONAL NEURAL NETWORKS',
                  'ЗАВОЕВЫВАТЬ':'TO CONQUER','ПЛАКАТЬ/ПЛАКАЛ':'TO WEEP \ TO WEPT','ТОЧНОСТЬ/АККУРАТНОСТЬ':'EXACTNESS',
                  'ПРОТИВОПОЛОЖНЫЙ/ОБРАТНОЕ':'CONTRARY','ОБЛИГАЦИИ НА ПРЕДЪЯВИТЕЛЯ':'BEARER BONDS',
                  'СЕЙФ':'VAULT','ПРЕДСЕДАТЕЛЬ/ГЛАВА':'CHAIRMAN','МЕНЯТЬ/ИЗМЕНЯТЬ(ЧТО-ТО)':'TO ALTER',
                  'ТРАНСЛИРОВАТЬ/ПЕРЕДАВАТЬ':'TO TRANSMIT','СТРАШНЫЙ/УЖАСНЫЙ':'FRIGHTFUL',
                  'ЛОЖНЫЙ СЛЕД/ГОНЯТЬСЯ ЗА ПРИЗРАКАМИ':'WILD-GOOSE CHASE','ШААРИТЬ/ВОЗИТЬСЯ':'TO FUMBLE',
                  'ЛОЖКА ДЕГТЯ В БОЧКЕ МЕДА':'FLY IN THE OINTMENT','ТРЕБОВАНИЯ О ВЫКУПЕ':'RANSOM DEMANDS',
                  'ГЛУШИТЕЛЬ': 'MUFFLER', 'ВАРЕЖКИ/РУКАВИЦЫ': 'MITTENS', 'НЕГИГИЕНИЧНО': 'UNSANITARY',
                  'ПОВЕСТКА ДНЯ': 'AGENDA',
                  'ЗЕЛЬЕ/ЭЛЕКСИР': 'POTION', 'ВЫДЕЛИТЬ': 'TO ALLOT', 'ДЕДОВЩИНА': 'HAZING', 'ОТСТОЙНЫЙ': 'LAME',
                  'ПРЕДРАССУДОК': 'PREJUDICE', 'ПАПКА-СКОРОСШИВАТЕЛЬ': 'BINDER', 'ОСТАТКИ(ПИЩИ)': 'LEFTOVERS',
                  'ПЕЛЬМЕНИ': 'DUMPLINGS', 'ВЕСЫ': 'SCALES', 'ПРЕСС/КУБИКИ': 'ABS', 'АРКА': 'ARCH',
                  'ОСОБНЯК': 'MANSION',
                  'ЧАЙКА': 'SEAGULL', 'ЛИПКИЙ': 'TACKY', 'ОЖИРЕНИЕ': 'OBESITY', 'НАБИРАТЬ(ВЕС)': 'TO GAIN',
                  'САЧКОВАТЬ/ФИЛОНИТЬ': 'TO SLACK', 'МЕТОД СОБЛАЗНЕНИЯ': 'SEDUCTION METHOD',
                  'ЗНАКОМЫЕ': 'ACQUAINTANCES',
                  'СУМОЧКА/КОШЕЛЕК': 'PURSE', 'ОПРАВДЫВАТЬ/ЗАКРЫВАТЬ ГЛАЗА': 'TO CONDONE',
                  'НАДУТЬ/РАЗДУВАТЬ': 'TO INFLATE',
                  'НЕПРИВЛЕКАТЕЛЬНЫЙ': 'UNAPPEALING', 'УЛОВКА/ХИТРОСТЬ': 'RUSE', 'ЗАСТАВИТЬ/ВЫНУДИТЬ': 'TO FORCE',
                  'ЯЗВА': 'ULCER', 'ВОРОНА': 'CROW', 'СОЛЬНЫЙ КОНЦЕРТ': 'RECITAL', 'КАПЛЯ': 'DRIP',
                  'ИНОГДА': 'ONCE IN A WHILE', 'ПРИМЕРНО/ПРИБЛИЗИТЕЛЬНО': 'APPROXIMATELY', 'СВЯЗИ': 'LIAISONS',
                  'СРЕДНИЙ АБСОЛЮТНЫЙ ПРОЦЕНТ ОШИБОК': 'MEAN ABSOLUTE PERCENTAGE ERROR',
                  'СРЕДНИЙ КВАДРАТ ЛОГАРИФМИЧЕСКИХ ОШИБОК': 'MEAN SQUARED LOGARITHMIC ERROR',
                  'ОКАЗЫВАЕТСЯ/ПОЛУЧАЕТСЯ': 'TURNS OUT', 'ЗАПЯСТЬЕ': 'WRIST', 'ВЕСЕЛЫЙ/СМЕШНОЙ': 'HILARIOUS',
                  'ПЕРЕМАНИТЬ': 'TO POACH', 'СТОЛОВЫЕ ПРИБОРЫ': 'FLATWARE', 'УВЕЛИЧИТЬ': 'TO AUGMENT',
                  'ТОШНОТА': 'QUEASY',
                  'СВИДЕТЕЛЬСКИЕ ПОКАЗАНИЯ': 'TESTIMONY', 'ТРЕЗВЫЙ': 'SOBER', 'ПОКРОВИТЕЛЬСТВОВАТЬ': 'TO PATRONIZE',
                  'ЦЕРЕМОНИЯ ПОСВЯЩЕНИЯ': 'INDUCTION CEREMONY', 'ДНЕВНИК': 'DIARY', 'ЖУТКИЙ': 'EERIE',
                  'ДАВАТЬ ПОКАЗАНИЯ': 'TO TESTIFY', 'КОМОК': 'LUMP', 'ОШИБОЧНЫЙ': 'FLAWED',
                  'КРАЙНЕ/МАКСИМАЛЬНО': 'UTMOST',
                  'ЧТО КАСАЕТСЯ...': 'REGARDING', 'КАНДИДАТ': 'CONTENDER', 'ТЕННИСНАЯ РАКЕТКА': 'PADDLE',
                  'ЗАКУСКИ/АПЕРИТИВ': 'APPETIZERS', 'ЗАПАХ': 'ODOR', 'КОСТЕР': 'BONFIRE', 'ПСИХУШКА': 'ASYLUM',
                  'СВЕРНУТЬСЯ КАЛАЧИКОМ': 'TO CURL UP', 'ЩЕНОК': 'PUPPY', 'ПРЕДПОЧТЕНИЕ': 'PREFERENCE',
                  'СВЕКОЛЬНЫЙ САЛАТ': 'BEET SALAD', 'ЗУД': 'ITCH', 'ИЛИ/ЛИБО': 'EITHER',
                  'ВОЗМЕЩЕНИЕ РАСХОДОВ': 'REIMBURSEMENT',
                  'ИНАЧЕ': 'OTHERWISE', 'ЗАЩИТА СВИДЕТЕЛЕЙ': 'WITNESS PROTECTION', 'ОХЛАЖДЕНИЕ': 'REFRIGERATION',
                  'НЕНУЖНЫЕ': 'NON-ESSENTIAL', 'ГУСЬ': 'GOOSE', 'БУКСИР/РЫВОК': 'TUG',
                  'ПО НАШИМ ДАННЫМ': 'ACCORDING TO OUR RECORDS',
                  'УЛЬТРАСОВРЕМЕННЫЙ': 'CUTTING EDGE', 'МАССАЖ СПИНЫ': 'BACK RUBS', 'ГОРОДСКАЯ АТМОСФЕРА': 'URBAN VIBE',
                  'ПОСЛЕДОВАТЕЛЬНОСТЬ': 'SEQUENTIAL', 'СРЕДНЕКВАДРАТИЧНАЯ ОШИБКА': 'MEAN SQUARED ERROR',
                  'КОМПИЛИРОВАТЬ': 'TO COMPILE', 'ОПТИМИЗАТОР': 'OPTIMIZER', 'ПОТЕРЯ': 'LOSS',
                  'ОБУЧАЮЩАЯ ВЫБОРКА': 'TRAINING SAMPLE', 'НАПАДАЮЩИЙ УДАР В ВОЛЕЙБОЛЕ': 'SPIKE',
                  'РЕКЛАМНЫЕ РОЛИКИ': 'COMMERCIALS', 'НЕТ В НАЛИЧИИ': 'OUT OF STOCK', 'КЛЮЧЕВАЯ СЦЕНА': 'PIVOTAL SCENE',
                  'СТАЩИТЬ/ПОХИЩАТЬ': 'TO SNATCH', 'ДРАНИКИ': 'HASH BROWNS', 'МОЧКА УХА': 'EARLOBE',
                  'ПРАЗДНИК/ПИР': 'FEAST', 'БИНАРНАЯ КРОСС-ЭНТРОПИЯ': 'BINARY CROSSENTROPY',
                  'КАТЕГОРИАЛЬНАЯ КРОСС-ЭНТРОПИЯ': 'CATEGORICAL CROSSENTROPY',
                  'СРЕДНИЙ МОДУЛЬ ОШИБОК': 'MEAN ABSOLUTE ERROR',
                  'КОГОТЬ': 'CLAW', 'КЛОЧЬЯ/КУСКИ': 'SHREDS', 'КАРТОШКА ФРИ': 'FRENCH FRIES',
                  'РЕДАКТИРОВАТЬ': 'TO EDIT',
                  'РЕКЛАМА': 'ADS', 'БОЛТАТЬСЯ/СВИСАТЬ': 'TO DANGLE', 'ПОДГЛЯДЫВАТЬ': 'TO PEEP', 'АРАХИС': 'PEANUT',
                  'НЕДУГ': 'AFFLICTION', 'БЕЗГРАМОТНЫЙ': 'ILLITERATE', 'НЫТИК': 'DOWNER',
                  'СДЕРЖАННЫЙ/ОСТОРОЖНЫЙ': 'DISCREET',
                  'ПОЗОР': 'INFAMY', 'НЕ ДАВИ НА МЕНЯ!': 'DO NOT RUSH ME!', 'СКОРБИТЬ': 'TO GRIEVE', 'ЕНОТ': 'RACOON',
                  'БЕСКОНЕЧНОСТЬ': 'INFINITY', 'КАПИТАЛЬНЫЙ РЕМОНТ/ПЕРЕСТРОЙКА': 'OVERHAUL',
                  'СТАРУХА С КОСОЙ': 'GRIM REAPER',
                  'БОЛЬШИЕ УСПЕХИ': 'GREAT STRIDES', 'ХАМ/БОЛВАН': 'TWERP', 'ПОЧИТАТЬ/ЧТИТЬ': 'TO REVERE',
                  'ЧЕРНИЛА': 'INK',
                  'ГУРМАН': 'GOURMET', 'ОТТАЛКИВАЮЩИЙ/ОТВРАТИТЕЛЬНЫЙ': 'REPULSIVE', 'СУТЬ/СУЩНОСТЬ': 'ESSENCE',
                  'НЕСЧАСТНЫЙ': 'MISERABLE', 'МАКЕТЫ': 'MOCK-UPS', 'ПИЯВКА': 'LEECH', 'ИЗОБРЕТЕНИЕ': 'INVENTION',
                  'РУМЯНЫЕ ЩЕЧКИ': 'RUDDY CHEEKS', 'ХИХИКАТЬ': 'TO GIGGLE', 'СТРИНГИ': 'THONG',
                  'БОЛЬНИЧНЫЙ': 'SICK LEAVE', 'ДЕРЗКИЙ/ПИКАНТНЫЙ': 'SAUCY', 'ПАРИК': 'WIG',
                  'ДВОЙНИК': 'IMPERSONATOR', 'ОТ ДВОЙКИ ДО': 'DEUCE TO', 'МОЮЩЕЕ СРЕДСТВО': 'DETERGENT',
                  'ТИРАН': 'TYRANT', 'РИФМА': 'RHYME', 'ПУСКАТЬ СЛЮНИ': 'TO SALIVATE', 'ЗАКОННО': 'LAWFULLY',
                  'ПОЧЕТНЫЙ ПРОФЕССОР': 'EMERITUS', 'ХВАСТЛИВЫЙ': 'BRAGGY', 'ФОНД/ФУНДАМЕНТ': 'FOUNDATION',
                  'СТУЛ/КАЛ': 'STOOL', 'К СЧАСТЬЮ': 'FORTUNATELY', 'КОНКУРИРОВАТЬ': 'TO COMPETE',
                  'ОБОРОТЕНЬ': 'WEREWOLF',
                  'ДЛЯ УДОБСТВА': 'FOR THE CONVENIENCE', 'УСТАРЕВШИЙ': 'OBSOLETE', 'ОТВАЛИ ОТ МЕНЯ!': 'GET OFF ME!',
                  'ВЫЧИТАТЬ': 'TO SUBSTRACT', 'ДОКАЗАТЕЛЬСТВО': 'PROOF', 'ИЗГНАНИЕ': 'EXILE',
                  'УБРАТЬ/УНИЧТОЖИТЬ': 'TO TAKE OUT',
                  'ПРЯМОЙ ВОПРОС': 'DIRECT QUESTION', 'СБЕРЕГАТЕЛЬНЫЙ СЧЕТ': 'NUMBERED ACCOUNT', 'СЕТИ': 'GRIDS',
                  'СВАРЩИК': 'WELDER', 'ЯКОРЬ': 'ANCHOR', 'ЦЫГАН': 'GIPSY', 'ШИШКА': 'BUMP', 'ВСТРЕЧА': 'APPOINTMENT',
                  'ГНАТЬСЯ/ПРЕСЛЕДОВАТЬ': 'TO CHASE', 'ЗАГВОЗДКА/ЗАМИНКА': 'HITCH',
                  'НА ЮГ/ЮЖНОЕ НАПРАВЛЕНИЕ': 'SOUTHBOUND',
                  'ТОРМОЗИТЬ МЕНЯ': 'TO SLOW ME DOWN', 'ЗАЛОГ': 'COLLATERAL', 'БАЗОВЫЕ ЗНАНИЯ': 'CORE KNOWLEDGE',
                  'ИСКУСТВЕННЫЙ ИНТЕЛЕКТ': 'ARTIFICIAL INTELLIGENCE', 'ЗНАМЕНИТОСТЬ': 'CELEBRITY',
                  'БЕШЕНСТВО': 'RABIES', 'ИСКОРЕНИТЬ': 'TO ERADICATE', 'ПОВОД': 'CAUSE',
                  'КРЕСТЯНИН/ДЕРЕВЕНЩИНА': 'PEASANT',
                  'ЗАМКНУТЫЙ КРУГ': 'VICIOUS CIRCLE', 'НАТИРАТЬСЯ/РАЗДРАЖАТЬСЯ (КОЖА)': 'TO CHAFE',
                  'БУКВАЛЬНО': 'LITERALLY', 'УДОЧКА': 'ROD', 'СПОРТИВНЫЙ КОММЕНТАТОР': 'SPORTSCASTER',
                  'ГЛОТАТЬ': 'TO SWALLOW', 'ХОТЯ, ЕСЛИ ЧЕСТНО': 'THOUGH TO BE FAIR', 'ГИПСОКАРТОН': 'DRYWALL',
                  'СЛАБЫЙ/ТУСКЛЫЙ': 'FAINT', 'ПОДЛИЗЫВАТЬСЯ КО МНЕ': 'TO SUCK UP TO ME',
                  'МЕТАЛЛОЛОМ': 'SCRAP', 'ГРЯЗЬ': 'GUNK', 'РОЗЕТКА': 'SOCKET', 'ДРАГОЦЕННЫЙ': 'PRECIOUS',
                  'ОТКРОЙ КАПОТ': 'TO POP THE HOOD', 'ОБОРВАНЕЦ': 'RAGAMUFFIN', 'ЛИШАТЬ ДЕВСТВЕННОСТИ': 'TO DEFLOWER',
                  'ЧЕРНАЯ ПОЛОСА/ТЯЖЕЛЫЙ ПЕРИОД': 'ROUGH PATCH', 'МАЛЬЧИШНИК': 'BACHELOR PARTY',
                  'ПЕРСОНАЛЬНОЕ ВНИМАНИЕ': 'PERSONALITY MIRRORING', 'АРОМАТ': 'FLAVOR', 'ТЕМ ВРЕМЕНЕМ': 'MEANWHILE',
                  'МОРСКИЕ ПЕХОТИНЦЫ': 'MARINES', 'ЯСТРЕБ': 'HAWK', 'БОЖЬЯ КОРОВКА': 'LADYBUG',
                  'ПРЕУВЕЛИЧЕНИЕ/УТРИРОВАНИЕ': 'EXAGGERATION', 'ШАНТАЖ/ВЫМОГАТЕЛЬСТВО': 'BLACKMAIL',
                  'МАЛЬЧИК НА ПОБЕГУШКАХ': 'BELLBOY', 'ПЛЕМЯННИЦА': 'NIECE', 'ОБМАНУТЬ МЕНЯ': 'FOOL ME',
                  'ПЕТУХ': 'ROOSTER', 'КУКАРЕКАТЬ': 'TO CROW', 'ОТСТУПИТЬ/УЙТИ С ПОСТА': 'TO STEP DOWN',
                  'ДОБИВАТЬСЯ УСПЕХА': 'TO SUCCEED', 'АЛЬФА-САМЕЦ': 'ALPHA MALE', 'ОТБОЙНЫЙ МОЛОТОК': 'JACKHAMMER',
                  'БЕСПОЩАДНЫЙ': 'MERCILESS', 'ДОПОЛНЕНИЕ': 'ADDITION', 'ЭТО МЕНЯ ПУГАЕТ': 'IT CREEPS ME OUT',
                  'НАДОЕДЛИВЫЙ/РАЗДРАЖАЮЩИЙ': 'ANNOYING', 'ПЕТАРДЫ': 'FIRECRACKERS', 'ОСЕЛ': 'DONKEY',
                  'ОЧЕНЬ БОЛЬШОЙ': 'HUGE', 'ОЧЕНЬ ОПАСНЫЙ': 'PERILOUS', 'ОЧЕНЬ СТАРЫЙ': 'FRAIL',
                  'ОЧЕНЬ УВЕРЕННО': 'CERTAIN', 'СИЛЬНО ПЕРЕЖИВАЮЩИЙ': 'DISTRESSED',
                  'БЛУЗКА': 'BLOUSE', 'ЗУБНАЯ НИТЬ': 'FLOSS', 'ИГРА СЛОВ/КАЛАМБУР': 'PUN',
                  'ПОНИЗИТЬ/РАЗЖАЛОВАТЬ': 'TO DEMOTE', 'СОЮЗНИК/ПОМОЩНИК': 'ALLY',
                  'ПРЕДАТЬ': 'TO BETRAY', 'СТАТУЯ/СКУЛЬПТУРА': 'STATUE', 'ТОРГОВЫЙ АВТОМАТ': 'VENDING MACHINE',
                  'ГОРЕ/ПЕЧАЛЬ': 'GRIEF', 'ОТРИЦАНИЕ': 'DENIAL', 'ПРОМЕЖНОСТЬ/ПАХ': 'CROTCH',
                  'ПОСТАВКА/ПАРТИЯ/ГРУЗ': 'SHIPMENT', 'КЛЮВ': 'BEAK', 'ЗАБОЙ': 'TO SLAUGHTER',
                  'ВЗДОР/ЧЕПУХА': 'BALONEY', 'МЕТЛА': 'BROOM', 'ВОЗМУЩЕНИЕ': 'OUTRAGE', 'ПРЕДАТЕЛЬ': 'TRAITOR',
                  'ПРОТИВОСТЯТЬ': 'TO CONFRONT', 'ЗАГРЯЗНЯТЬ': 'TO POLLUTE', 'ОБГОНЯТЬ': 'TO OUTRUN',
                  'Я СВАЛИВАЮ ОТСЮДА': 'I AM OUTTA HERE', 'ТУАЛЕТНАЯ КАБИНКА': 'BATHROOM STALL',
                  'ПОЛДЕНЬ': 'NOON', 'ПАРТИЯ': 'BATCH', 'ЧАСТО ЗАЯВЛЯТЬ О СЕБЕ': 'NAME REPETITION',
                  'СЕСТЬ НА МЕЛЬ': 'TO RUN AGROUND', ',БУЙНЫЙ/ШУМНЫЙ': 'ROWDY', 'РАССТАТЬСЯ': 'TO BREAK UP',
                  'СРОЧНЫЙ(ВОПРОС)': 'URGENT', 'ПРЫГАТЬ/СКАКАТЬ': 'HOP', 'ЛОКОТЬ': 'ELBOW',
                  'СТОЛБ(ЭЛКТРОПЕРЕДАЧ)': 'POLE',
                  'УПОМИНАТЬ': 'TO MENTION', 'ЛЕЧЕНИЕ': 'TREATMENT', 'КАПРИЗНЫЙ': 'FUSSY',
                  'КУРИЦА-ГРИЛЬ': 'ROTISSERIE CHICKEN', 'КОРОЧЕ/КОМПАКТНЕЕ': 'CHUNKIER',
                  'ВТИРАТЬ/НАТИРАТЬ': 'TO RUB', 'НЕСОКРУШИМЫЙ': 'INDESTRUCTIBLE',
                  'ИМИТИРОВАТЬ/ВЫСМЕИВАТЬ': 'TO MOCK', 'ТРЯПКА/СЛАБАК': 'WUSS', 'ЗАЖАТЬ/ЗАЖИМАТЬ': 'TO CLAMP',
                  'СОТРЯСЕНИЕ МОЗГА': 'CONCUSSION', 'БЛЕВОТИНА': 'VOMITY',
                  'ТУПОЙ/ТУСКЛЫЙ': 'DULL', 'ЗАФИКСИРОВАТЬ/СОВЕРШИТЬ': 'TO COMMIT', 'ПОДЧИНЯТЬСЯ': 'TO OBEY',
                  'УСПОКОИТЕЛЬНОЕ': 'CHILL PILL', 'КОСЯК': 'JOINT', 'МИР ВАМ!': 'PEACE OUT!', 'КОСЯЧОК': 'DOOBIE',
                  'ЗАКУСКИ': 'MUNCHIES', 'СГЛАЗ': 'JINX', 'ЖЕСТКИЙ': 'RIGID', 'ПОСЛЕ/НАД': 'UPON',
                  'ЦЕЛЬ/НАЗНАЧЕНИЕ': 'PURPOSE', 'ОТКАЗАТЬСЯ': 'TO REFUSE', 'ПРИСЯГА/КЛЯТВА': 'OATH',
                  'ПОД ПРИСЯГОЙ': 'SWORN IN', 'ПАХ': 'GROIN',
                  'СПАСАТЕЛЬНЫЕ ЖИЛЕТЫ': 'LIFE PRESERVERS', ' ПЕРВОБЫТНЫЙ': 'PRIMAL',
                  'ДРЕВНИЕ ВРЕМЕНА': 'ANCIENT TIMES',
                  'ПОШЛЫЙ/НЕПРИСТОЙНЫЙ': 'FILTHY', 'ЛИЦЕМЕР': 'HYPOCRITE', 'МОШЕННИЧЕСТВО': 'SCAM',
                  'ОСТРОУМНЫЙ': 'WITTY',
                  'ГОЛУБЬ': 'DOVE', 'ПОРОХОВАЯ БОЧКА': 'TINDERBOX', 'РАВНЫЕ/РАВНО': 'EQUAL', 'ТОПОР': 'AXE',
                  'БРОСИТЬ/УЙТИ': 'TO QUIT', 'ВПЕЧАТЛИТЬ': 'TO IMPRESS', 'УВОЛЬНЕНИЕ': 'LAYOFF', 'ПОЛЬЩЕН': 'FLATTERED',
                  'НЕ ПОЙМИТЕ МЕНЯ НЕПРАВИЛЬНО': 'DO NOT GET ME WRONG', 'БОЕВЫЕ ИСКУССТВА': 'MARTIAL ARTS',
                  'МУЧАТЬ': 'TO TORTURE',
                  'ЗАХВАТИТЬ/УГНАТЬ':'TO HIJACK','АВТОМАГИСТРАЛЬ':'EXPRESSWAY','ЗАСОХНУТЬ':'TO WITHER','ХУЛИГАН':'HOODLUM',
                  'ТАПОЧКИ':'SLIPPERS','ВОСПРЯНУТЬ ДУХОМ':'TO PERK UP','НАПРАВЛЯТЬ/УПРАВЛЯТЬ/РУКОВОДИТЬ':'TO STEER',
                  'КРЕВЕТКА':'SHRIMP','ЯМА/КОТЛОВАН':'PIT','СТОГ СЕНА':'HAYSTACK','ИСПАРЕНИЯ':'FUMES','ХОРЕК':'WEASEL',
                  'ПРИМАНКА/ЛОВУШКА':'DECOY','ПАСТИСЬ':'TO GRAZE','ХРУПКИЙ':'FRAGILE','НЕТРОНУТЫЙ':'INTACT',
                  'ОПЕКА/РУКОВОДСТВО':'TUTELAGE','КРУШЕНИЕ/АВАРИЯ':'WRECK','РАЗ ПЛЮНУТЬ!':'PIECE OF CAKE!',
                  'СВИДЕТЕЛЬСТВО/ДОКАЗАТЕЛЬСТВО': 'EVIDENCE', 'ПАСТБИЩЕ': 'PASTURE', 'ПОД ПРЕКРЫТИЕМ': 'UNDERCOVER',
                  'ТРЮК': 'STUNT',
                  'НЕОТСЛЕЖИВАЕМЫЕ': 'UNTRACEABLE', 'ПАПОРОТНИК': 'FERN', 'ПОЛИЦЕЙСКИЙ УЧАСТОК': 'PRECINCT',
                  'ВОПИЮЩИЙ': 'BLATANT',
                  'ЭЛЕГАНТНЫЙ КОД': 'SLEEK CODE', 'ПРОИЗОДИТЕЛЬНЫЙ КОД': 'PERFORMANT CODE',
                  'НИЗКОЗАТРАТНЫЙ КОД': 'LOW-OVERHEAD CODE',
                  'ФУНКЦИИ ВЫСШЕГО ПОРЯДКА': 'HIGHER ORDER FUNCTIONS', 'ДОЛЯ/АКЦИИ': 'EQUITY',
                  'МАСТЕР НА ВСЕ РУКИ': 'JACK OF ALL TRADES', 'ПРОТОТИП': 'PROTOTYPE', 'ТМИН': 'CUMIN',
                  'НАМАЗЫВАТЬ/РАЗМАЗЫВАТЬ': 'TO SMEAR',
                  'БОКОВАЯ ЛИНИЯ': 'SIDELINE', 'ПРЕЖНИЙ/БЫВШИЙ': 'FORMER', 'НЕ СМОТРЯ НА....': 'DESPITE',
                  'ОСТОРОЖНЫЙ': 'WARY',
                  'ОБЯЗАННОСТИ': 'DUTIES', 'ОТБОР(ОТБОР МЯЧА)': 'TACKLE', 'ПРОДОЛЖАТЬ(ЧТО-ТО)': 'TO PROCEED',
                  'ЗАСУХА': 'DRAUGHT',
                  'ГРЯЗНЫЙ': 'MESSY', 'УВЕЛИЧИВАТЬ/ПОВЫШАТЬ': 'TO INCREASE', 'СКРОМНЫЙ': 'HUMBLE',
                  'ВПАДАТЬ В ЭКСТАЗ': 'TO SWOON',
                  'ИМПУЛЬС/ДВИЖУЩАЯ СИЛА': 'MOMENTUM',
                  'ПОДДЕРЖИВАТЬ(ФОРМУ)/СОХРАНЯТЬ': 'TO MAINTAIN',
                  'ВОЗРОЖДЕНИЕ': 'RENAISSANCE', 'НЕКОТОРЫЙ': 'CERTAIN', 'ИЗНУТРИ': 'INTERNALLY',
                  'ПОСТОЯННО/НЕПРЕРЫВНО': 'CONSTANTLY',
                  'ПРЕДПОЛОГАТЬ/ДОПУСКАТЬ(Я ДОПУСКАЮ,ЧТО..)': 'TO ASSUME', 'ПРЕИМУЩЕСТВО/ПРИВИЛЕГИЯ/ПОЛЬЗА': 'BENEFIT',
                  'БЕЗУСЛОВНО/ЯВНО': 'OBVIOUSLY', 'НАСТОЙЧИВАЯ ПРОСЬБА/ТРЕБОВАНИЕ': 'DEMAND',
                  'ЕДИНСТВО/СПЛОЧЕННОСТЬ': 'UNITY',
                  'СУЩЕСТВОВАТЬ/БЫТЬ': 'TO EXIST', 'БЛАГОТВОРНЫЙ/ПОЛЕЗНЫЙ': 'BENEFICIAL', 'ИЗВНЕ/СНАРУЖИ': 'EXTERNALLY',
                  'ЦЕЛЬ': 'AIM',
                  'ВЫПОЛНЯТЬ ПО ИНДИВИДУАЛЬНОМУ ЗАКАЗУ': 'TO CUSTOMIZE', 'НЕСОМНЕННО': 'NO DOUBT',
                  'РАЗГРОМ/ПОРАЖЕНИЕ(ФУТБОЛ)': 'ROUT',
                  'СЛУХ/ШОПОТ': 'WHISPER', 'ЗВЕЗДНЫЙ': 'STELLAR', 'ПРЕДОТВРАЩАТЬ/ПРЕДОХРАНЯТЬ': 'TO PREVENT',
                  'ЗАВЕРШИТЬ ЧТО-ТО (ЧЕМ-ЛИБО)': 'TO ROUND OFF SOMETHING WITH', 'ИТОГОВОЕ ЧИСЛО/ЕДИНИЦА СЧЕТА': 'TALLY',
                  'ЗДЕСЬ И ТАМ': 'HERE AND THERE', 'ДЕЛО': 'CAUSE', 'ВЫЗЫВАТЬ(КОГО-ТО)': 'TO CALL UP',
                  'ПРЕДВКУШАТЬ/ОЖИДАТЬ': 'TO ANTICIPATE',
                  'СРАЖАТЬСЯ С КЕМ-ЛИБО': 'TO TAKE SOMEBODY ON', 'ВСТРЕЧА(О КОМАНДАХ)/СТОЛКНОВЕНИЕ/ЛЯЗГ': 'CLASH',
                  'ОППОЗИЦИЯ/СОПРОТИВЛЕНИЕ': 'OPPOSITION',
                  'ИЗБЕГАТЬ': 'TO AVOID', 'ОЧАРОВЫВАТЬ/УВЛЕКАТЬ': 'TO FASCINATE', 'ПОСЫЛАТЬ/ОТПРАВЛЯТЬ': 'TO FORWARD',
                  'ПРОСМОТРЕТЬ/ПРОВЕРИТЬ': 'TO REVIEW', 'ВНИМАТЕЛЬНОЕ ЧТЕНИЕ': 'PERUSAL',
                  'ВСТРЕТИТЬСЯ/СТОЛКНУТЬСЯ': 'TO FACE',
                  'ПОЛОЖЕНИЕ (СРЕДИ ЧЕГО-ТО)': 'AMONG', 'АКТУАЛЬНАЯ ТЕМА': 'TOPIC', 'НАДО НАДЕЯТЬСЯ': 'HOPEFULLY',
                  'ПРОБЛЕМА': 'ISSUE',
                  'ПРОМЕЖУТОК ВРЕМЕНИ': 'SPELL', 'НЕДОСТАТОК(ПРИМ.ЧЕГО-ЛИБО(ВРЕМЕНИ))': 'LACK',
                  'ИЗГИБ(ДОРОГИ)/ПОВОРОТ': 'TWIST',
                  'ПОСЛЕДОВАТЕЛЬНО': 'CONSECUTIVELY',
                  'ЕМКОСТЬ': 'CAPACITY', 'ШИФРОВАТЬ': 'TO ENCRYPT', 'КОМПЬЮТЕРНОЕ ОБОРУДОВАНИЕ': 'HARDWARE',
                  'СВОЙСТВО': 'PROPERTY', 'ПАНЕЛЬ ЗАДАЧ': 'TASKBAR', 'ПРОВЕРЯТЬ': 'TO VERIFY', 'РЕКЛАМА/': 'ADVERTISING',
                  'ГОДОВОЙ ОТЧЕТ': 'ANNUAL REPORT', 'ДОЛГ(ДЕНЕЖНЫЙ)': 'DEBT', 'ВАЛЮТНЫЙ КУРС': 'EXCHANGE RATE',
                  'БЕСПЛАТНО/ДАРОМ': 'FREE OF CHARGE', 'ПОСРЕДНИК': 'INTERMEDIARY', 'АРЕНДА/ЛИЗИНГ': 'LEASING',
                  'КРЕСЛО': 'ARMCHAIR', 'КРЕСЛО-КАЧАЛКА': 'BENTWOOD ROCKER', 'КОВЕР': 'CARPET', 'ЛЮСТРА': 'CHANDELIER',
                  'ДЕТСКАЯ КРОВАТКА': 'COT', 'ЧЕРЕП': 'SKULL', 'УРАВНЕНИЕ': 'EQUATION', 'ПРЕДСКАЗЫВАТЬ': 'TO PREDICT',
                  'ИСПАРЯТЬСЯ': 'TO EVAPORATE', 'ВЫСТОЯТЬ': 'TO WITHSTAND', 'РЕДКО': 'RARELY', 'ВОСХОД': 'SUNRISE',
                  'СУМЕРКИ': 'TWILIGHT', 'КОНСУЛЬТАНТ': 'ADVISER', 'САМОУЧКА': 'AUTODIDACT',
                  'НЕ ОБИЖАЙСЯ': 'NO OFFENCE',
                  'ТЫ ЧТО,СПЯТИЛ?': 'ARE YOU NUTS?', 'ПОЧЕМУ ТЫ ТАК УВЕРЕН?': 'HOW CAN YOU BE SO SURE?',
                  'БЕРЕГОВАЯ ЛИНИЯ': 'COASTLINE', 'ПРОХЛАДНО': 'CHILLY', 'МОРОЗ': 'FROST', 'ИНТУИЦИЯ': 'HUNCH',
                  'ВЫРУЧКА': 'REVENUE',
                  'ПРИБЫВАТЬ': 'TO ARRIVE', 'ДЛИТЕЛЬНОСТЬ': 'DURATION', 'РАЗРЕШЕНИЕ': 'PERMIT', 'ССЫЛАТЬСЯ': 'TO REFER',
                  'ПЕЙЗАЖ': 'SCENERY', 'ЭФФЕКТИВНЫЙ': 'SPECTACULAR', 'ВЫКУПАТЬ': 'TO BUY BACK', 'РУКОВОДСТВО': 'MANUAL',
                  'ЗРЕНИЕ': 'VISION', 'ДОЛЖНЫМ ОБРАЗОМ': 'DULY', 'ВЕНА/ЖИЛА': 'VEIN', 'ДОСТОЙНЫЙ': 'DECENT',
                  'ДОСТАТОЧНО': 'PRETTY',
                  'СТАТИСТИКА': 'STATS', 'ОБЗОР/ПАНОРАМА': 'OVERVIEW', 'ДУМАТЬ': 'TO DEEM', 'НАНИМАТЬ': 'TO HIRE',
                  'ОТСТРАНЕНИЕ/БАН': 'SUSPENSION',
                  'СЛАБЫЙ': 'WEAKEST', 'У МЕНЯ НАСМОРК': 'I HAVE A RUNNY NOSE', 'ОБЪЕМ РАБОТЫ': 'WORKLOAD',
                  'ОТВЕТ': 'RESPOND',
                  'СОБИРАТЬ(ПРИМ. ДАННЫЕ)': 'TO COMPILE', 'ПРИВЛЕКАТЬ/ВОВЛЕКАТЬ/ВПУТЫВАТЬ': 'TO INVOLVE',
                  'ВЫЯВЛЯТЬСЯ/ВЫХОДИТЬ(ПРИМ.ПОБЕДИТЕЛЕМ': 'TO EMERGE',
                  'ВОЗОБНОВЛЯТЬ': 'TO RESUME', 'ЛЕЧЕНИЕ/': 'TREATMENT', 'СВЯЗКА(МЕДИЦИНСКОЕ)': 'LIGAMENT',
                  'ПОВРЕЖДАТЬ': 'TO DAMAGE',
                  'ПРЕДВИДЕТЬ/НАМЕЧАТЬ': 'TO ENVISAGE', 'СВОДКА НОВОСТЕЙ': 'ROUND-UP', 'КРУЖЕНИЕ/ВОДОВОРОТ': 'SWIRL',
                  'ОПРЯТНЫЙ/ЧИСТЫЙ': 'TIDY',
                  'ПОРАЗИТЕЛЬНЫЙ/ЗАХВАТЫВАЮЩИЙ': 'BREATHTAKING', 'ТЕКУЩИЙ/НЫНЕШНИЙ': 'CURRENT', 'СОБЫТИЕ': 'OCCASION',
                  'ПРИМЕРНЫЙ/ПРЕДПОЛАГАЕМЫЙ(ПРИМЕРНАЯ ЦЕНА(ПРИМ)': 'ESTIMATED', 'РАЗРЕШАТЬ/ПОЗВОЛЯТЬ': 'TO ALLOW',
                  'ПОДТВЕРЖДАТЬ': 'TO CONFIRM', 'БЛИСТАТЬ': 'TO SPARKLE', 'РАЗМИНКА': 'WARMING-UP',
                  'ГОЛ,СРАВНИВАЮЩИЙ СЧЕТ': 'EQUALIZER',
                  'ЗАВИСИМОСТЬ(АЛКОГОЛЬНАЯ)': 'ADDICTION', 'ОДЕЯЛО': 'BLANKET', 'ГОЛОВНАЯ БОЛЬ': 'HEADACHE',
                  'ВОНЬ': 'STINK',
                  'СИГАРЕТНЫЙ ОКУРОК': 'CIGARETTE BUTT', 'УДОВЛЕТВОРЕНИЕ': 'SATISFACTION', 'ЗАВИДОВАТЬ': 'TO ENVY',
                  'ПЕЧКА': 'STOVE',
                  'ПРИДУМЫВАТЬ/ИЗОБРЕТАТЬ': 'TO INVENT', 'ЧИХАТЬ': 'TO SNEEZE', 'ПЕРХОТЬ': 'DANDRUFF', 'ПРЫЩ': 'ACNE',
                  'ПЕПЕЛ': 'ASH', 'КАША': 'PORRIDGE', 'СПОКОЙНЫЙ': 'COMPOSED', 'ПЕРЕГОВОРЫ': 'NEGOTIATION',
                  'САРАЙ': 'BARN',
                  'ХРАПЕТЬ': 'TO SNORE', 'ПЕРЕЛОМ': 'FRACTURE', 'пНУТЬ/ТКНУТЬ': 'TO DIG', 'ХРУСТ': 'CRUNCH',
                  'СПЛЕТНЯ': 'GOSSIP',
                  'НАИВНЫЙ': 'NAIVE', 'РАЗДРАЖЕНИЕ': 'IRRITATION', 'ПАЛАТКА': 'TENT', 'АЛЬПИНИСТ': 'CLIMBER',
                  'СТРАСТЬ К ПУТЕШЕСТВИЯМ': 'WANDERLUST',
                  'ЩЕТИНА': 'STUBBLE', 'ШНУР': 'CORD', 'КНОПКА': 'BUTTON', 'КЛЯТВА': 'VOW', 'ОБЩИЙ': 'OVERALL',
                  'ОТСУТСТВИЕ': 'ABSENCE',
                  'СТРАСТЬ': 'PASSION', 'ПОДНИМАТЬ': 'TO LIFT', 'НАБЕГ/ОБЛАВА': 'RAID', 'ПОДДЕЛКА': 'COUNTERFEIT',
                  'ТУПИК/МЕРТВАЯ ТОЧКА': 'STALEMATE', 'ТЕЧЕНИЕ': 'FLOW', 'ПОКОЛЕНИЕ': 'GENERATION',
                  'ОГЛЯНИСЬ ВОКРУГ': 'TAKE A LOOK AROUND',
                  'ПЕРЕПИХОН': 'NOOKIE', 'ИЗМЕНИВШИЙСЯ': 'RE-ARRANGED', 'РАСШИРЕНИЕ': 'EXTENDED',
                  'ПЕРЕОПРЕДЕЛЕНИЕ': 'OVERRIDING', 'ПРОНИКНУТЬ ВНУТРЬ': 'TO PENETRATE', 'МОРСКАЯ БОЛЕЗНЬ': 'SEASICK',
                  'НЕЗАМУЖНЯЯ': 'UNWED',
                  'УВЕРЕННЫЙ': 'CONFIDENT', 'БЕДРО/БОК': 'HIP', 'ПОЛУЧАТЬ/ПРИОБРЕТАТЬ': 'TO RECEIVE',
                  'ПРИОБОДРЯТЬ/ПОДБАДРИВАТЬ': 'TO ENCOURAGE',
                  'РУГАТЬ': 'TO BERATE', 'ПРИЗНАВАТЬ': 'TO ADMIT', 'УМНЫЙ/ХИТРОУМНЫЙ': 'ASTUTE',
                  'НЕПРОЧИТАННОЕ': 'UNREAD', 'ПРИСТАЛЬНО/ПОДРОБНО': 'NARROWLY',
                  'ВОСХИЩАТЬСЯ': 'TO DELIGHT', 'АКТИВИРОВАЛ/ИНИЦИИРОВАЛ': 'TO TRIGGER',
                  'УДЕРЖАНИЕ(ПР.УДЕРЖАНИЕ МЯЧА)': 'RETENTION',
                  'ЗАДЕРЖАТЬСЯ': 'TO STICK AROUND', 'ВИНОВНИК ТОРЖЕСТВА': 'THE MAN OF THE HOUR',
                  'ПОСТЫДНЫЙ/ПОЗОРНЫЙ': 'SHAMEFUL',
                  'ИТОГ/РЕЗУЛЬТАТ': 'OUTCOME', 'ПОДХОДИТЬ/ВПИСЫВАТЬСЯ': 'TO FIT', 'МНОГОЧИСЛЕННЫЙ': 'MULTIPLE',
                  'ПРИБЫЛЬ': 'INCOME',
                  'ОТЗЫВАТЬ': 'TO RETRACT', 'КОНЕКРЕТНЫЙ': 'PARTICULAR', 'УБЕРИ ЭТО!': 'PUT IT AWAY!',
                  'ОТРЕКАТЬСЯ/ОТКАЗЫВАТЬСЯ': 'TO RENEGE',
                  'РАЗНООБРАЗИЕ/': 'VARIETY', 'ТЕРПЕТЬ': 'TO TOLERATE', 'ВЕЩЕСТВО/СУЩЕСТВО': 'SUBSTANCE',
                  'ЗЛОУПОТРЕБЛЕНИЕ/НАСИЛИЕ': 'ABUSE',
                  '...ОБОСРЕТСЯ/ОБЛАЖАЕТСЯ': 'CAKES ITS PANTS', 'СТОЛЕШНИЦА': 'COUNTERTOP',
                  'РАЗОБРАТЬСЯ': 'TO SORT IT OUT',
                  'МИГ': 'JIFFY', 'ХУЖЕ': 'WORSE', 'НАБЛЕВАТЬ НА...': 'TO PUKE ALL OVER',
                  'АБСУРДНО/НЕЛЕПО/ГЛУПО': 'ABSURD',
                  'МГНОВЕННО/': 'INSTANTLY', 'МЕСТО/ПЯТНО': 'SPOT', 'МУТНЫЙ/ПОДОЗРИТЕЛЬНЫЙ': 'SKETCHY',
                  'РАЙОН/': 'NEIGHBORHOOD',
                  'ЗАКАТАТЬ/ЗАСУЧИВАТЬ': 'TO ROLL UP', 'СТРОЧНЫЙ/НИЖНИЙ РЕГИСТР': 'LOWERCASE', 'АВТОСТРАДА': 'FREEWAY',
                  'ТУСОВАТЬСЯ': 'TO HANG OUT', 'БУХГАЛТЕР': 'ACCOUNTANT', 'МУДАК': 'PRICK', 'СТИЛЬ/ТАЛАНТ': 'FLAIR',
                  'УТВЕРЖДЕНИЕ/ОДОБРЕНИЕ/СОГЛАСИЕ': 'APPROVAL', 'НЕУМЕСТНО': 'IRRELEVANT',
                  'ЗЭК/УРКА': 'CONVICTED FELON',
                  'ТРАТИТЬ/РАССТРАЧИВАТЬ': 'TO WASTE', 'НАКЛОНИТЬСЯ/НАГНУТЬСЯ': 'TO BEND OVER', 'ИСКРЕННЕ': 'GENUINELY',
                  'ОТМЕНИТЬ': 'TO WITHDRAW', 'ГОЛОГРАФИЧЕСКИЙ': 'HOLOGRAPHIC', 'ТЕЛЕКОНФЕРЕНЦИЯ': 'TELECONFERENCING',
                  'ГОЛОГРАММА': 'HOLOGRAM', 'ЖЕСТ': 'GESTURE', 'ВЫСОКОСКОРОСТНОЙ ИНТЕРНЕТ': 'BROADBAND',
                  'СЕЛЬСКИЙ': 'RURAL', 'ОБЯЗАТЕЛЬНЫЙ(ДЛЯ ВСЕХ)/ПРИНУДИТЕЛЬНЫЙ': 'COMPULSORY',
                  'ИЗЛЕЧИТЬ': 'TO CURE', 'БЫДЛО': 'SCUM', 'СМЫВАТЬ': 'TO WASH AWAY', 'НАМЕКАТЬ': 'TO HINT',
                  'УКАЧИВАНИЕ': 'MOTION SICKNESS',
                  'БРОСАТЬ(КОГО-ТО)': 'TO DUMP', 'НЕЗРЕЛЫЙ/ЮНЫЙ': 'IMMATURE',
                  'ПОГРЯЗНУТЬ В ЖАЛОСТИ К СЕБЕ': 'WALLOWING IN SELF-PITY', 'ЧЕРТЫ ЛИЦА/ОСОБЕННОСТИ': 'FEATURES',
                  'ОТКАЗЫВАТЬ': 'TO TURN DOWN', 'ДОМАШНИЙ': 'DOMESTIC', 'НЕПРИВЕТЛИВЫЙ/ЗЛОБНЫЙ': 'MEAN',
                  'НАПАДАТЬ НА ЛОЖНЫЙСЛЕД': 'TO BARK UP THE WRONG TREE', 'СОБЛАЗНЯТЬ': 'TO ENTICE', 'ПЛОТЬ': 'FLESH',
                  'СТОЯК': 'BONER', 'РУКОПОЖАТИЕ': 'SHOOK HANDS', 'ПОЧТАЛЬОН': 'POSTMAN', 'ВЕЖЛИВЫЙ': 'POLITE',
                  'РАСПЛАТИТЬСЯ': 'TO PONY UP', 'ДАВАЙТЕ НАЧНЕМ': 'LETS GET STARTED', 'ПРОЖИВАТЬ': 'TO RESIDE',
                  'АРЕНДАТОР': 'TENANT', 'ДОЛИ(В ПРОЦЕНТНОМ ЭКВ)': 'PERCENTAGES', 'РАСПРЕДЕЛЯТЬ': 'TO APPORTION',
                  'КРАЙНЕ/СОВЕРШЕННО': 'UTTERLY', 'БЕСПОЛЕЗНЫЙ': 'USELESS',
                  'НЕЛОВКИЙ(ПР.РАЗГОВОР)': 'AWKWARD',
                  'НАПОРИСТЫЙ': 'ASSERTIVE', 'ЗАИМСТВОВАТЬ': 'TO BORROW', 'ПЕРЕОПРЕДЕЛИТЬ': 'TO REDEFINE',
                  'ВЗЛАМЫВАТЬ(КОД)': 'TO TAKE APART',
                  'ДОСТУП': 'ACCESS', 'МОНЕТА В ДЕСЯТЬ ЦЕНТОВ': 'DIME', 'ЯДРО': 'NUCLEUS',
                  'ВЫПИСЫВАТЬ(ПР.ЧЕК)/ОБЖИМАТЬСЯ/': 'TO MAKE OUT',
                  'ДОСТИЖЕНИЕ/УСПЕХ': 'ACCOMPLISHMENT', 'ОЦЕНИВАТЬ': 'TO MEASURE', 'НАНОТЕХНОЛОГИИ': 'NANOTECH',
                  'ПРОДВИНУТЫЙ': 'SOPHISTICATED', 'ГОЛОД': 'HUNGER', 'УСТАРЕВШИЙ/ВОТСТАВКЕ': 'RETIRED',
                  'ХУДШИЙ': 'INFERIOR',
                  'ПОКУПКА': 'PURCHASE', 'ЗАСОВЫВАТЬ': 'TO TUCK', 'ИСТРАТИТЬ/ПОТРАТИТЬ ПОЛНОСТЬЮ': 'TO MAX OUT',
                  'СКАЗКА': 'FAIRY TALE', 'ПЕЩЕРА': 'CAVE', 'УЖАС/ЗВЕРСТВО': 'ATROCITY',
                  'ПОДОЖДАТЬ/СДЕРЖИВАТЬСЯ': 'TO HOLD OFF',
                  'ОПРЕДЕЛЯТЬ': 'TO DEFINE', 'ПОЛОВОЙ АКТ': 'INTERCOURSE', 'НАПОМИНАТЬ': 'TO REMIND',
                  'ТОВАРНЫЙ ЗНАК': 'TRADEMARK',
                  'РВАНУТЬ/ПОЕХАТЬ/УХОДИТЬ': 'TO HEAD OUT', 'ПОШЛО НЕ ТАК': 'WENT SIDEWAYS',
                  'ЗАКРЫТЬСЯ': 'TO SHUT DOWN',
                  'РЫНОЧНАЯ КАПИТАЛИЗАЦИЯ': 'MARKET CUP', 'МАЛОЗНАКОМЫЙ': 'UNFAMILIAR', 'РОВЕСТНИК/КОЛЛЕГА': 'PEER',
                  'СОСТОЯТЬ ИЗ...': 'TO CONSIST OF', 'ТОЛЬКО/ИСКЛЮЧИТЕЛЬНО': 'SOLELY', 'ПЛАТЕЖНАЯ ВЕДОМОСТЬ': 'PAYROLL',
                  'СЕРДИТЫЙ': 'IRATE', 'ПРОСТО-НАПРОСТО': 'MERELY', 'ВОЗРАЖАТЬ': 'TO MIND', '...А ИМЕННО...': 'TO WIT',
                  'НЕЛЕГАЛ': 'ILLEGAL', 'ИРОНИЯ': 'IRONY', 'УРОЖАЙ/ЗЕРНО': 'CROP', 'МЕШАТЬ': 'TO INTERFERE',
                  'ФЕРМА': 'FARMLAND',
                  'ПЯЛИТЬСЯ НА...': 'TO STARE AT', 'ОСНОВЫВАТЬ/СОЗДАВАТЬ': 'TO FOUND',
                  'СЕМЯ/СЕМЕЧКА/ЗЕРНЫШКО': 'SEED',
                  'НА ВЕРШИНЕ/ПОВЕРХ': 'ATOP', 'КУНЖУТ': 'SESAME', 'ГРУППА/ТОЛПА/НЕСКОЛЬКО': 'BUNCH',
                  'ЦИФРОВЫЕ РЕШЕНИЯ': 'DIGITAL SOLUTIONS',
                  'ИНТЕГРИРОВАННЫЕ': 'INTEGRATING', 'БАЗА ДАННЫХ': 'DATA SPACE', 'УНИКАЛЬНЫЙ': 'UNIQUE',
                  'КРОСС-ПЛАТФОРМЕННЫЙ': 'CROSS PLATFORM',
                  'КАК РАЗ ВОВРЕМЯ': 'RIGHT ON TIME', 'КОРЕШ': 'HOMEBOY', 'ПАДАЙ!': 'POP A SQUAT!',
                  'СПРАВИТСЯ С...': 'GET THROUGH',
                  'СОЗДАТЬ/УСТАНОВИТЬ': 'TO ESTABLISH', 'УЧИТЫВАТЬ/ВКЛЮЧАТЬ': 'TO INCORPORATE',
                  'ПОВЕСИТЬ ТРУБКУ': 'TO HUNG UP',
                  'ФУ': 'YUCK', 'КОДИРОВАТЬ': 'TO ENCODE',
                  'МЕТАДАННЫЕ': 'META-DATA',
                  'БЛОК-СХЕМА': 'FLOW DIAGRAM', 'БАЗА ФИЛЬТРОВ': 'FILTER BANK', 'КИВАТЬ': 'TO NOD', 'КИШКИ': 'GUTS',
                  'МУСОРКА/МУСОР': 'TRASH',
                  'ВРОДЕ': 'SORT OF', 'РЕЗЮМИРОВАТЬ/ПОДВОДИТЬ ИТОГИ': 'TO RECAP', 'УВАЖАТЬ': 'TO HONOR',
                  'ИЗЛОЖИТЬ/ВЫЛОЖИТЬ': 'TO LAY OUT',
                  'В ОБЩИХ ЧЕРТАХ': 'IN BROAD STOCKES', 'НЕ СПЕШИ/ДЕРЖИ СЕБЯ В РУКАХ': 'PACE YOURSELF', 'РАБ': 'SLAVE',
                  'МАФИОЗИ': 'MOBSTER', 'САМЫЙ КРУТОЙ': 'ILLEST', 'РЕЗКИЙ/ВНЕЗАПНЫЙ': 'ABRUPT',
                  'оТЧЕТЛИВО': 'DISTINCTLY',
                  'ПОМОШНИК': 'ASSOCIATE', 'ПОДГОТОВИТЬ/НАБРОСАТЬ/СПРОЕКТИРОВАТЬ': 'TO DRAFT UP', 'ПРАВЛЕНИЕ': 'BOARD',
                  'НАЗНАЧАТЬ/': 'TO APPOINT', 'ПРИЯТЕЛЬ/ДРУЖИЩЕ': 'HOMEY', 'КЛИЗМА': 'ENEMA',
                  'ПЕРЕСМОТРЕН/ИСПРАВЛЕН': 'AMENDED', 'ПРОСНУТЬСЯ': 'TO AWAKE', 'ПРЕДУПРЕЖДЕН': 'FOREWARNED',
                  'ВСЕ ПРОЙДЕТ': 'LITTLE HAIR OF THE DOG',
                  'ПЕРЕЖИТЬ': 'TO RELIVE', 'ЗАВЕРШАТЬ/ВЫПОЛНИТЬ': 'TO COMPLETE', 'В ШУТКУ': 'HALF-JOKINGLY',
                  'НАДЗОР': 'OVERSIGHT', 'ОБЛЕГЧЕНИЕ': 'RELIEF', 'Я РАД,ЧТО ТЫ ТУТ': 'I AM GLAD YOU ARE AROUND',
                  'НА ЗАДНЕМ ДВОРЕ': 'OUT BACK', 'РАССТЕГНУТЬ': 'TO UNBUTTON', 'МАРКЕТОЛОГ': 'MARKETER',
                  'ЖИЛЕТКА': 'VEST', 'СОГЛАСИЕ': 'CONSENT', 'ОБЫЧНЫЙ/СТАНДАРТНЫЙ': 'CONVENTIONAL', 'МЕНЬШЕ': 'FEWER',
                  'ПЛАН/УЧЕБНЫЙ ПЛАН': 'SYLLABUS', 'УПОРСТВО/НАСТОЙЧИВОСТЬ': 'PERSISTENCE',
                  'СУЩЕСТВЕННЫЙ(ПР...РОСТ)': 'SUBSTANTIAL',
                  'ПРЕДПРИЯТИЕ': 'ENTERPRISE', 'НЕОСЯЗАЕМО': 'INTANGIBLE',
                  'БРОСИТЬ ЧТО-ТО/УЙТИ ИЗ..': 'TO DROP OUT OF SOMETHING', 'КОЛЫБЕЛЬ': 'CRADLE', 'ЖЕСТОКИЙ': 'CRUEL',
                  'РАЗДУВАТЬСЯ': 'BLOAT', 'ИЗВЕРГАТЬ': 'TO SPEW', 'ПРЕДПРИНИМАТЕЛЬ': 'ENTREPRENEUR',
                  'БУНТАРЬ': 'ICONOCLAST',
                  'ПОВТОРНО ИСПОЛЬЗОВАТЬ': 'TO REUSE', 'СПЕКТР/ДИАПАЗОН': 'SPECTRUM',
                  'ПРОГРАММА/ПРИЛОЖЕНИЕ': 'APPLICATION', 'ВОЗНИКАТЬ/ПОЯВЛЯТЬСЯ': 'TO BLOW UP', 'СОВПАДЕНИЕ': 'MATCH',
                  'НАРУШАТЬ(ЗАКОН)': 'TO INFRINGE', 'ПРОИЗВОДИТЬ/СНАБЖАТЬ': 'TO DELIVER', 'НАРОД': 'HUMANITY',
                  'ТЕХНИЧЕСКИ': 'TECHNICALLY', 'УПАКОВЫВАТЬ': 'TO PACKAGE', 'ТЕХНОЛОГИЯ': 'TECH',
                  'ИНОВАЦИОННЫЙ': 'INNOVATIVE',
                  'ТРАНСФОРМИРОВАТЬ': 'TO TRANSFORM', 'ОРИЕНТИРОВАТЬСЯ': 'TO ORIENT',
                  'ТВЕРДО(ПРИМ.Я ТВЕРДО УВЕРЕН..)': 'FIRMLY',
                  'ДОСТИГАТЬ': 'TO ACHIEVE', 'ВЕЛИЧИЕ': 'GREATNESS', 'НЕПОНЯТНЫЙ': 'INCOMPREHENSIBLE',
                  'ОТСОСИ САМ У СЕБЯ': 'TO BLOW YOURSELF', 'АДЕКВАТНЫЙ': 'ADEQUATE', 'ПАРКОВАТЬСЯ': 'TO PARK',
                  'ВЛАЖНОСТЬ ВОЗДУХА': 'HUMIDITY',
                  'ПОДОЗРИТЕЛЬНЫЙ': 'SUSPICIOUS',
                  'БОЛЬШИНСТВО': 'MAJORITY', 'СУТЕНЕР': 'PIMP', 'ВМЕСТО/ВЗАМЕН': 'INSTEAD',
                  'ДЕНЕЖНОЕ ВОЗНАГРАЖДЕНИЕ': 'REWARD',
                  'СЕУВЕРИЕ': 'SUPERSTITION', 'ЗАДОМ НАПЕРЕД': 'BACKWARDS', 'ОТРИЦАТЕЛЬНЫЙ ОТВЕТ': 'NEGATIVE',
                  'ПЕПЕЛЬНИЦА': 'ASHTRAY',
                  'ОТВРАТИТЕЛЬНЫЙ/ОМЕРЗИТЕЛЬНЫЙ': 'DISGUSTING', 'ВОДОЕМ/БАССЕЙН': 'TANK', 'УБИЙСТВО': 'HOMICIDE',
                  'УСТАНАВЛИВАТЬ/ОСНОВЫВАТЬ': 'TO ESTABLISH', 'НОЧНОЙ ГРАБИТЕЛЬ': 'BURGLAR',
                  'ПРИЗНАВАТЬСЯ/СОЗНАВАТЬСЯ': 'TO CONFESS',
                  'ХОЛМИК/БУГОРОК': 'KNOLL', 'УРОЖАЙ': 'YIELD', 'УСТУПАТЬ(КОМУ-ТО)/ПРОГИБАТЬСЯ': 'TO YIELD',
                  'МОРСКАЯ СВИНКА': 'PORPOISE',
                  'СЪЕДОБНЫЙ МОРСКОЙ МАЛЛЮСК': 'CLAM', 'РАЗРЕШЕНИЕ/ПОЗВОЛЕНИЕ': 'PERMISSION', 'НА БОРТУ': 'ABOARD',
                  'ЛЕГКАЯ НАЖИВА': 'GRAVY', 'ОТЛОЖИТЬ/ОТСРОЧИТЬ': 'TO POSTPONE', 'САМОЕ ГЛАВНОЕ': 'ESSENTIAL',
                  'ИМЕТЬ ОТНОШЕНИЕ(К ЧЕМУ-ТО)': 'TO RELATE', 'ВСКРЫТИЕ ТРУПА': 'AUTOPSY', 'РЕДКИЙ': 'RARE',
                  'УЮТНЫЙ': 'COZY',
                  'МЕСТЬ/': 'REVENGE', 'ЧУВСТВИТЕЛЬНЫЙ/НЕЖНЫЙ': 'SENSITIVE', 'ПЕРЕМАТЫВАТЬ': 'TO REWIND',
                  'СЛАБАК': 'QUITTER',
                  'ПОХИЩЕНИЕ': 'ABDUCTION', 'ЗАШНУРОВАТЬ': 'TO LACE', 'ВОССТАНОВЛЕНИЕ СИЛ': 'REFRESHMENT',
                  'ЗАНУДА': 'WIMP',
                  'ВЕРНО ПОДМЕЧЕНО!': 'DULY NOTED!',
                  'ЭПИЛЯЦИЯ ГРУДИ': 'CHEST-WAXING', 'КУПАНИЕ ГОЛЫШОМ': 'SKINNY-DIPPING',
                  'ЗАПИШИТЕ МЕНЯ!': 'SIGN ME UP!',
                  'ЛОВУШКА': 'TRAPP', 'НАМЕКАТЬ/ПОДРАЗУМЕВАТЬ': 'TO IMPLUY', 'ЖЕНЩИНА': 'FEMME', 'ЛЮДОЕД': 'MAN-EATER',
                  'ХАЛАТ': 'ROBE', 'ГОЛОДАЮЩИЙ': 'STARVING', 'ТАСКАТЬ': 'TO DRUGG', 'ПОТРЯСАЮЩИЙ': 'FABULOUS',
                  'ЖАДНЫЙ': 'GREEDY',
                  'ТУПОРЫЛЫЙ': 'BONEHEAD', 'СОЧНЫЙ': 'LUSCIOUS', 'ОСКОРБИТЕЛЬНЫЙ': 'RIDICULOUS', 'ГАВКАТЬ': 'TO BARK',
                  'БОЛЬ В СЕРДЦЕ': 'HEARTACHE', 'БРОСИТЬ КОГО-ТО': 'TO ABANDON SOMEBODY', 'ОБЯЗАТЕЛЬСТВО': 'COMMITMENT',
                  'СТОНАТЬ': 'TO MOAN', 'ХВАТАТЬ': 'TO GRAB', 'ЗАПРЕЩЕННЫЙ': 'TABOO', 'ПРОВАЛИВАЙ!(СЛЭНГ)': 'BUZZ OFF!',
                  'УМОЛЯТЬ/ПРОСИТЬ': 'TO BEG', 'СУДОРГА': 'CRAMP', 'ОТЧАЯНЫЙ': 'DESPERATE', 'НАПРЯЖЕННЫЙ': 'STIFF',
                  'ПОРТИТЬ/БАЛОВАТЬ': 'TO SPOIL', 'БОЖЕСТВЕННЫЙ': 'DIVINE', 'ЧУДЕСНЫЙ': 'MARVELOUS',
                  'НА МОЕЙ СТОРОНЕ': 'BY MY SIDE',
                  'ПОДКИНУТЬ/ДАВАТЬ НА ЧАЙ': 'TO TIP', 'ОСТАВАТЬСЯ В КАКОМ-ТО СОСТОЯНИИ/СОХРАНЯТЬСЯ': 'TO REMAIN',
                  'ЯРКИЙ': 'VIVIT', 'СВЕРЛО': 'DRILL', 'ИМЕТЬ ДЕЛО/ДОГОВАРИВАТЬСЯ': 'TO DEAL(DEALT)',
                  'СТРЕЛА/УКАЗАТЕЛЬ': 'ARROW',
                  'ВЫГОРАТЬ(СЛЭНГ)': 'TO FADE', 'КОЛЕНИ (СИДЯЩЕГО ЧЕЛОВЕКА)': 'LAP',
                  'ПОВТОРЯЮЩИЙСЯ/ЧЕРЕДУЮЩИЙСЯ': 'ROLLING',
                  'КОЛОТЬ(НОЖОМ)/ТЫКАТЬ': 'TO STAB', 'КАСАТКА': 'ORKA', 'КИТ': 'WHALE', 'ПАКЕТИК МАРИХУАНЫ': 'LID',
                  'ОБЩАГА': 'DORM',
                  'КОНТРАБАНДИСТ': 'SMUGGLER', 'МАСКИРОВКА': 'DISGUISE', 'НАСЛАЖДЕНИЕ': 'TREAT', 'ФУРГОН': 'VAN',
                  'ТЕРЕПЕТЬ ЕГО НЕ МОГУ': 'I CAN NOT STAND HIM', 'НАРУШАТЬ': 'TO DISRUPT',
                  'ИЕРАРХИИ': 'HIERARARCHIES',
                  'ДОБРОВОЛЬНЫЙ': 'WILLING',
                  'СЛЕДОВАТЬ(ПР.ЗА СВОЕЙ МЕЧТОЙ)': 'TO PURSUE', 'ПОВТОРНО ПОСТУПАТЬ (В КОЛЛЕДЖ)': 'RE-ENROLL',
                  'ПРИГОВОРЕННЫЙ К ПОЖИЗНЕННОМУ ЗАКЛЮЧЕНИЮ': 'LIFER', 'ЗАКОННЫЙ': 'VESTED', 'АКЦИИ': 'STOCK',
                  'ДВОРНИК': 'WIPER', 'ПОДГУЗНИК': 'DIAPER',
                  'НЕВЕЖЕСТВО': 'IGNORANCE',
                  'БЕЗРАБОТНЫЙ': 'UNEMPLOYED',
                  'ДОЛЖНИК': 'DEBTOR', 'СОМНИТЕЛЬНОЕ': 'DUBIOUS',
                  'ПОНИЖЕННЫЙ': 'DOWNGRADED',
                  'БЕЗ ПОТЕРЬ': 'LOSSLESS', 'КАК-ТО': 'SOMEHOW',
                  'ВЫУЧИТЬ НАИЗУСТЬ': 'TO MEMORIZE',
                  'ШЕСТНАДЦАТЕРИЧНЫЙ': 'HEXADECIMAL', 'ОТ ИМЕНИ...': 'BEHALF OF', 'ВОЗВЫШАТЬ': 'TO ELEVATE',
                  'ОБЪЯВЛЕНИЕ': 'AD', 'ПО КРАЙНЕЙ МЕРЕ/ ВО ВСЯКОМ СЛУЧАЕ': 'AT LEAST', 'ПЫЛЬ': 'DUST',
                  'В ПОСЛЕДНЕЕ ВРЕМЯ': 'LATELY',
                  'ВЗАИМОДЕЙСТВОВАТЬ/ОБЩАТЬСЯ': 'TO INTERACT', 'НЕПРИЕМЛЕМЫЙ/НЕСОСТОЯТЕЛЬНЫЙ': 'UNTENABLE',
                  'ОСВЕДОМЛЕННЫЙ/В КУРСЕ/ЗНАЮЩИЙ': 'AWARE', 'КЛЮКВА': 'CRANBERRY', 'ПЛЕСЕНЬ': 'FUNGUS',
                  'ПОДВЕРГАТЬ РИСКУ': 'TO JEOPARDIZE',
                  'НАДЛЕЖАЩЕЕ ФИНАНСИРОВАНИЕ': 'PROPER FUNDING', 'ПОЛУЧИЛОС/СРАБОТАЛО': 'WORKED OUT',
                  'УМНОЖАТЬ': 'TO MULTIPLY', 'ПОПРОБУЙ ЕЩЕ РАЗ!': 'GIVE IT ANOTHER CUT!', 'ТЕХНИЧЕСКИЙ ДИРЕКТОР': 'CTO',
                  'ДЕЛИГИРОВАТЬ': 'TO DELEGATE', 'ИСПУГАТЬСЯ': 'TO GET SPOOKED', 'ПРИОБРЕТЕНИЕ/ЗАКУПКА': 'ACQUISITION',
                  'НАЧАЛЬНИК/ВЫШЕСТОЯЩИЙ': 'SUPERIOR', 'ПЕРЕЧЕНЬ УСЛОВИЙ': 'TERM SHEET', 'ПРОНИЦАТЕЛЬНЫЙ/': 'SHREWDEST',
                  'БЕГЕМОТ': 'HIPPO', 'БРОДИТЬ/БЛУЖДАТЬ': 'TO WANDER', 'ВИНТОВКА/РУЖЬЕ': 'RIFLE',
                  'ИСПУГАТЬ': 'TO STARTLE',
                  'ПРЕЖДЕ ЧЕМ/ПРЕДВАРИТЕЛЬНО': 'PRIOR', 'ПРЕДСТОЯЩИЙ/БУДУЩЕЙ/НАСТУПАЮЩИЙ': 'UPCOMING',
                  'УЖАСНЫЙ': 'HORRIBLE',
                  'БЛИЗОРУКИЙ': 'NEAR-SIGHTED', 'ОТРЫЖКА': 'BELCH', 'СМУЩАТЬ': 'TO EMBARRASS',
                  'ОТВЕРНИСЬ!': 'AVERT YOUR EYES!',
                  'БЕСПОКОИТЬСЯ/ВОЛНОВАТЬСЯ': 'TO BOTHER', 'ФИАСКО': 'DEBACLE', 'СРАВНИВАТЬ': 'TO COMPARE',
                  'КАК БУД-ТО ЭТО ТАК ВАЖНО': 'LIKE IT MATTERS', 'ШВЫ': 'STITCHES', 'ССАТЬ': 'TO GET PEED',
                  'КУЧА ВРЕМЕНИ': 'HELL OF A TIME',
                  'ФИЛЕ': 'FILET', 'ПОДТИРАТЬ/ВЫТИРАТЬ': 'TO WIPE', 'ХРАМ': 'TEMPLE', 'БРИГАДА': 'CREW',
                  'ПОДДЕРЖИВАТЬ(КАКОЕ-ТО СОСТОЯНИЕ)': 'TO SUSTAIN',
                  'СОВЕТЫ': 'POINTERS', 'КОРМУШКА': 'FEEDER', 'РАЙОН/ОКРЕСТНОСТИ': 'VICINITY',
                  'ВЕРОЯТНОСТЬ': 'LIKELIHOOD',
                  'ПРИЧЕСКА': 'MULLET', 'ТАЙНИК': 'STASH', 'ПОСТОРОННИМ ВХОД ЗАПРЕЩЕН': 'NO TRESPASSING',
                  'МЕРЗКИЙ/НЕПРИЯТНЫЙ': 'NASTY',
                  'ПОДСКАЗКИ/УЛИКИ': 'CLUES', 'ЖЕРТВА': 'VICTIM', 'ЯЗЫК': 'TONGUE', 'КОНКУРС': 'CONTEST',
                  'НАБРАСЫВАТЬСЯ/СРЫВАТЬСЯ': 'TO LASH OUT',
                  'НЕФТЯНАЯ ВЫШКА': 'OIL RIG', 'ГРЫЗУН': 'RODENT', 'КИНУТЬ/БРОСИТЬ': 'TO BAIL ON',
                  'УДОСТОИТЬ': 'TO DIGNIFY',
                  'СПЛЕТНЯ/СЛУХ': 'RUMOR', 'ГУДЕТЬ/ЖУЖЖАТЬ': 'TO ABUZZ', 'СВОДИТ/СУДОРГА/СПАЗМ': 'TO CRAMP UP',
                  'ОТБОРОЧНЫЙ ТУР': 'PRELIMS',
                  'ДРОЧИТЬ': 'TO JERK OFF', 'ТЕОРЕТИЧЕСКИ/ГИПОТЕТИЧЕСКИ': 'HYPOTHETICALLY',
                  'ДОПОЛНИТЕЛЬНЫЙ': 'COMPLEMENTARY',
                  'ОКРУЖНОСТЬ': 'GIRTH', 'НАДЕЖНЫЙ/ДОСТОВЕРНЫЙ': 'RELIABLE', 'МЕТРИЧЕСКИЙ': 'METRIC',
                  'ВЫНОСЛИВОСТЬ': 'STAMINA',
                  'ПОДАВЛЕН/РАССТРОЕН': 'BUMMED OUT', 'ПРОРЫВ': 'BREAKTHROUGH', 'ОБЛАЧНАЯ(ТЕХОЛОГИЯ)': 'CLOUD-BASED',
                  'БУКЛЕТЫ': 'PAMPHLETS', 'БОТАНИК': 'NERD', 'ЭЛЕКТРОПРОВОДКА': 'WIRING', 'ОДИНАКОВО/СХОЖИ': 'ALIKE',
                  'ВЗБОДРИСЬ!/ВЫШЕ НОС!': 'CHEER UP!',
                  'БЛЕФ': 'BLUFF', 'КОЖЗАМЕНИТЕЛЬ': 'PLEATHER', 'ШЛАНГ': 'HOSE',
                  'РАДИ ВСЕГО СВЯТОГО!': 'FOR CHRISSAKES!',
                  'БЛИЖЕ К ДЕЛУ!': 'GET TO THE POINT!', 'ВОЗРОЖДАТЬ/РАЗЖЕЧЬ': 'TO REKINDLE', 'ЖАЛКИЙ': 'PATHETIC',
                  'ИЗБАВЬТЕСЬ ОТ НЕГО!': 'CUT HIM LOOSE!', 'НАЛИВАТЬ': 'TO POUR', 'БИНОКЛЬ': 'BINOCULAR',
                  'МЕБЕЛЬ': 'FURNITURE',
                  'БЕЗ ПОНЯТИЯ!': 'BEATS ME!', 'СЛЕЖКА/ЗАСАДА': 'STAKEOUT', 'ДВУХЭТАЖНЫЙ': 'TWO-STORY',
                  'ПОХОТЛИВЫЙ/ОЗАБОЧЕННЫЙ': 'HORNY',
                  'СХВАТКИ/СОКРАЩЕНИЯ': 'CONTRACTIONS', 'НЕ ПРИПОМИНАЮ!': 'DOES NOT RING A BELL!', 'ТАЗ': 'PELVIS',
                  'УКРОП': 'DILL',
                  'ВЫКУСИ!': 'BITE ME!', 'ВЫПУСКАТЬ/ОСВОБОЖДАТЬ': 'TO RELEASE', 'ГРУБЫЙ': 'RUDE', 'ЖЕЛЕ/СЛИЗЬ': 'GOO',
                  'ЖЕНИХ': 'GROOM', 'ПОДРУЖКА НЕВЕСТЫ': 'BRIDESMAID', 'РЕШИТЕЛЬНЫЙ ШАГ': 'PLUNGE', 'СМОКИНГ': 'TUXEDO',
                  'ПОДЕЛИТЬ/РАЗДЕЛИТЬ/РАСПРЕДЕЛИТЬ': 'TO DEVIDE UP', 'СБЕРЕЖЕНИЯ': 'SAVINGS',
                  'ВЗАИМНЫЙ/СОВМЕСТНЫЙ': 'MUTUAL',
                  'ПРОХОД': 'AISLE', 'ШЛЮХА': 'HOOKER', 'ПЕДИК': 'FAG', 'НЕУТОЛИМАЯ': 'UNQUENCHABLE',
                  'КОЛОССАЛЬНЫЙ': 'COLOSSAL',
                  'ВЫМЫШЛЕННЫЙ': 'FICTIONAL', 'ИГРАЛЬНЫЕ КОСТИ': 'DICE', 'МУЛЬТИПЛИКАТОР/КАРИКАТУРИСТ': 'CARTOONIST',
                  'ФОН': 'BACKGROUND', 'ЗАМЕЧАНИЕ/ПРИМЕЧАНИЕ': 'REMARK', 'ВИНА': 'GUILT',
                  'ГНЕВ': 'RAGE', 'НОСОРОГ': 'RHINO', 'ПРОСЛУШКА': 'WIRETAP', 'УМСТВЕННО ОТСТАЛЫЙ': 'RETARDED',
                  'КУШЕТКА/ДИВАН': 'COUCH', 'ОБИЖАТЬСЯ/ДУТЬСЯ': 'TO SULK', 'ПСИХИАТР': 'SHRINK',
                  'НЕДОСТАТОК/СЛАБОСТЬ': 'WEAKNESS',
                  'ВЗВОЛНОВАН': 'FLUSTERED', 'СОСРЕДОТОЧЕННЫЙ': 'CENTERED', 'ХЛЕБАЛО': 'PIE-HOLE',
                  'ВМЕШАТЬСЯ': 'TO INTERJECT',
                  'УСВОИТЬ': 'TO ABSORB', 'ДО ЧЕРТИКОВ': 'BEJESUS', 'ОФИЦИАНТ': 'WAITRESS', 'БОЛЕЗНЬ': 'DISEASE',
                  'ПОЭЗИЯ': 'POETRY',
                  'ПРИТВОРЯТЬСЯ/': 'TO DISSEMBLE', 'ЧУДЕСА': 'MIRACLES', 'СПАСЕНИЕ': 'RESCUE', 'ШЕВЕЛИТЬ': 'TO WIGGLE',
                  'ВМЯТИНА': 'DING', 'ТЕРПЕНИЕ': 'TEMPER', 'НОЗДРЯ': 'NOSTRIL', 'ТАЙНО ПОЖЕНИТЬСЯ': 'TO ELOPE',
                  'РЕЕСТР': 'DOCKET',
                  'ПОЛЗАТЬ': 'TO CRAWL', 'ПОТРЕПАННЫЙ': 'BANGED UP', 'ПОДПРОГРАММА': 'SUBROUTINE', 'ВЫДЕРЖКА': 'POISE',
                  'ЗАВСИЛО': 'IT IS FROZEN', 'ДОЛЖЕН/ОБЯЗАН(ИЗВИНИТЬСЯ ПР.)': 'OWE', 'РЕЗЕРВНОЕ КОПИРОВАНИЕ': 'BACKUP',
                  'ЛЮБОПЫТНЫЙ/ЛЮБОЗНАТЕЛЬНЫЙ': 'CURIOUS', 'ИЗМЕНИТЬ КОРЕННЫМ ОБРАЗОМ': 'TO REVOLUTIONIZE',
                  'АГРЕГИРОВАНИЕ': 'AGGREGATION',
                  'ПЛАМЯ/ОГОНЬ': 'FLAME', 'СОСНА': 'PINE', 'ЖУК': 'BEETLE', 'ДРЕВЕСНЫЙ УГОЛЬ': 'CHARCOAL',
                  'НЕЗВАННЫЙ ГОСТЬ': 'INTRUDER', 'СДЕРЖИВАТЬ': 'TO DETER', 'ЖАЛО': 'STING', 'КВИТАНЦИЯ/ЧЕК': 'RECEIPT',
                  'ТОРГОВАТЬСЯ/ОБМЕНИВАТЬСЯ': 'TO TRADE', 'СЧЕТ ЗА КОММУНАЛКУ': 'UTILITY BILL',
                  'ЧЕЛОВЕЧЕСТВО': 'MANKIND',
                  'СТРЕМИТЬСЯ': 'TO SOUGHT', 'ЮРИСТ': 'ATTORNEY', 'ОСНОВАНИЕ ДЛЯ СУДЕБНОГО ИСКА': 'ACTIONABLE',
                  'РАЗНООБРАЗНЫЕ ВОЗМОЖНОСТИ': 'DIVERSE FEATURES', 'СОБИРАТЬ': 'TO ASSEMBLE',
                  'СИНХРОНИЗИРОВАНЫ': 'SYNCED',
                  'РАЗВЕРНУТЬ/разместить': 'TO DEPLOY', 'ПОПОЛНЯТЬ/НАПОЛНИТЬ': 'TO REFILL', 'МИЛЫЙ': 'ADORABLE',
                  'ОДОЛЖЕНИЕ/ПРОСЬБА': 'FAVOR', 'ЖЕСТОКОСТЬ': 'FEROCITY', 'РАЗОЙТИСЬ!': 'BREAK IT UP!',
                  'МАСТЕР/ВОЛШЕБНИК': 'WIZARD',
                  'ЗАЖИВАТЬ/ИСЦЕЛЯТЬ': 'TO HEAL', 'НАСЕКОМОЕ': 'INSECT', 'СУДНО/КОРАБЛЬ': 'VESSEL',
                  'ОБЕСПОКОЕННОСТЬ': 'CONCERN',
                  'ИСПОРТИТЬ/РАЗРУШИТЬ': 'TO RUIN', 'ПРЕОДОЛЕВАТЬ': 'TO TRANSCEND', 'ПРИМЕНЯТЬ': 'TO APPLY',
                  'ЗАКЛИНИЛО/ЗАЕЛО': 'JAMMED',
                  'СОКРАЩЕНИЕ/СНИЖЕНИЕ': 'REDUCTION', 'ДЕЗИНФИЦИРОВАТЬ': 'TO SANITIZE',
                  'ИСПЫТАНИЕ ОГНЕМ(УСТ.ФР.)': 'TRIAL BY FIRE',
                  'СЛОЖНЕЕ': 'TOUGHER', 'БЫТЬ НА СВЯЗИ': 'BE IN TOUCH', 'ВЗРОСЛЫЕ': 'GROWNUPS', 'УЗЕЛ': 'NODE',
                  'БУДКА/ЛАРЕК': 'BOOTH',
                  'ЧЕСТНО ГОВОРЯ': 'FRANKLY',
                  'ВОЛОСАТЫЙ/': 'SHAGGY', 'ПОДНАПРЯЧЬСЯ/ПОДСУЕТИТЬСЯ': 'TO HUSTLE OUT',
                  'Я ПРИДЕРЖИВАЮСЬ ПРИНЦИПА': 'I ABIDE BY THE MAXIM',
                  'ПУНКТ НАЗНАЧЕНИЯ': 'DESTINATION', 'МАРШРУТ': 'ROUTE', 'ИНСТРУКЦИИ': 'GUIDANCE',
                  'ПРИСТЕГНИСЬ!': 'BUCKLE UP!',
                  'ХРАНИЛИЩЕ КЛЮЧ-ЗНАЧЕНИЕ': 'KEY VALUE STORE', 'КОРТЕЖ': 'TUPLE', 'СИГНАЛИТЬ': 'TO HONK',
                  'РЕЗАТЬ': 'TO CARVE',
                  'УТЕЧКА/ПРОТЕЧКА': 'LEAK', 'ЗАЛОЖНИКИ': 'HOSTAGES', 'СЛЕДИТЬ': 'TO TRACK', 'ЖЕВАТЬ': 'TO CHEW',
                  'СВОЕОБРАЗНЫЙ/СПЕЦИФИЧЕСКИЙ': 'PECULIAR', 'ИЗНАШИВАТЬСЯ': 'TO WEAR OUT', 'САМЫЕ ТЯЖЕЛЫЕ': 'HARSHEST',
                  'СОЖАЛЕТЬ': 'TO REGRET', 'АРХИТЕКТУРА/СИСТЕМА': 'ARCHITECTURE', 'ТРУБА': 'PIPE',
                  'ПРЕДПОЛОЖИТЕЛЬНО': 'APPARENTLY',
                  'ВЗЛОМАТЬ/УНИЧТОЖИТЬ': 'TO TAKE DOWN', 'РАЗРУШЕНИЕ': 'TEARDOWN', 'РАБОТЕНКА': 'GIG',
                  'РАНЕНИЯ/РАНЫ': 'WOUNDS', 'НЕЗНАКОМЕЦ/ЧУЖАК': 'STRANGER', 'ПРИВЛЕКАТЕЛЬНЫЙ/КРАСИВЫЙ': 'ATTRACTIVE',
                  'ПРИЧУДЛИВЫЙ': 'BIZARRE', 'НЕИЗБЕЖНЫЙ/НЕМИНИУЕМЫЙ': 'INEVITABLE', 'НАВОЗ/ПОМЕТ': 'DUNG',
                  'ЛАБИРИНТ': 'MAZE',
                  'ГНЕЗДО': 'NEST', 'УСИЛИЕ': 'EFFORT', 'ДЮЙМ': 'INCH', 'ЗАМАНЧИВО/СОБЛАЗНИТЕЛЬНО': 'TEMPTING',
                  'ЖАБА': 'TOAD', 'СОЛЕНЫЙ': 'BRACKISH', 'ДОБЫЧА/ДИЧЬ': 'PREY', 'СНЕЖНАЯ БУРЯ': 'BLIZZARD',
                  'ДЛЯ МЕНЯ ЧЕСТЬ': 'I AM HONORED',
                  'ПАРАЗИТ/ВРЕДИТЕЛЬ': 'VERMIN', 'ПОТОЛОК': 'CEILING', 'НАСРАЛ': 'POOPED', 'КОЛЛЕГА': 'COWORKER',
                  'ОЦЕНКА': 'ASSESSMENT', 'ВОЗДЕРЖИВАТЬСЯ': 'TO REFRAIN', 'УЛУЧШАТЬ': 'TO ENHANCE', 'ПИЗДА': 'TWAT',
                  'КРОТ': 'MOLE', 'ТОЛЧОК/СОРТИР': 'SHITTER', 'ПРИКАЛЫВАТЬСЯ НАД ТОБОЙ': 'TO PULL YOUR LEG',
                  'НЕЗАМЕТНЫЙ': 'INVISIBLE', 'МАЛОВЕРОЯТНО/СОМНИТЕЛЬНО': 'DOUBTFUL', 'ВЕРОЯТНОСТЬ/ШАНСЫ': 'ODDS',
                  'ОБДУМЫВАТЬ/РАССМАТРИВАТЬ': 'TO CONSIDER', 'ОТСТАВКА': 'RESIGNATION', 'ВСПЫЛЬЧИВЫЙ/ОГНЕННЫЙ': 'FIERY',
                  'ОБСУДИТЬ/ОБГОВОРИТЬ': 'TO GO OVER', 'ПРИЛИЧНОЕ ПОВЕДЕНИЕ': 'TAME DEMEANOR',
                  'КАДРЫ(ВИДЕО,СНИМКИ)': 'FOOTAGE',
                  'БОБ/ФАСОЛЬ': 'BEAN', 'ВЫЙТИ/ОТОЙТИ': 'STEP OUT', 'ПРИБЛИЗИТЬСЯ/ПОДОЙТИ': 'TO APPROACH',
                  'ПРИВОЗИТЬ/ВЫСАЖИВАТЬ': 'TO DROP OFF', 'ПЕРЕХВАТИТЬ': 'TO INTERCEPT', 'ВАЛЮТА': 'CURRENCY',
                  'ПЕРЕСПАТЬ/ЗАМУТИТЬ': 'TO HOOK UP', 'КОМПЕТЕНТНЫЙ': 'COMPETENT', 'ВАЛИ ОТСЮДА!': 'TAKE A HIKE!',
                  'ПРЯТАТЬ/ПРЯТАТЬСЯ': 'TO HIDE', 'НЕ ШУТИ С.../НЕ СВЯЗЫВАЙСЯ С ...': 'DO NOT MESS WITH',
                  'КРАСИВАЯ ПРИЧЕСКА': 'SILKY SMOOTH',
                  'ПРЕДКИ': 'ANCESTORS', 'УГНЕТАТЬ': 'TO OPPRESS', 'ИСЧЕЗНУТЬ': 'TO DISAPPEAR',
                  'ВЫСЫХАТЬ/ВЯНУТЬ': 'SHRIVEL',
                  'СТАДО': 'HERD', 'ПЕСОК': 'SAND', 'ЛОДЫЖКА': 'ANKLE', 'ПРОВОРНЫЙ/ГИБКИЙ': 'AGILE',
                  'ПУГЛИВЫЙ': 'SKITTISH',
                  'ПЕРНАТЫЙ': 'FEATHERED', 'ПРОЛИВНОЙ ДОЖДЬ': 'TORRENTIAL RAIN', 'СВИРЕПЫЙ': 'FEROCIOUS',
                  'ХВОСТ': 'TAIL',
                  'СХЕМА': 'SCHEMA', 'РАБОЧИЙ ПРОЦЕСС': 'WORKFLOW', 'ДВИЖОК': 'ENGINE', 'УСЛУГИ': 'SERVICES',
                  'ПОТРЕБЛЕНИЕ/РАСХОД': 'CONSUMPTION', 'КОЛОНКА': 'COLUMN', 'ВИДИМОСТЬ': 'VISIBILITY',
                  'ЗА ШТУКУ.../КАЖДОМУ': 'APIECE',
                  'ПОДАВИТЬСЯ': 'TO CHOKE', 'НЕСПЕШНО': 'LEISURELY', 'ТЕМП': 'PACE', 'СНАРУЖИ/НА УЛИЦЕ': 'OUT FRONT',
                  'ПОДНЯТЬ БОЛЬШОЙ ПАЛЕЦ ВВЕРХ': 'GIVE THE THUMBS-UP', 'ЖАЛОБА': 'COMPLAINT', 'ЛИЧНОСТЬ': 'INDIVIDUAL',
                  'УЯЗВИМЫЙ': 'VULNERABLE', 'САНТЕХНИК': 'PLUMBER', 'ИНВЕСТИЦИЯ': 'INVESTMENT',
                  'ЧУВСТВА': 'SENSIBILITIES',
                  'ПОХАБНО': 'RAUNCHY', 'ХИТ СЕЗОНА': 'HOT TICKET', 'ЧАС ПИК': 'RUSH HOUR',
                  'ЛЮБЕЗНОСТЬ/ВЕЖЛИВОСТЬ': 'COURTESY',
                  'НА ГРАНИ': 'ON THE VERGE', 'ХВАТИТ ИГРАТЬ!': 'QUIT PLAYING!', 'НОВИЧОК/САЛАГА': 'ROOKIE',
                  'ПОЗОР/': 'DISGRACE', 'МИЗИНЕЦ': 'PINKIE', 'МЭР': 'MAYOR', 'ЗАДАНИЕ': 'ASSIGNMENT',
                  'НОСИЛЬЩИК': 'SKYCAP',
                  'ПРИТЕСНЕНИЕ/ЗАПУГИВАНИЕ': 'HARASSMENT', 'НЕ ТВОЕ ДЕЛО': 'MIND YOUR OWN BUSINESS!',
                  'ПОДОЗРЕВАЕМЫЙ': 'SUSPECT',
                  'ШАНТАЖ': 'SHAKEDOWN', 'РАССЛЕДОВАНИЕ': 'INVESTIGATION', 'ТАРЕЛКА ЛАПШИ': 'A CUP OF NOODLES',
                  'ГОВЯДИНА': 'BEEF',
                  'УСТРАНЯТЬ': 'TO ELIMINATE', 'БЕЗУМИЕ': 'MADNESS', 'НАПАДЕНИЕ/НАСИЛИЕ': 'ASSAULT',
                  'СПАРЖА': 'ASPARAGUS',
                  'РАССТРОИТЬ/ОБИДЕТЬ': 'TO UPSET', 'УДУШЬЕ': 'CHOKING', 'СБЕЖАТЬ/УДРАТЬ': 'TO SCURRY',
                  'ПРЕРЫВАТЬ': 'TO INTERRUPT',
                  'РАССЕРДИТЬ': 'TO DISPLEASE', 'ВЫТАЩИТЬ/ВЫЙТИ': 'TO PULL OUT',
                  'ПРОГОРЕТЬ/ОБАНКРОТИТЬСЯ': 'TO GO BUST',
                  'УБЕЖДАТЬ': 'TO CONVINCE', 'СПРАВЕДЛИВОСТЬ': 'FAIRNESS', 'ГЛУБОКО ПОХУЙ': 'GIVE A FLYING FUCK',
                  'ЗАГОЛОВОК': 'HEADLINE', 'НЮХАТЬ': 'TO SNIFF', 'ЗАТХЛЫЙ': 'MUSTY', 'УСИЛИТЬ': 'TO HEIGHTEN',
                  'ОБРАБОТКА ОШИБОК': 'ERROR HANDLING', 'ЗАХВАТ': 'CAPTURE', 'САМОАНАЛИЗ': 'INTROSPECTION',
                  'МАСШТАБИРОВАНИЕ': 'SCALING',
                  'КОНЕЧНОСТЬ': 'LIMB', 'ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ': 'SOFTWARE', 'ТРЕХМЕРНЫЙ': 'THREE DIMENSIONAL',
                  'СРАВНИВАТЬ/СОПОСТОВЛЯТЬ': 'TO COLLATE', 'СТИМУЛ': 'STIMULUS', 'НАСТРАИВАТЬ': 'TO ADAPT',
                  'ПОПЫТКА': 'ATTEMPT',
                  'ДОКОПАТЬСЯ ДО ИСТИНЫ': 'TO GET TO THE BOTTOM', 'ВЫЙТИ ИЗ...': 'TO COME OUT OF', 'НАРОДНЫЙ': 'FOLKSY',
                  'ВОСПРИНИМАТЬ': 'TO PERCEIVE', 'ПОЭТОМУ': 'THEREFORE', 'ОСТРОЕ ОБОНЯНИЕ': 'KEEN A SENSE',
                  'ГОСТИННАЯ': 'LIVING ROOM', 'НАГЛЯДНЫЙ ПРИМЕР': 'CASE IN POINT', 'СПОР': 'ARGUING',
                  'ПОРТАТИВНЫЙ/ПЕРЕНОСНОЙ': 'PORTABLE',
                  'БАРЬЕР': 'BARRIER', 'КАБИНКА': 'CUBICLE', 'ИМПРОВИЗИРОВАТЬ': 'IMPROVISE',
                  'НЕЭФФЕКТИВНОСТЬ': 'INEFFICIENCY',
                  'В ГЛАВНЫХ РОЛЯХ...': 'STARRING', 'ПОСАДОЧНЫЙ ТАЛОН': 'BOARDING PASS', 'ПОСОЛЬСТВО': 'EMBASSY',
                  'ИНОСТРАНЕЦ': 'FOREIGNER', 'ТОРГОВАТЬСЯ': 'TO HAGGLE', 'ГРАНИЦА': 'BORDER', 'УТЕС': 'CLIFF',
                  'СЕЛЬСКАЯ МЕСТНОСТЬ': 'COUNTRYSIDE',
                  'ДАМБА/ПЛОТИНА': 'DAM', 'БОЛОТО': 'SWAMP', 'ЛОСЬ': 'ELK', 'ХОМЯК': 'HAMSTER', 'СКУНС': 'SKUNK',
                  'ВЫШЕ НУЛЯ': 'ABOVE ZERO',
                  'НИЖЕ НУЛЯ': 'BELOW ZERO', 'МЕЛКИЙ ДОЖДЬ': 'DRIZZLE', 'СУХОЙ': 'DRY', 'ГОЛОЛЕД': 'ICE-SLICK',
                  'ЛИВЕНЬ': 'RAINFALL',
                  'ГРОМ': 'THUNDER', 'ВЬЕТНАМКИ': 'FLIP-FLOPS', 'МОЛНИЯ': 'BOLT', 'МЕДЬ': 'COPPER',
                  'ПОТРЕБЛЕНИЕ ТОПЛИВА': 'FUEL CONSUMPTION',
                  'ЗНАЧИТЕЛЬНЫЙ': 'SIGNIFICANT', 'ПОВЕРХНОСТЬ': 'SURFACE', 'УМЕНЬШИТЬ ВЕС': 'TO REDUCE THE WEIGHT',
                  'СОПРОТИВЛЯТЬСЯ': 'TO RESIST', 'РЕШИТЬ ПРОБЛЕМУ': 'TO FIX THE PROBLEM', 'КМСЛОРОД': 'OXYGEN',
                  'ЗАГРЯЗНЕНИЕ': 'POLLUTION',
                  'СОЛНЕЧНАЯ ЭНЕРГИЯ': 'SOLAR POWER', 'ТРАЕКТОРИЯ': 'TRAJECTORY', 'ЗАПОР': 'CONSTIPATION',
                  'СЛОЙ': 'LAYER',
                  'ЗАПИСЫВАТЬ': 'TO WRITE DOWN',
                  'ПРОВАЛИТЬСЯ,ТЕРПЕТЬ НЕУДАЧУ': 'TO FALL THROUGH',
                  'ЗАКРЫТЬСЯ/ПРЕКРАЩЕНИЕ ДЕЯТЕЛЬНОСТИ': 'TO CLOSE DOWN',
                  'НАЖИВАТЬСЯ/ЗАРАБАТЫВАТЬ ДЕНЬГИ НА ЧЕМ-ТО': 'TO CASH IN ON', 'ВЫИГРЫВАТЬ/ПРЕУСПЕВАТЬ': 'TO GET AHEAD',
                  'ОГОРЧАТЬ ИЛИ РАЗДРАЖАТЬ КОГО-ТО': 'TO WIND SOMEBODY UP',
                  'ВЫВОДИТЬ ИЗ СЕБЯ/БЕСИТЬ': 'TO GET TO SOMEBODY',
                  'РАЗДРАЖАТЬ/ДЕЙСТВОВАТЬ НА НЕРВЫ': 'TO PISS SOMEBODY OFF', 'ПЕРЕЗАГРУЗКА': 'REBOOT',
                  'БЕСПРОВОДНОЙ СИГНАЛ': 'WAIRLESS SIGNAL',
                  'ТОЧКА ДОСТУПА': 'HOTSPOT', 'СЕКУНДОМЕР': 'STOPWATCH', 'ИССЛЕДОВАТЬ': 'TO EXPLORE',
                  'РАСПОЗНАВАТЬ': 'TO RECOGNIZE',
                  'ЭКРАНИЗАЦИЯ': 'ADAPTATION', 'ЗРИТЕЛИ': 'AUDIENCE', 'ДУБЛИРОВАННЫЙ': 'DUBBED', 'ЖАНР': 'GENRE',
                  'СЮЖЕТ': 'PLOT',
                  'ВЛАМЫВАТЬСЯ/ВРЫВАТЬСЯ': 'TO BREAK IN', 'ПРОДОЛЖАТЬ ЗАНИМАТЬСЯ ЧЕМ-ТО': 'TO CARRY ON',
                  'ЗАКОНЧИТЬ/ПОПАСТЬ': 'TO END UP',
                  'УПАСТЬ/ПАДАТЬ': 'TO FALL DOWN', 'УХОДИТЬ/УДРАТЬ/УСКОЛЬЗНУТЬ': 'TO GET AWAY',
                  'ПРОЙТИ ЧЕРЕЗ/ПОВТОРЯТЬ': 'TO GO THROUGH',
                  'ПРИХОДИТЬ / ПОЯВЛЯТЬСЯ': 'TO SHOW UP', 'ВКЛЮЧАТЬ': 'TO SWITCH ON', 'ВЫКЛЮЧАТЬ': 'TO SWITCH OFF',
                  'ПРЕВРАЩАТЬСЯ В КОГО-ТО': 'TO TURN INTO', 'СОЗДАВАТЬ/ОРГАНИЗОВЫВАТЬ/УСТРАИВАТЬ': 'TO SET UP',
                  'НАДЕВАТЬ': 'TO PUT ON',
                  'СПЕЛЫЙ/': 'RIPE', 'СЛИВА': 'PLUM', 'НАПИТОК': 'BEVERAGE', 'ГОРЯЧИЙ ПУНШ': 'HOT TODDY',
                  'ЖАЛЮЗИ': 'BLINDS',
                  'ВЫЯСНЯТЬ/РАЗБИРАТЬСЯ': 'TO FIGURE OUT', 'ОЖИДАТЬ ЧЕГО-ТО С НЕТЕРПЕНИЕМ': 'TO LOOK FORWARD TO',
                  'ТЕРЯТЬ СОЗНАНИЕ/РАЗДАВАТЬ': 'TO PASS OUT', 'ПОДДЕРЖИВАТЬ': 'TO STAND BY',
                  'ГРАВИРОВАТЬ': 'TO ENGRAVE', 'СТРАТЕГ': 'STRATEGIST', 'ОБХОДНОЙ ПУТЬ': 'AVOIDING LINE',
                  'ОПУБЛИКОВЫВАТЬ': 'TO RELEASE', 'ТЮРЬМА': 'JAIL', 'ОТНОШЕНИЕ/ПОЗИЦИЯ': 'ATTITUDE',
                  'КТО ПЛАТИТ БОЛЬШЕ': 'BIDDER',
                  'ИНВАЛИДНАЯ КОЛЯСКА': 'WHEELCHAIR', 'ПОВРЕЖДЕННЫЙ': 'DISABLED', 'КОММУНИКАТОР': 'COMMUNICATOR',
                  'НЕДАЛЬНОВИДНЫЙ': 'HINDSIGHT', 'МУДРОСТЬ': 'WISDOM', 'ЗАГАДКА': 'RIDDLE', 'ДОВЕРИЕ': 'CONFIDENCE',
                  'СОГЛАСИЕ/ЕДИНСТВО': 'ACCORD', 'ТО,ЧТО ПРИЧИТАЕТСЯ': 'DUE', 'СИЛЬНОЕ ЖЕЛАНИЕ': 'DESIRE',
                  'ЧЕСТНО': 'HONESTLY', 'СОВЕРШЕНСТВО': 'PERFECTION', 'УБЕЖИЩЕ/УКРЫТИЕ': 'SHELTER',
                  'СРЕДНЕЕ': 'AVERAGE',
                  'РАЗОБЛАЧАТЬ': 'TO REVEAL', 'ПОРАЖЕНИЕ': 'DEFEAT',
                  'ЗАВЛАДЕНИЕ ИМУЩЕСТВОМ РАНЬШЕ ДРУГИХ': 'PREOCCUPATION',
                  'УДИВЛЯТЬ': 'TO WONDER', 'ПРЕДЛОЖЕНИЕ ЦЕНЫ': 'BID', 'ВДОХНОВЛЕНИЕ': 'INSPIRATION',
                  'ПОСВЯЩАТЬ': 'TO DEDICATE',
                  'ОТВЕРГАТЬ': 'TO REFUSE', 'СТИМУЛИРОВАТЬ': 'TO STIMULATE', 'УНИЖЕННЫЙ': 'HUMILIATED',
                  'ГАЛОП': 'CANTER',
                  'СЧИТАТЬ (В УМЕ)': 'TO RECKON', 'ТРЕБОВАТЬ': 'TO CLAIM', 'БЫСТРО ПИСАТЬ': 'TO BANG OUT',
                  'ПРИЕМЛИМОСТЬ': 'ELIGIBILITY', 'СЧЕТ(НА ОПЛАТУ)': 'BILL', 'СОПЕРНИК': 'RIVAL',
                  'РАДИКАЛЬНО': 'RADICALLY',
                  'ЭКСПЕРТИЗА': 'EXPERTISE', 'ОДАРЕННЫЙ': 'CAPABLE', 'КОЛИЧЕСТВО/ВЕЛИЧИНА': 'AMOUNT',
                  'ПОСЕЛЯТЬ ВНЕ ДОМА': 'TO BOARD OUT',
                  'ФИЛОСОФСКИЙ': 'PHILOSOPHICAL', 'В НАСТОЯЩЕЕ ВРЕМЯ': 'NOWADAYS', 'ПОЗОРНЫЙ': 'INFAMOUS',
                  'НАГРАДА': 'AWARD',
                  'БОРЬБА/ДРАКА': 'TUSSLE', 'ОДНОРАЗОВЫЙ': 'DISPOSABLE', 'ВЫСКАЗЫВАТЬСЯ': 'TO EXPRESS',
                  'ВЛИЯНИЕ/ВОЗДЕЙСТВИЕ': 'INFLUENCE',
                  'НЕДОВОЛЬСТВО': 'GRUDGE', 'СИЛА/МОЩЬ': 'FORCE', 'ОТЪЕЗД/УХОД': 'DEPARTURE', 'ГРАФИН': 'DECANTER',
                  'ЭКИПАЖ': 'CARRIAGE', 'АМБУЛАТОРНЫЙ': 'AMBULANT', 'СЛУЧАЙ': 'CASE',
                  'ЗАЛИВАТЬ/ЗАТАПЛИВАТЬ': 'TO FLOOD',
                  'ЭКРАН': 'SCREEN', 'УЛИТКА': 'SNAIL', 'ЦИТИРОВАТЬ': 'TO QUOTE', 'ЗАПРЕЩАТЬ': 'TO PROHIBIT',
                  'РАЗМАХ': 'SWING',
                  'ВРЕМЯ ВЫШЛО': 'TIME IS UP', 'МЕНЕДЖЕР ПО ЗАКУПКАМ': 'PROCUREMENT MANAGER', 'ПОПЕРЕК': 'ACROSS',
                  'РАСШИРЯЕМЫЙ': 'EXTENSIBLE', 'ЧАСТИЦА': 'PARTICLE', 'ВЫГРЕБНАЯ ЯМА': 'SINK',
                  'КОЗЛИННАЯ БОРОДКА': 'GOATEE',
                  'ОКРУЖАТЬ/ОБНОСИТЬ': 'TO ENCOMPASS', 'ОСТЕПЕНИТЬСЯ': 'TO SETTLE DOWN', 'ВЛИЯНИЕ': 'IMPACT',
                  'НАКЛАДНАЯ': 'MANIFEST',
                  'СБРАСЫВАТЬ': 'TO FLIP', 'ВНИМАНИЕ!': 'HEADS UP!', 'СОВЕРШАТЬ': 'TO COMMIT', 'ШАБЛОН': 'TEMPLATE',
                  'КАПУСТА': 'CABBAGE', 'ОТРИЦАТЬ': 'TO DENY', 'ДОМАШНИЙ ТОРТ': 'TART', 'ПЛЯЖНЫЙ СПАСАТЕЛЬ': 'BAYWATCH',
                  'Я НИЧЕГО НЕ ИМЕЮ ПРОТИВ': 'I DO NOT MIND', 'РАЗУМНЫЙ': 'RATIONAL',
                  'НАЧИНАТЬ/ПРЕДПРИНИМАТЬ': 'TO INITIATE',
                  'СКЛАД/ХРАНИЛИЩЕ': 'STORAGE', 'ВОСПРОИЗВОДИМЫЙ': 'REPRODUCTIBLE', 'ВОЗМОЖНОСТЬ': 'OPPORTUNITY',
                  'ОПТОВЫЕ ЦЕНЫ': 'WHOLESALE PRICES', 'НАВЯЗЧИВАЯ ИДЕЯ': 'OBSESSION', 'КРЕВЕТКА/': 'PRAWN',
                  'ОБНИМАТЬ И ЦЕЛОВАТЬ': 'TO SMOOCH', 'ОЛЕНИНА': 'VENISON', 'ЕДВА/ЕЛЕ-ЕЛЕ': 'BARELY',
                  'ПРИЛОЖЕНИЕ': 'APP',
                  'ГОЛОСОВАНИЕ': 'VOTE', 'МУСОР': 'GARBAGE', 'КОМАНДИРОВКА': 'BUSSINES TRIP', 'ИСКАТЬ': 'TO SEEK',
                  'МНЕНИЕ': 'OPINION', 'КУСАТЬ': 'TO BITE', 'БЕГУН ТРУСЦОЙ': 'JOGGER', 'НЕДАВНИЙ': 'RECENT',
                  'РАСШИРЯТЬ': 'TO EXPAND',
                  'ГНИЛАЯ ЛОЖЬ': 'ROTTEN LIE', 'РВОТА': 'VOMIT', 'ДОГОВОР': 'BOND', 'БАБКИ/ФИШКИ': 'DIBS',
                  'ЧЕСТНОЕ СЛОВО': 'I MEAN IT',
                  'ГОРЕ': 'SORROW', 'АВАРИЯ': 'ACCIDENT', 'БЕСИТЬСЯ': 'TO FREAK OUT', 'ПОДВАЛ': 'BASEMENT',
                  'ЗАПУСТИТЬ': 'TO LAUNCH',
                  'СПОСОБ': 'MODE', 'НАБОР': 'SET', 'ЖАРИТЬ': 'TO FRY', 'ВЫКЛАДЫВАЙ/ДАВАЙ НАЧИНАЙ': 'TO FIRE AWAY',
                  'УХОДИТЬ': 'TO WALK AWAY', 'ВЕТЧИНА': 'HAM', 'ПРОДОВОЛЬСТВЕННЫЙ МАГАЗИН': 'GROCERY STORE',
                  'ГРУЗ': 'CARGO',
                  'СОТРУДНИК': 'EMPLOYEE', 'ОПИСЫВАТЬ': 'TO DESCRIBE', 'ПОСТАВЩИК': 'SUPPLIER', 'ДЕФОЛТ': 'DEFAULT',
                  'ДОБАВЛЯТЬ': 'TO APPEND', 'БЕЗУСЛОВНО/КОНЕЧНО': 'CERTAINLY', 'ПОДВЕРГАТЬ/РАЗОБЛАЧАТЬ': 'TO EXPOSE',
                  'ГРАФИК': 'SHEDULE', 'СПРАВЕДЛИВО': 'FAIR', 'ПРЕИМУЩЕСТВО/ПРЕВОСХОДСТВО': 'ADVANTAGE',
                  'ВНУТРИ': 'INSIDE',
                  'ВЕРОЯТНО': 'PROBABLY', 'НОС К НОСУ': 'TOE TO TOE', 'ВЫЗЫВАТЬ': 'TO CAUSE', 'ВХОДЯЩИЕ': 'INBOX',
                  'СОВЕТ/': 'ADVICE', 'ПОДАВАТЬ(ЗАЯВКУ)': 'TO SUBMIT', 'ПРИМЕЧАТЬ': 'TO NOTE', 'НАЧИНАТЬ': 'TO KICK OFF',
                  'ПРИГЛАШЕНИЕ': 'INVINTATION', 'ВЫСТУПАТЬ/ИГРАТЬ': 'TO PERFORM', 'ХРАБРОСТЬ': 'COURAGE',
                  'ИНТЕНСИВНОСТЬ': 'INTENSITY', 'ПОВЫШАТЬ': 'TO RAISE', 'КРИТИЧЕСКИЙ': 'CRITICAL',
                  'ПРЕИМУЩЕСТВО': 'EDGE',
                  'ПОМИМО ЭТОГО': 'APART FROM THAT', 'ДЫРА': 'GAP', 'ПРОПУСКАТЬ(ФУТБОЛ)': 'TO CONCEDE',
                  'РАССТРОЕННЫЙ': 'FRUSTRATED', 'ВЫПОЛНЯТЬ': 'TO EXECUTE', 'СМОТРЕТЬ ВПЕРЕД': 'TO LOOK AHEAD',
                  'ЭНЕРГИЧНЫЙ': 'SPIRITED', 'В КОНЕЧНОМ СЧЕТЕ': 'ULTIMATELY', 'РАЗОЧАРОВЫВАТЬ': 'TO DISSAPOINT',
                  'НАПРОТИВ': 'IN FRONT OF', 'БЕЗЖАЛОСТНЫЙ': 'RUTHLESS', 'О ТОМ': 'ON WHETHER', 'ПРАВИЛЬНО': 'PROPERLY',
                  'ОТРАЖАТЬ': 'TO REFLECT', 'АВТОТРАСНПОРТНОЕ СРЕДСТВО': 'VEHICLE',
                  'ОБЛАДАЮЩИЙ САМОСОЗНАНИЕМ': 'SELF-AWARE',
                  'ПОТОМСТВО': 'BREED',
                  'ПОДОНОК': 'CREEP', 'ПРОВАЛ/НЕУДАЧА': 'FLOP', 'РАЗГРУЗКА': 'UNLOADING',
                  'ДАВАЙ,ПОЕХАЛИ': 'THERE YOU GO',
                  'ЖЕРТВЫ': 'CASUALTIES', 'ПРЯМО': 'STRAIGHT', 'ПРОВАЛИВАЙ!': 'TO GET LOST!', 'ЖЕНОПОДОБНЫЙ': 'PANSY',
                  'ОПЛАТА ЗА ПРОСМОТР': 'PAY-PER-VIEW', 'ПОСТРАДАВШИЙ': 'AFFECTED', 'ХОДИТЬ ПОВСЮДУ': 'TO WALK AROUND',
                  'ПОДСТРЕЛИТЬ': 'TO POP OFF', 'НА ПОЛЕ': 'ON THE PITCH', 'ПЕРЕКУСИТЬ/ЗАКУСИТЬ': 'TO HAVE A BITE',
                  'НАКЛОННЫЙ': 'DOWNWARD', 'УГРОЗА': 'THREAT', 'ПЕРВОСТЕПЕННЫЙ': 'PRIMARY',
                  'ВЫСЛУШАЙТЕ МЕНЯ!': 'HEAR ME OUT!',
                  'ПОСТАВЩИК/КОРМИЛЕЦ': 'PROVIDER', 'ИСТОЧНИК': 'SOURCE', 'ВООРУЖЕННЫЙ': 'ARMED',
                  'ЗА ИСКЛЮЧЕНИЕМ': 'EXCEPT',
                  'УСКОРИТЕЛЬ/ПЕДАЛЬ ГАЗА': 'ACCELERATOR', 'ВХОДИТЬ/ВЛЕЗАТЬ': 'TO GET IN', 'СУДЬБА': 'DESTINY',
                  'НЕБОСКРЕБ': 'SKYSCRAPER', 'ПИТАТЕЛЬНЫЙ': 'NUTRITIOUS', 'ЗАКАЗЫВАТЬ': 'TO ORDER', 'НИЗ': 'BOTTOM',
                  'ОХОТНИК/НЕЖЕЛАННЫЙ УХАЖЕР': 'STALKER', 'ВЫБРАСЫВАТЬ': 'TO TOSS',
                  'ВЫСОКИЕ МОРАЛЬНЫЕ УСТОИ': 'MORAL HIGH GROUND',
                  'ВЕЛИКОДУШНЫЙ': 'GENEROUS', 'ПОДУМАЙ ХОРОШЕНЬКО': 'THINK IT OVER', 'ПРЕДПОЛАГАТЬ': 'TO SUPPOSE',
                  'МЧАТЬСЯ СО ВСЕХ НОГ': 'TO HIGHTAIL', 'РАДОСТИ': 'OFJOY', 'БЕССМЫСЛЕННЫЙ': 'POINTLESS',
                  'ЖАЖДАТЬ': 'TO THIRSTY',
                  'ЗАСУДИТЬ': 'TO SUE', 'ПУХ': 'FLUFF', 'ДОМОРОЩЕННЫЙ': 'HOMEGROWN', 'ВИД/СОРТ': 'SORT',
                  'НАКАЗЫВАТЬ': 'TO PUNISH', 'СПИРАЛЬ': 'SPIRAL', 'НЕ ГЛУПИ!': 'DO NOT BE SILLY!',
                  'ОСТОРОЖНО!': 'WATCH OUT!',
                  'УДАЛЯТЬ': 'TO TAKE AWAY', 'ПРОДОЛЖАТЬ ДВИЖЕНИЕ': 'TO MOVE ON', 'СУДИМОСТЬ': 'RAP SHEET',
                  'НАДОЕДЛИВЫЙ РЕБЕНОК': 'BRAT', 'БЕДСТВИЕ': 'DISASTER', 'УВЕЛИЧЕНИЕ': 'BOOST',
                  'ПРИВЛЕКАТЕЛЬНЫЙ': 'LOVABLE',
                  'ДОРОЖКА ДЛЯ РАЗБЕГА/ВЗЛЕТНАЯ ПОЛОСА': 'RUNWAY', 'МЕНЕЕ/МЕНЬШИЙ': 'LESS', 'ШАМАН': 'VOODOO',
                  'КАК ХОЧЕШЬ!': 'SUIT YOURSELF!', 'ПОГРУЗКА': 'LOADING', 'СЫРОЕ/СЫРОЙ(ПИЩА)': 'RAW',
                  'БЫСТРО': 'PROMPTLY', 'В НЕКОТОРОМ РОДЕ/ОТЧАСТИ': 'SOMEWHAT', 'НАМЕК': 'INNUENDO',
                  'УЗНАВАТЬ': 'TO INQUIRE', 'ТЕРПЕЛИВО': 'PATIENT', 'РАКОВИНА': 'CONCH', 'НАБЛЮДАТЕЛЬ': 'OBSERVER',
                  'ОБОЛОЧКА': 'SHELL', 'СМЕКАЛКА': 'SAVVY', 'РЯДОМ': 'BESIDE', 'ПРОСЬБА/ЗАПРОС': 'REQUEST',
                  'БЕЗБРАЧИЕ': 'CELIBACY', 'ОБРАЩЕНИЕ': 'APPEAL', 'УВЛЕЧЕННЫЙ': 'KEEN', 'ЦЕЛЫЙ/ВЕСЬ/ПОЛНЫЙ': 'ENTIRE',
                  'ВЫКЛЮЧЕН': 'TURNED OUT', 'ОБЪЕКТ/СООРУЖЕНИЕ': 'FACILITY', 'ПОДОЖДАТЬ': 'TO HANG ON',
                  'ИДТИ С КЕМ-ЛИБО': 'TO COME ALONG', 'ДОЛГ': 'DUTY', 'ПРИЯТЕЛЬ': 'PAL', 'КУТАТЬСЯ': 'TO BUNDLE UP',
                  'ГНИТЬ': 'TO ROT', 'БАНКА': 'JAR', 'ЯЩИК': 'CHEST', 'СНИЗИТЬ(ЦЕНУ)': 'TO KNOCK OFF',
                  'УКРАСТЬ': 'TO ROB', 'МЕДОВЫЙ МЕСЯЦ': 'HONEYMOON', 'ПОЩЕЧИНА': 'SLAP', 'ИЗВРАЩЕНЕЦ': 'PERVENT',
                  'ЛОБ': 'FOREHEAD', 'ВЫПЛЕВЫВАТЬ': 'TO SPIT OUT', 'ГРОБОВЩИК': 'UNDERTAKER', 'СЧЕТЧИК': 'COUNTER',
                  'ПО СООБЩЕНИЯМ': 'REPORTEDLY', 'ПЕРЕИМЕНОВАТЬ': 'TO RENAME',
                  'ПОКА ЧТО ВСЕ ИДЕТ ХОРОШО': 'SO FAR SO GOOD',
                  'ИЗМУЧЕННЫЙ': 'EXHAUSTED', 'ПРИМАНКА': 'BAIT', 'ПРОТИВНЫЙ': 'CREEPY', 'СЕРЬЕЗНО?': 'NO FOOLING?',
                  'НАЖИМАТЬ': 'TO SQUEEZE', 'ХУДШЕЕ': 'WORST', 'ПАРШИВЫЙ': 'LOUSY',
                  'ВЫРАЖАЙСЯ ЯСНЕЕ': 'MAKE YOURSELF CLEAR',
                  'ТЫ С ЭТИМ СПРАВИШЬСЯ?': 'CAN YOU MANAGE IT?', 'ВЫГОДНЫЕ УСЛОВИЯ': 'FAVORABLE TERMS',
                  'ДОСТИЖЕНИЕ': 'ACHIEVEMENT', 'ЛЮБОПЫТНЫЙ': 'NOSY', 'ПРЕДОСТАВЛЯТЬ': 'TO PROVIDE',
                  'ГРЯЗНОЕ ЖИВОТНОЕ': 'FILTHY ANIMAL', 'БОЛВАН': 'MORON', 'ПРИОБРЕТАТЬ/ДОСТИГАТЬ': 'TO ACQUIRE',
                  'ХРОМАЯ НОГА': 'GIMPY LEG', 'БЛАГОСЛОВЛЯТЬ': 'TO BLESS', 'ПРИНУЖДЕНИЕ': 'COMPLUSION',
                  'ЗЛО': 'MISCHIEF', 'ПРИСТУПАТЬ ПРЯМО К ДЕЛУ': 'TO GET RIGHT ON IT',
                  'ТЫ В СВОЕМ УМЕ?': 'ARE YOU OUT OF YOUR MIND?',
                  'СРЕДА(ОБИТАНИЯ)': 'ENVIRONMENT', 'ТАК ТЕБЕ И НАДО': 'IT SERVES YOU RIGHT', 'КРОМЕ ТОГО': 'BESIDES',
                  'ПРИКРЕПЛЯТЬ': 'TO ATTACH', 'ОЛЕНЬ': 'DEER', 'РОГА': 'ANTLERS', 'РЕБЕНОК': 'INFENT',
                  'НОЛЬ': 'SCRATCH',
                  'ПРЕСТУПНИК': 'DELINQUENT', 'МОШЕННИЧЕСТВО/': 'FRAUD', 'РАБОТА ЛОПАТОЙ': 'SHOVELING',
                  'ПО УМЕРЕННОЙ ЦЕНЕ': 'MODERATE-PRICED', 'ВЫРВАТЬСЯ НАРУЖУ': 'TO BUST OUT', 'ОРУЖИЕ': 'WEAPON',
                  'ШЛЕПОК': 'SPANK', 'КИПЕТЬ': 'TO BOIL', 'НАПИТЬСЯ': 'TO GET DRUNK', 'ХОЛОДИЛЬНИК': 'FRIDGE',
                  'КАК-НИБУДЬ УВИДИМСЯ': 'SEE YOU AROUND', 'В КОНЦЕ КОНЦОВ': 'EVENTUALLY',
                  'ЗАЗНАВАТЬСЯ': 'TO GET COCKY',
                  'КЭШ': 'CACHS', 'ПУТЬ': 'PATH', 'ЦЕНИТЬ': 'TO APPRECIATE', 'ОСНОВА': 'BASIS',
                  'ЯДРО/СЕРДЦЕВИНА': 'CORE',
                  'НАСТРОЙКИ': 'SETTINGS', 'СКЛАД': 'WAREHOUSE', 'РАЗРЫВ': 'SPLIT', 'ОБЩАЯ ПЛОЩАДЬ': 'TOTAL AREA',
                  'ЭНЕРГЕТИКА': 'VIBES', 'ВОСПИТЫВАТЬ': 'TO REAR', 'МОЯ ТОЧКА ЗРЕНИЯ': 'MY POINT',
                  'ОБОРУДОВАНИЕ': 'EQUIPMENT',
                  'НЕДЕЙСТВИТЕЛЬНОЕ': 'INVALIDATE', 'КОНВЕРТ': 'ENVELOPE', 'ПРЕСНЫЙ': 'BLAND',
                  'СОБСТВЕННОСТЬ': 'PROPERTIES', 'КИСЛЫЙ': 'SOUR', 'ЭКСПОНАТ': 'EXHIBIT',
                  'ФИГУРА РЕЧИ': 'FIGURE OF SPEECH', 'БУМАЖНИК': 'WALLET', 'ГОРЬКИЙ': 'BITTER',
                  'ОБРУЧИТЬСЯ': 'TO ENGAGE', 'КЛИЕНТСКАЯ БАЗА': 'CUSTOMER BASE', 'ПОЛНОСТЬЮ': 'FULLY',
                  'ПРЕДЛОЖЕНИЕ': 'SUGGESTION', 'РЕКОМЕНДАЦИЯ': 'REFERENCE', 'ПРИНЯТЬ': 'TO ACCEPT',
                  'ПРИЦЕП': 'TRAILER', 'УДОВОЛЬСТВИЕ': 'PLEASURE', 'ВСТРЕЧА/': 'ENCOUNTER',
                  'УДОБНО': 'CONVENIENT', 'Я СЛЕТЕЛ С КАТУШЕК': 'I AM OFF MY HINGES',
                  'ОТВЕТНЫЙ УДАР': 'BACKLASH', 'МЕРОПРИЯТИЕ': 'EVENT', 'ДОСТИЖЕНИЯ': 'ACHIEVING',
                  'НЕ НАДО ОБ ЭТОМ': 'DO NOT MENTION THAT', 'МУЖСКОЙ ТУАЛЕТ': 'URINAL',
                  'ЩЕКА': 'CHEEK', 'ГЛУБИНА': 'DEPTH', 'КОЙКА': 'BUNK', 'СМУЩЕНИЕ': 'CONFUSION',
                  'ПЫХТЕТЬ': 'TO HUFFING', 'ДОЛЯ': 'SHARE', 'ГРОБ': 'COFFIN', 'ТВЕРДЫЙ': 'HARDENED',
                  'ПОВЯЗКА': 'PATCH', 'НЕУДАЧА': 'FAILURE', 'САЛФЕТКА': 'NAPKIN', 'СПУСКАТЬСЯ': 'TO GET DOWN',
                  'СГИБАТЬ': 'TO BENT', 'МЕЛКОЕ ВОРОВСТВО': 'SHOPLIFTING', 'ПИРАТ': 'BUCCANEER',
                  'ПЫЛКИЙ/ГОРЯЧИЙ': 'FERVENT', 'КУЧА': 'PILE', 'КРОШЕЧНЫЙ': 'TINY', 'ПОЯВЛЯТЬСЯ': 'TO APPEAR',
                  'ОДИНОКИЙ': 'SOLITARY', 'ОТДЕЛЬНЫЙ': 'SEPARATE', 'ОБЪЯТИЯ': 'EMBRACE', 'ПОД/НИЖЕ/ВНИЗУ': 'BENEATH',
                  'РАЗРУШИТЕЛЬНЫЙ': 'DEVASTATING', 'УЛУЧШЕНИЕ': 'IMPROVEMENT', 'КИПАРИС': 'CYPRESS',
                  'БЕСКОНЕЧНЫЙ': 'INTERMINABLE', 'РОЩА': 'GROVE', 'РАЗВОД': 'DIVORCE', 'ТЕМНЫЙ': 'SHADOWY',
                  'ГЛЫБА': 'CLUMP', 'ПЕРЕКУСИТЬ': 'TO SNAK', 'ТУМАННЫЙ': 'FOGGY', 'СТРАСТНЫЙ/ВЛЮБЛЕННЫЙ': 'PASSIONATE',
                  'ИЗГИБ': 'MEANDER', 'РОМАН': 'AFFAIR', 'ВООБЩЕ/В ЦЕЛОМ': 'ALTOGETHER', 'ВЫЗДОРОВЛЕНИЕ': 'HEALING',
                  'ТОШНОТВОРНЫЙ': 'SICKENING', 'ХРУПКИЙ/': 'BRITTLE', 'ЗАПУТАННЫЙ': 'KNOTTY',
                  'УСЛОЖНЯТЬ': 'TO COMPLICATE',
                  'ДАЛЕЕ/ДАЛЬШЕ': 'FURTHER', 'ЧИСТО': 'PURELY', 'РУБИТЬ': 'TO CHOPP', 'ЛАСКАТЬ': 'TO CARESS',
                  'ПРИЧИНЯТЬ': 'TO INFLICT', 'ПРИ СВЕЧАХ': 'CANDLELIT', 'МЕРЦАЮЩИЙ': 'FLICKERING',
                  'НЕЗАПЯТНАНЫЙ': 'UNSULLIED', 'СОЧИНЯТЬ': 'TO COMPOSE', 'ТЕМ НЕ МЕНЕЕ/ВСЕ ЖЕ': 'NONETHELESS',
                  'ЛИ/БУДЬ ТО': 'WHETHER', 'НАПОМИНАЮЩИЙ': 'REMINISCENT', 'СЛЕГКА/ЧУТЬ/ЕДВА': 'SLIGHTLY',
                  'МУДРЕЙШИЙ': 'WISEST', 'ОБРАЗЕЦ/ПРИМЕР': 'INSTANCE', 'ХОЛОСТОЙ': 'CELIBATE',
                  'ДЕЙСТВИТЕЛЬНО/КОНЕЧНО': 'INDEED', 'ОСТАЛЬНОЙ': 'REMAINING', 'РЕГУЛИРОВАТЬ': 'TO ADJUST'
                  }

    vocabulary_update = {value: key for key, value in vocabulary.items()}

    print('Слов в словаре:', len(vocabulary))
    pickle.dump(vocabulary_update, file)
    file.close()


main()
