import pickle


def main():
    """
    Программа принимает и сохраняет новые английские слова в словарь.
    :return: None
    """
    # создадим словарь,куда будем сохранять слово/перевод и запишем в файл.
    file = open('/home/andrey/Studying/vocabulary/my_vocabulary2.dat', 'wb')
    vocabulary = {'ШТУКИ/ТЫСЯЧИ/ГРАНД': 'GRAND', 'СТАВКА/КУРС/КОЕФИЦИЕННТ': 'RATE',
                  'УСИЛИТЬ/АКТИВИЗИРОВАТЬ': 'TO STEP UP',
                  'ВРАЖДЕБНОСТЬ': 'HOSTILITY', 'ХАМСТВО': 'RUDENESS', 'ВЯЛЫЙ': 'FLACCID', 'ВЫПЕЧКА': 'PASTRY',
                  'ТЫ РАЗЫГРЫВАЕШЬ МЕНЯ?': 'ARE YOU SHITTING ME?', 'ПРЯМАЯ ЗАВИСИМОСТЬ': 'LINEAR CORRELATION',
                  'КОНТРОЛЬНЫЕ ПОКАЗАТЕЛИ': 'BENCHMARKS', 'НЕОБХОДИМЫЙ/СООТВЕТСТВУЮЩИЙ': 'RELEVANT',
                  'ПРОЦВЕТАТЬ': 'TO THRIVE',
                  'ПОДСЧИТАТЬ/ОПРЕДЕЛИТЬ КОЛИЧЕСТВО': 'TO QUANTIFY', 'НЕРЕШИТЕЛЬНЫЙ': 'HESITANT',
                  'ПРОИЗВОДИТЬ': 'TO MANUFACTURE',
                  'НАПРЯЖЕНИЕ/НАПРЯЖЕННОСТЬ': 'TENSION', 'ПОИСК ДАННЫХ': 'DATA RETRIEVAL',
                  'ОПТОВОЛОКОННЫЙ': 'FIBER-OPTIC',
                  'ВЗАИМОДЕЙСТВИЕ/СИНЕРГИЯ': 'SYNERGY', 'СВОРАЧИВАТЬСЯ/ЗАКРУГЛЯТЬСЯ': 'TO WRAP THIS UP',
                  'ТАЙНА/ЗАГАДКА': 'MYSTERY',
                  'НЕИЗМЕРЯЕМЫЙ': 'UNMEASURED', 'ПРОЦВЕТАНИЕ/БЛАГОПОЛУЧИЕ': 'PROSPERITY', 'НАЗНАЧАТЬ': 'TO DESIGNATE',
                  'ВЫБИТЬ/ВЫРУБИТЬ(ПР.ВЫРУБИТЬ ЭЛЕКТРИЧЕСТВО)': 'TO KNOCK OUT', 'КВАРТАЛЬНЫЙ': 'QUARTERLY',
                  'ПРОГНОЗЫ': 'PROJECTIONS',
                  'ВРАЩЕНИЕ': 'SPIN', 'ТЫ МОЖЕШЬ РАССЧИТЫВАТЬ НА МЕНЯ!': 'YOU CAN COUNT ON ME!',
                  'КОШЕРНАЯ ЕДА': 'KOSHER MEAL',
                  'АКЦИОНЕР': 'SHAREHOLDER', 'ИДЕИ/СООБРАЖЕНИЯ': 'INSIGHTS', 'РАЗВРАЩАТЬ/ИЗВРАЩАТЬ': 'TO PERVERT',
                  'РАСЧЕТ/ПОДСЧЕТ': 'ESTIMATION', 'МНЕ КАЖЕТСЯ...': 'METHINKS', 'КОПАТЬ': 'TO DIG',
                  'ДЖАКУЗИ': 'HOT TUB',
                  'КОПЫТА': 'HOOVES', 'ВЫХОДНОЕ ПОСОБИЕ': 'SEVERANCE', 'ФИНАНСОВЫЙ ДИРЕКТОР': 'CFO',
                  'ПРЕДЪЯВИТЬ ОБВИНЕНИЕ': 'TO INDICT',
                  'ГЕНЕРАЛЬНЫЙ ДИРЕКТОР': 'CEO', 'ЖЕРТВЫ/ЖЕРТВОПРИНОШЕНИЯ': 'SACRIFICES',
                  'В СЛЕДУЮЩИЙ РАЗ': 'RAIN CHECK!',
                  'ДАЙ ПЯТЬ!': 'UP HIGH!', 'ЛУЖАЙКА/ГАЗОН': 'LAWN', 'ИЗЫМАТЬ(ЗА НЕУПЛАТУ)': 'TO REPOSSESS',
                  'ПЕНСИЯ': 'PENSION',
                  'ПОХОРОНЫ': 'FUNERAL', 'НЕУВАЖИТЕЛЬНО': 'DISRESPECTFUL', 'ПОЛОВОЕ СОЗРЕВАНИЕ': 'PUBERTY',
                  'ОТОЙДИ!': 'BACK AWAY!',
                  'МНЕ СТЫДНО!': 'I AM ASHAMED!', 'ПРЕДСТАВЛЯТЬ(ЧЬИ-ТО ИНТЕРЕСЫ)': 'TO REPRESENT',
                  'ПРЕДАННОСТЬ': 'DEVOTION',
                  'СКЛОНИТЬ/ПОКЛОНИТЬСЯ': 'TO BOW', 'ВОЗДУШНЫЙ ЗМЕЙ': 'KITE', 'СЛИШКОМ': 'OVERLY', 'ВИЛКА': 'FORK',
                  'МОТЫЛЬКИ/МОЛЬ': 'MOTHS', 'КАЧЕЛИ': 'PORCH SWING', 'ПЬЯНЫЙ': 'WASTED', 'МЯСНОЙ РУЛЕТ': 'MEAT LOAF',
                  'КРАН/СМЕСИТЕЛЬ': 'FAUCET', 'ВОДА ИЗ-ПОД КРАНА': 'TAP WATER', 'РАСПРОСТРАНЕНИЕ': 'SPREAD',
                  'РАЗВЕЯТЬ': 'TO SCATTER',
                  'ИЗОБРАЖАТЬ': 'TO DEPICT', 'ЧИСТИТЬ(ПР.ОТ КОЖУРЫ БАНАН)': 'TO PEEL', 'СКОРЕЕ': 'RATHER',
                  'ЖЕЛУДИ': 'ACORNS',
                  'ХЛОПЬЯ': 'CEREAL', 'СВЕЧИ ЗАЖИГАНИЯ': 'SPARK PLUGS', 'СМЕНА': 'SHIFT', 'ПРОКЛАДКА/САЛЬНИК': 'GASKET',
                  'ЛОСОСЬ': 'SALMON', 'БЕСПОРЯДОК': 'MESS', 'ПЕРЕХОДНИК': 'ADAPTER', 'АККУРАТНО/ОПРЯТНО': 'NEATLY',
                  'ОГРОМНЫЕ ДЕНЬГИ/СОСТОЯНИЕ': 'FORTUNE', 'БАГАЖ': 'LUGGAGE',
                  'ПРИНЦИП ЕДИНСТВЕННОЙ ОТВЕТСТВЕННОСТИ': 'SINGLE RESPONSIBILITY PRINCIPLE',
                  'ПРИНЦИП ОТКРЫТОСТИ/ЗАКРЫТОСТИ': 'OPEN-CLOSED PRINCIPLE',
                  'ПРИНЦИП ПОДСТАНОВКИ ЛИСКОВ': 'LISKOV SUBSTITUTION PRINCIPLE',
                  'ПРИНЦИП РАЗДЕЛЕНИЯ ИНТЕРФЕЙСА': 'INTERFACE SEGREGATION PRINCIPLE',
                  'ПРИНЦИП ИНВЕРСИИ ЗАВИСИМОСТЕЙ': 'DEPENDENCY INVERSION PRINCIPLE',
                  'ЛЕСТНИЦА': 'LADDER', 'УЕБАНСКИЙ/УЕБИЩЕ': 'FUGLY', 'СОПЛИВЫЙ': 'SNOTTY', 'РУК ДЕЛО': 'HANDIWORK',
                  'СКОВОРОДКА': 'FRYING PAN', 'ЛОТЕРЕЯ': 'RAFFLE', 'ПРИЕМНАЯ СЕМЬЯ': 'FOSTER FAMILY',
                  'ПРИТВОРЯТЬСЯ': 'TO PRETEND',
                  'ЛАСТЫ': 'FLIPPERS', 'СЧАСТЛИВАЯ СЛУЧАЙНОСТЬ': 'FLUKE', 'ЛЫСЫЙ': 'BALD',
                  'ХВАТИТ НЕСТИ ЧУШЬ!': 'CUT THE CRAP!',
                  'ДРЯХЛЫЙ/МОРЩИНИСТЫЙ': 'WRINKLY', 'МЕРЗОСТЬ/ГАДОСТЬ': 'GROSS', 'ФАЛЬШИВЫЙ': 'BOGUS',
                  'ГОРЧИЦА': 'MUSTARD',
                  'ВОСХОЖДЕНИЕ': 'ASCENT', 'ЗАЯВЛЕНИЕ': 'STATEMENT', 'УНАСЛЕДОВАТЬ': 'TO INHERIT', 'ФАРТУК': 'APRON',
                  'ОБМАНУТЬ': 'TO TRICK', 'СКРИПКА': 'FIDDLE', 'БОЛЬНОЕ ГОРЛО': 'STREP THROAT', 'ОБВИСАТЬ': 'TO SAG',
                  'МУСОРНЫЙ БАК': 'DUMPSTER', 'НАСЛЕДНИК': 'HEIR', 'ПОДКРАДАТЬСЯ': 'TO SNUCK UP', 'МЕШОК': 'SACK',
                  'МЯСНИК': 'BUTCHER', 'РЕМОНТ': 'REPAIR', 'ГРЕТЬСЯ': 'TO BASK', 'ВЗНОС/ВКЛАД': 'CONTRIBUTION',
                  'ВЕРАНДА': 'PORCH',
                  'СТРАННО/СТРАННЫЙ': 'ODD', 'ЗАГАР': 'TAN', 'ТРУП': 'CORPSE', 'ЭГОИЗМ': 'SELFISHNESS',
                  'ИГЛА': 'NEEDLE',
                  'БОГОСЛУЖЕНИЕ': 'WORSHIP', 'Я ПОТРЯСЕН!': 'I AM STUNNED!', 'СОЖИТЕЛЬСТВОВАТЬ': 'TO SHACK UP',
                  'ФОРЕЛЬ': 'TROUT', 'ИСКРЕННИЙ': 'SINCERE', 'ПИТОМНИК': 'KENNEL', 'ВПАДАТЬ В СПЯЧКУ': 'TO HIBERNATE',
                  'ПОТОМ/ПОСЛЕ': 'AFTERWARDS', 'РАЗВЕДКА': 'RECON', 'НОВОСЕЛЬЕ': 'HOUSEWARMING', 'ВРЕД/УЩЕРБ': 'HARM',
                  'ОБИДА': 'RESENTMENT', 'НАОБОРОТ': 'CONVERSELY', 'НЕВЫНОСИМЫЙ': 'OBNOXIOUS', 'БАНКИ/КАНИСТРЫ': 'CANS',
                  'ПРОБЕГ': 'MILEAGE', 'ДИАПАЗОН/РЯД': 'RANGE', 'ГИЕНА': 'HYENA', 'ИЗМЕНЯТЬ': 'TO CHEAT',
                  'НАМАТЫВАТЬ(КАТУШКУ)': 'TO REEL',
                  'СРАТЬ': 'TO POO', 'КУРОРТ': 'RESORT', 'ОТРЫВАТЬСЯ/ПРОВОДИТЬ ВРЕМЯ': 'TO LIVE IT UP',
                  'ЭЛЕКТРОСТАНЦИИЯ/ЛОКОМОТИВ': 'POWERHOUSE',
                  'КУХНЯ(ЛОКАЛЬНАЯ)': 'CUISINE', 'НОЧНОЙ КОШМАР': 'NIGHTMARE', 'РЕЗУЛЬТАТИВНОСТЬ': 'EFFICIENCY',
                  'НЫТЬ': 'TO BITCH',
                  'СТРОКА/РЯД': 'ROW', 'СДЕРЖИВАТЬСЯ': 'TO HELD BACK', 'НИКОГДА НЕ СДАВАЙСЯ!': 'NEVER BACK DOWN!',
                  'ЯГОДЫ': 'BERRIES', 'КЛАДБИЩЕ': 'CEMETERY', 'БОГАТСТВО/СОСТОЯНИЕ': 'WEALTH',
                  'НЕЗАМЕНИМЫЙ': 'INDISPENSABLE',
                  'МОЗОЛЬ': 'CALLUS', 'ОТПЕЧАТКИ ПАЛЬЦЕВ': 'FINGERPRINTS', 'КОЛЬЦО': 'RIM',
                  'СТРОИТЕЛЬ': 'CONSTRUCTION WORKER',
                  'ЖУЛЬНИЧЕСТВО': 'HUSTLE', 'ДУБ': 'OAK TREE', 'РАКЕТА': 'MISSILE', 'ЕДИНОРОГ': 'UNICORN',
                  'МЕСТО В СОСТАВЕ': 'ROSTER SPOT', 'БУНТ/МЯТЕЖ': 'RIOT', 'ОТМЕНЕНО/ОТМЕНЕНЫ': 'REVOKED',
                  'ПРОБА/ПОПЫТКА': 'TRYOUT',
                  'Я В ВОСТОРГЕ!': 'I AM THRILLED!', 'АРЕНДОДАТЕЛЬ/ДОМОВЛАДЕЛЕЦ': 'LANDLORD',
                  'ПРОВОКАЦИЯ': 'ENTRAPMENT',
                  'ЭКСКЛЮЗИВНЫЙ/ВЫСОКОКЛАССНЫЙ': 'UPSCALE', 'БЛАГОТВОРИТЕЛЬНОСТЬ': 'CHARITY',
                  'ОБЕСПЕЧЕННЫЙ': 'WELL-OFF',
                  'КЛЮЧИЦА': 'COLLARBONE', 'ЭКИПИРОВКА': 'GEAR', 'БУЛОЧКИ': 'BUNS', 'СУДЬБА/УЧАСТЬ': 'FATE',
                  'ОБРУЧАЛЬНОЕ КОЛЬЦО': 'PROMISE RING',
                  'НАРЯД/КОСТЮМ': 'OUTFIT', 'МЕЛКИЕ РАСХОДЫ/НЕПРЕДВИДЕННЫЕ РАСХОДЫ': 'INCIDENTALS',
                  'СОМНЕНИЯ': 'QUALMS',
                  'УБОГИЙ': 'SHABBY', 'ПОЛАГАЮ/ПРЕДПОЛОГИЮ': 'PRESUME', 'УКАЗ/ПОСТАНОВЛЕНИЕ': 'DECREE',
                  'ПРОЩАЛЬНЫЙ(ПР.КОНЦЕРТ)': 'FAREWELL',
                  'ОБЛОМ': 'BUMMER', 'ИСПОРЧЕННЫЙ/ЗАРАЖЕННЫЙ': 'TAINTED', 'СДЕЛАЙ ПАУЗУ!': 'PINCH IT OFF!',
                  'БРАКОНЬЕР': 'POACHER',
                  'ЩЕДРОСТЬ': 'BOUNTY', 'МРАЧНЫЙ': 'GLOOMY', 'ЛЕСОПИЛКА': 'SAWMILL', 'ЛОБКОВЫЙ ВОЛОС': 'PUBE',
                  'ПРИДУРКИ': 'DORKS',
                  'БАБНИК/ДОНЖУАН': 'PHILANDERER', 'НЕВИННЫЙ/БЕЗВИННЫЙ': 'INNOCENT', 'ЩЕЛЬ': 'CHINK',
                  'ПОДКЛЮЧАТЬ': 'TO PLUG',
                  'ПОЗВОЛЯТЬ СЕБЕ': 'TO AFFORD', 'КОРОЛЕВСКИЙ/ЦАРСКИЙ': 'ROYAL', 'ПООБЩАТЬСЯ': 'TO MINGLE',
                  'РАЗДОБЫТЬ': 'TO RUSTLE UP',
                  'ПРОКОЛОТЬ': 'TO IMPALE', 'ВТОРЖЕНИЕ': 'INVASION', 'ВЫСКОЧКА': 'JUMPED-UP', 'НАСТАИВАТЬ': 'TO INSIST',
                  'КУЧЕРЯВЫЙ': 'CURLY', 'ШАХТА': 'SHAFT', 'КРОМЕШНАЯ ТЬМА': 'PITCH BLACK', 'ШИНА/ПОКРЫШКА': 'TYRE',
                  'РУЛЬ/КОЛЕСО': 'WHEEL',
                  'НЕУДОБСТВО/НЕПРИЯТНОСТЬ': 'NUISANCE', 'МЕТКО': 'APTLY', 'ЖИЗНЕННО ВАЖНЫЙ': 'VITAL',
                  'ПЕРЕХЕТРИТЬ': 'TO OUTWIT',
                  'ЗЛОДЕЙ': 'VILLAIN', 'ЦИКЛ': 'LOOP', 'ЭКЗЕМПЛЯР КЛАССА': 'INSTANCE OFF A CLASS', 'СХВАТКА': 'SCRUM',
                  'ОРАТЬ': 'TO YELL', 'МНЕ ТОЖЕ': 'ME EITHER', 'КОНФИСКОВАТЬ/ИЗЫМАТЬ': 'TO SEIZE',
                  'МГНОВЕННО': 'MOMENTARILY',
                  'ПРЕЛЮДИЯ': 'FOREPLAY', 'ВОСХИЩЕНИЕ': 'ADMIRATION', 'ПОМЕСТЬЕ': 'ESTATE',
                  'ДОВЕРЕННОЕ ЛИЦО': 'TRUSTEE',
                  'ЛЕКАРСТВО ПО РЕЦЕПТУ': 'PRESCRIPTION MEDICATION', 'СОРТИРОВКА СЛИЯНИЕМ': 'MERGE SORT',
                  'ПОИСК В ШИРИНУ': 'BREADTH FIRST SEARCH', 'СОРТИРОВКА ПУЗЫРЬКОМ': 'BUBBLE SORT',
                  'МАЛИНА': 'RASPBERRY',
                  'ЭМОЦИОНАЛЬНЫЕ ВСПЛЕСКИ': 'EMOTIONAL OUTBURSTS', 'ВИНИТЬ': 'TO BLAME', 'САМЫЙ СМЕЛЫЙ': 'BOLDEST',
                  'НЕУЛОВИМЫЙ': 'ELUSIVE', 'СРАЗУ ЖЕ': 'RIGHT AWAY', 'НЕТЕРПИТСЯ': 'CHOMPING AT THE BIT',
                  'ДЕРЗКИЙ': 'BRASH',
                  'МАТРАС': 'FUTON', 'БОСОЙ': 'BAREFOOT', 'ТОЧНЫЙ/ЧЕТКИЙ': 'PRECISE', 'ДРОЖЬ/ТРЕПЕТ': 'TINGLE',
                  'УГОЛЬ': 'COAL',
                  'НАЧИНКИ': 'TOPPINGS', 'СТОНАТЬ/КРЯХТЕТЬ': 'TO GROAN', 'ЛИМУЗИН': 'LIMO', 'ЭВАКУАТОР': 'TOW TRUCK',
                  'СНЕГОУБОРОЧНАЯ МАШИНА': 'SNOWPLOW', 'СЛУГА': 'VALET', 'ВРОЖДЕННЫЙ/ПРИРОДНЫЙ': 'INNATE',
                  'ПОДАВЛЯТЬ': 'TO SQUASH',
                  'СИГАРЕТКУ МОЖНО?': 'CAN I BUM A SMOKE?', 'ЛЕГКИЕ': 'LUNGS', 'ФРИЦ': 'KRAUT',
                  'НЕНОРМАТИВНАЯ ЛЕКСИКА': 'PROFANITY',
                  'КЛИЧКА': 'MONIKER', 'МАКАРОННИК': 'GREASEBALL', 'РОСКОШНЫЙ': 'RITZY',
                  'ЛАДИТЬ\УЖИВАТЬСЯ': 'GET ALONG',
                  'ЖИР': 'GREASE', 'СМЕТЬ': 'TO DARE', 'МОГУЧИЙ': 'MIGHTY', 'НЕБОЛЬШОЙ ПЕРЕРЫВ': 'BRIEF INTERMISSION',
                  'РАВНИНА': 'PLAIN', 'ОСТРЫЙ': 'SHARP', 'ДАВАТЬ ВЗЯТКУ': 'TO BRIBE', 'ФАЛЬШИВЫЙ/ПОДДЕЛЬНЫЙ': 'PHONY',
                  'БАКЛАЖАН': 'EGGPLANT', 'УСТРАИВАТЬ/ПРИСТРАИВАТЬ': 'TO ARRANGE', 'НАСИЛИЕ/ЖЕСТОКОСТЬ': 'VIOLENCE',
                  'ЧУВСТВО СОБСТВЕННОГО ДОСТОИНСТВА': 'DIGNITY', 'ПРЕОБЛАДАТЬ/ДОМИНИРОВАТЬ': 'TO PREVAIL',
                  'ГУБЕРНАТОР': 'GOVERNOR',
                  'ПРИТОРМОЗИ!': 'PULL OVER!', 'СТРАДАТЬ': 'TO SUFFER', 'ПОЧТОВАЯ МАРКА': 'STAMP',
                  'КАШЛЯТЬ': 'TO COUGH',
                  'ПЕРЕМИРИЕ': 'TRUCE', 'ПАЧКА(ПР.НАЛИЧНЫХ)': 'WAD', 'СОКРОВИЩЕ': 'TREASURE', 'БОЧКА': 'BARREL',
                  'УТЕШЕНИЕ': 'CONSOLATION',
                  'ВЗЛОМ': 'BREACH', 'ОРДЕР': 'WARRANT', 'ПРЕДУСМОТРИТЕЛЬНОСТЬ': 'PRUDENCE', 'НАРАЩИВАТЬ': 'TO RAMP UP',
                  'ПРИГОРОДНЫЙ': 'COMMUTER', 'ПРЕНЕБРЕЖИТЕЛЬНЫЙ': 'DISMISSIVE', 'СИБИРСКАЯ ЯЗВА': 'ANTHRAX',
                  'ЗАГРУЖАТЬ/ЗАКАЧИВАТЬ': 'TO UPLOAD',
                  'ИЗБАВИТЬСЯ': 'TO GET RID', 'ОСУЩЕСТВЛЯТЬ/РЕАЛИЗОВЫВАТЬ': 'TO IMPLEMENT', 'ПЛЯТЕЖ': 'PAYMENT',
                  'ИПОТЕКА': 'MORTGAGE', 'ВЗЛАМЫВАТЬ': 'TO CRACK', 'ВРУЧНУЮ': 'MANUALLY',
                  'ПРОТЯНУТЬ РУКУ ПОМОЩИ': 'LEND A HAND',
                  'ИЗМЕНЯЕМЫЕ ТИПЫ ДАННЫХ': 'MUTABLE DATA TYPES', 'НЕИЗМЕНЯЕМЫЕ ТИПЫ ДАННЫХ': 'IMMUTABLE DATA TYPES',
                  'ОБРАБОТКА ИСКЛЮЧЕНИЙ': 'EXCEPTION HANDLING', 'НАСЛЕДОВАНИЕ КЛАССОВ': 'CLASS INHERITANCE',
                  'ИНКАПСУЛЯЦИЯ': 'ENCAPSULATION', 'ООП': 'OBJECT-ORIENTED PROGRAMMING',
                  'СИСТЕМА КОНТРОЛЯ ВЕРСИЙ': 'VERSION CONTROL SYSTEM',
                  'ВЕТКА': 'BRANCH', 'УДАЛЕННЫЙ': 'REMOTE', 'ОГРАЮЛЕНИЕ': 'HEIST', 'МЕСТЬ': 'REVENGE',
                  'КЛАПАН': 'VALVE',
                  'РАЯДОМ С ': 'ALONGSIDE', 'ПЕРЕКЛЮЧИТЬ/ПЕРЕЙТИ': 'TO SWITCH', 'УПРЯМЫЙ': 'STUBBORN',
                  'РАЙОН': 'BOROUGH',
                  'КРЫЛЬЦО': 'STOOP', 'НАЗЛО': 'FOR SPITE', 'КАРТЕЖНИК/АЗАРТНЫЙ ИГРОК': 'GAMBLER',
                  'ОСКОРБЛЕНИЕ': 'OFFENSIVE',
                  'ЧЕРТА(ПР.ТВОЯ ЧЕРТА)': 'TRAIT', 'МЯТЕЖ': 'MUTINY', 'ЖАЛОВАТЬСЯ': 'TO COMPLAIN',
                  'ХОТЯ И...': 'ALBEIT',









                  'ФОЛЬГА': 'TINFOIL', 'ЖАЖДАТЬ/ТРЕБОВАТЬ': 'TO CRAVE', 'ИЗВЕСТНЫЙ/ЗНАМЕНИТЫЙ': 'RENOWNED',
                  'НЕНАВИСТЬ':'HATREDS','РАСТВОРЯТЬСЯ':'TO DISSOLVE','МАЛОЛЕТНИЙ ПРЕСТУПНИК':'JUVIE',
                  'ЗАКРЫТИЕ / ПРЕКРАЩЕНИЕ ПРЕНИЙ':'CLOSURE','БОДРЫЙ/ВЕСЕЛЫЙ':'CHIPPER','ДРАТЬСЯ':'TO STRUGGLE',
                  'ЗАТОЧКА':'SHIV','ГЛАЗУРЬ':'FROSTING','ТРАХАТЬ':'TO HUMP','КРОВЯНАЯ КОЛБАСА':'BLOOD PUDDING',
                  'СПАРИВАНИЕ/СЛУЧКА':'MATING','ИСКОПАЕМЫЙ':'FOSSIL','ПОТЕНЦИАЛ/СПОСОБНОСТЬ':'CAPACITY',
                  'ВЕЧНАЯ ЖИЗНЬ':'EVERLASTING LIFE','ПОЕСТЬ И СМЫТЬСЯ':'DINE AND DASH',
                  'ВОЗМЕЗДИЕ/РАСПЛАТА':'RETRIBUTION','ДАВАТЬ ПРАВО..':'TO ENTITLE TO...','ПРИХОТЬ/ПРИЧУДА':'WHIMSY',
                  'СДАВАТЬ В АРЕНДУ':'TO LEASE OUT','ЗАЖИГАТЬ/ЗАЖЕЧЬ(ТУСОВКА)':'TO SPARK UP',
                  'ТЕКУЩИЙ/ПОСТОЯННЫЙ':'ONGOING','НАЧАТЬ С НАЧАЛА':'START OVER',
                  'ЖИДКИЙ МЕТАЛ':'LIQUID METAL','ПЕРЕЙТИ К ДЕЛУ':'TO CUT TO THE CHASE',
                  'ГУЛЯТЬ':'TO STROLL','ПАХАТЬ':'TO PLOW','ГОЛЫЙ ПО ПОЯС':'SHIRTLESS','РОГАЛИКИ':'BAGELS',
                  'ТЩЕСЛАВИЕ/СВМОЛЮБИЕ':'VANITY','ПЕЧЬ(ЗАВОДСКАЯ)':'FURNACE','РЕБРЫШКИ':'PRIME RIB',
                  'САХАРОЗАМЕНИТЕЛЬ':'SPLENDA','РАЗНООБРАЗИЕ':'DIVERSITY','ПАРИТЬ/ВИТАТЬ':'TO HOVER',
                  'СВОДКА/КРАТКОЕ ИЗЛОЖЕНИЕ':'RUNDOWN','БОРДЕЛЬ':'BROTHEL','РУКАВА':'SLEEVES',
                  'ГЛАВНЫЙ/ЗАВЕДУЮЩИЙ':'IN CHARGE','ЧИСТИТЬ':'TO PURGE','РАСКРЫТЬ(ПОТЕНЦИАЛ)':'TO UNLEASH','НАВОЗ':'MANURE',
                  'ПОЧВА':'SOIL','ПОНЧИКИ':'DONUTS','ВОСПРИИМЧИВЫЙ':'RECEPTIVE','ВЫКУП':'BUYOUT',
                  'ОАСКРЫВАТЬ(ДЕТАЛИ)':'TO REVEAL','ЗАГЛЯНУТЬ ВНУТРЬ СЕБЯ':'TO LOOK INWARD','ПРЕДВЗЯТЫЙ':'BIASED',
                  'ПЛЮСЫ':'PROS','МИНУСЫ':'CONS','СРЕДСТВО/ЛЕКАРСТВО':'REMEDY','ГРЕМУЧАЯ ЗМЕЯ':'RATTLER',
                  'МОЛОЧНАЯ КИСЛОТА':'LACTIC ACID','ИЗВИВАТЬСЯ':'TO SQUIRM','ТЫКАТЬ':'TO POKE',
                  'БРОДЯГИ':'TRAMP','ПРИСТАВАТЬ/ДОСТАВАТЬ':'PESTERING',
                  'УЧЕНИК':'APPRENTICE', 'ОГРОМНЫЙ':'VAST','УНИЧТОЖЕНИЕ/ИСТРЕБЛЕНИЕ':'EXTERMINATION','АНГАР':'HANGAR',
                  'ПРОПАСТЬ':'PRECIPICE','ДО ТЕХ ПОР ПОКА':'AS LONG AS','САЛЬТО':'BACKFLIP',
                  'СЕТИ ПРЯМОГО РАСПРОСТРАНЕНИЯ':'FEEDFORWARD NETWORKS','ГИБКИЙ/ЭЛАСТИЧНЫЙ':'FLEXIBLE',
                  'АКТИВЫ':'ASSETS','ПРИНИМАТЬ УЧАСТИЕ':'TO PARTICIPATE','РЕГУЛИРУЕМЫЙ':'ADJUSTABLE',
                  'ВСТРАИВАТЬ':'TO EMBED','ПОСЛЕДОВАТЕЛЬНОСТЬ/ЦЕПОЧКА':'SEQUENCE',
                  'МАТРИЧНОЕ УМНОЖЕНИЕ':'MATRIX MULTIPLICATION','ПРЕОБРАЗОВЫВАТЬ':'TO CONVERT','ПЕРЕОБУЧЕНИЕ':'RETRAINING',
                  'РАСПОЗНОВАНИЕ ОБЪЕКТОВ':'OBJECT RECOGNITION','Я НЕ ПОНИМАЮ':'I DONT GET IT','СЖИМАТЬ':'TO CLENCH',
                  'ЯГОДИЦЫ':'BUTTOCKS','ПРОБЛЕМА С ПОВЕДЕНИЕМ':'ATTITUDE PROBLEM','ШТАБ-КВАРТИРА':'HEADQUARTER',
                  'ЛУЧШИЙ ВЫПУСКНИК':'VALEDICTORIAN','САРДЕЛЬКА':'WIENER','НЕДООЦЕНЕННЫЙ':'UNDERRATED','ВЫПУСКНОЙ ВЕЧЕР':'PROM',
                  'УМНИК':'WISENHEIMER','УХМЫЛКА':'GRIN','ОБОСРАТЬСЯ':'TO SHIT YOURSELF','КРОВОТЕЧЕНИЕ':'BLEEDER',
                  'СЫЩИК':'INVESTIGATOR','ССЫКУН':'PISSER','АЛКАШ':'ALKY','БУХЛО':'BOOZE',
                  'УТВЕРДИТЕЛЬНЫЙ/ПОЛОЖИТЕЛЬНЫЙ':'AFFIRMATIVE','КАБАК':'GIN MILL','РЕВ/ГУЛ/ГРОХОТ':'ROAR',
                  'ГРАБИТЬ':'TO PILFER','КУРЯТНИК':'HENHOUSE','ЧЕЛЮСТЬ':'JAW','НЕЧЕСТНАЯ ИГРА':'UNFAIR GAME',
                  'ПОЧИК':'KIDNEYS','ВЕРА':'FAITH','ПЛЕМЯННИК':'NEPHEW','МНЕ ГЛУБОКО НАПЛЕВАТЬ':'I DONT GIVE A RATS ASS',
                  'СРЕДНЕВЕКОВЬЕ':'MEDIEVAL','ПРОКАЖЕННЫЙ':'LAPER','СТИПЕНДИЯ':'SCHOLARSHIP',
                  '(ЧТО-ТО/КТО=ТО)УПУСКАЮТСЯ ИЗ ВИДУ ':'OVERLOOKED FOR','ОЧЕВИДНЫЕ НЕДОСТАТКИ':'PERCEIVED FLAWS',
                  'ВНЕШНОСТЬ':'APPEARANCE','НАПЛЕВАТЬ':'TO GIVE A SHIT','БЛИЗОСТЬ(ПР.К ОКЕАНУ)':'PROXIMITY',
                  'ИСТЕКАТЬ/ЗАКАНЧИВАТЬСЯ':'TO EXPIRE','КОНТЕЙНЕРЫ':'BINS','СРЕДНИЙ/УСРЕДНЕННЫЙ':'MEDIAN',
                  'ПЕРЕСТАНОВКА':'PERMUTATION','ТРОТУАР':'SIDEWALK','ИССЛЕДОВАНИЕ':'RESEARCHING','ВОРЧЛИВЫЙ':'GROUCHY',
                  'ВОЛОСАТЫЙ':'HAIRY','ИСКРЕВЛЕНИЕ НОСОВОЙ ПЕРЕГОРОДКИ':'DEVIATED SEPTUM','СОВЕТ':'TIP','В ЛЮБОЕ ВРЕМЯ':'WHENEVER',
                  'НИ С ТОГО НИ С СЕГО':'APROPOS OF NOTHING','РЫДАТЬ':'TO SOB','НОМЕРНОЙ ЗНАК(АВТО)':'LICENSE PLATE',
                  'УГЛЕВОДЫ':'CARBS','ШЛЮПКА':'SKIFF','ГОРШОК(ТУАЛЕТ)':'POTTY','РАСЦВЕТАТЬ/ЦВЕСТИ':'TO BLOOM',
                  'УТОЧНЯТЬ/ПРОЯСНЯТЬ':'TO CLARIFY','БЛЮДЕЧКО':'SAUCER','ТЕМА':'SUBJECT','ЖАРКОЕ В ГОРШОЧКЕ':'POT ROAST',
                  'НЕДОВАРЕННОЕ/НЕДОЖАРЕННОЕ':'UNDERCOOKED','ДОЛГАЯ КРАТКОСРОЧНАЯ ПАМЯТЬ':'LONG SHORT-TERM MEMORY',
                  'ЖМОТ':'MISER','УПРАВЛЯЕМЫЕ РЕКУРЕНТНЫЕ БЛОКИ':'GATED RECURRENT UNITS',
                  'ОПРОС КЛИЕНТОВ': 'CUSTOMER SURVEYS', 'СМУГЛЫЙ': 'DUSKY', 'ЭКСКАВАТОР': 'DIGGER',
                  'АБРАЗИВНЫЙ/РЕЗКИЙ': 'ABRASIVE', 'НЕПРИЯТНЫЙ': 'DISTASTEFUL', 'КРУЖКА/ЧАШКА': 'MUG',
                  'БОРМОТАТЬ/МЯМЛИТЬ': 'TO MUMBLE', 'ОЧАРОВАНИЕ': 'CHARM', 'ВЫСОКОМЕРНЫЙ': 'ARROGANT',
                  'ВРАЖДЕБНЫЙ': 'HOSTILE', 'ГРАНИЦЫ/РАМКИ': 'BOUNDARIES', 'БОМЖ': 'HOBO',
                  'ПЕРЕВЕРНУТЬСЯ': 'TO ROLL OVER', 'УГОЛОК/ЗАКУТОК': 'NOOK', 'НЕКОТОРОЕ ВРЕМЯ': 'FOR WHILE',
                  'СОВЕРШИТЬ БОЛЬШОЙ СКАЧОК': 'TO TAKE A BIG LEAP', 'НЕ ПОКЛАДАЯ РУК': 'TIRELESSLY',
                  'НАВЯЗЧИВЫЙ': 'INTRUSIVE', 'СУТОЧНЫЕ': 'PER DIEM', 'ГЛОТОК': 'SIP', 'ВЗДРЕМНУТЬ': 'TO NAP',
                  'КРАСОВАТЬСЯ/ВЫСТАВЛЯТЬ НА ПОКАЗ': 'TO FLAUNT', 'ОПЬЯНЯЮЩИЙ': 'INTOXICATING',
                  'РАЗВЕДАТЬ': 'TO SCOPE OUT', 'СОКРАЩАТЬСЯ': 'TO SHRINK',
                  'ТРЯПОЧКА/ТРЯПКА': 'RAG', 'ВСПЛЕСК/ВОЛНА': 'SURGE', 'ПОДГОТОВЛЕННОСТЬ/ГОТОВНОСТЬ': 'PREPAREDNESS',
                  'В ЯРОСТИ/ВНЕ СЕБЯ': 'LIVID', 'РАЗВЛЕКАТЬ/ВЕСЕЛИТЬ': 'TO AMUSE',
                  'ВЗЯТЬ НА СЕБЯ/ЗАВЛАДЕТЬ': 'TO TAKE OVER',
                  'ХОРОНИТЬ': 'TO BURY', 'БОЛЬШОЙ АЖИОТАЖ': 'A LOT OF BUZZ', 'ЛУГ': 'MEADOW', 'ЖАРЕННЫЙ': 'ROAST',
                  'КАРЛИК': 'MIDGET', 'ГОЛЫЕ СИСЬКИ': 'BARE BOOBS', 'ВНЕ/ЗА ПРЕДЕЛОМ': 'BEYOUND',
                  'НА ЗАДНЕМ ПЛАНЕ': 'ALL THE WAY IN THE BACK', 'НАБРОСАТЬ/ЗАПИСАТЬ': 'TO JOT DOWN',
                  'СОСУЛЬКА': 'ICICLE',
                  'ВОПРОС ВРЕМЕНИ': 'MATTER OF TIME', 'ВОНЯТЬ': 'TO REEK', 'ПРОНИЦАТЕЛЬНЫЙ': 'INSIGHTFUL',
                  'СУРОВЫЙ/ЖЕСТКИЙ': 'HARSH',
                  'ТРАВЫ': 'HERBS', 'САНИ/САНКИ': 'TOBOGGAN', 'ОТЧАЯНИЕ/БЕЗЫСХОДНОСТЬ': 'DESPAIR',
                  'ИБМИЦИЛ': 'IMBECILE',
                  'ВОСКЛИЦАТЕЛЬНЫЙ ЗНАК': 'EXCLAMATION POINT', 'ОСКОРБИТЕЛЬНО': 'INSULTING',
                  'ААКЦЕНТ/УПОР/ОСОБОЕ ВНИМАНИЕ': 'EMPHASIS',
                  'ПОСЛЕДСТВИЯ': 'CONSEQUENCES', 'ГОРАЗДНО/ЗНАЧИТЕЛЬНО': 'VASTLY',
                  'СУДЕБНЫЙ ПРОЦЕСС': 'LAWSUIT', 'ИСПЫТАТЕЛЬНЫЙ СТРОК': 'PROBATION', 'СТОЛ/ПИСЬМЕННЫЙ СТОЛ': 'DESK',
                  'ХОЛСТ/ПОЛОТНО': 'CANVAS', 'ЗАМАНИВАТЬ': 'TO LURE',
                  'БУДЬ ЗДОРОВ!': 'BLESS YOU!', 'ФИНАНСОВЫЙ ГОД': 'FISCAL YEAR', 'ЯРМАРКА ТРУДА(ВАКАНСИЙ)': 'JOB FAIR',
                  'САМОЗВАНЕЦ': 'IMPOSTER', 'ГАРНИТУРА': 'HEADSET',
                  'ЛИГА ПЛЮЩА': 'IVY LEAGUE', 'СВИДЕТЕЛЬ': 'WITNESS',
                  'НАВЫКИ ПОНИМАНИЯ': 'COMPREHENSION SKILLS',
                  'ПОЛНОЕ ПРАВО/ВСЕ ПОЛНОМОЧИЯ': 'FULL AUTHORITY',
                  'ОРГАНИЗАЦИОННАЯ СТРУКТУРА': 'ORG CHART', 'ЩЕКОТАТЬ': 'TO TICKLE',
                  'НЕ ТРЕБУЮЩЕЕ ОБЪЯСНЕНИЙ': 'SELF-EXPLANATORY',
                  'ЦЕМЕНТ': 'CEMENT', 'МЕЧТА ВСЕЙ ЖИЗНИ': 'LIFELONG DREAM', 'ИНИЦИАЛЫ': 'INITIALS',
                  'УВЕКОВЕЧИТЬ': 'TO IMMORTALIZE', 'ПРИЛАГАТЕЛЬНОЕ': 'ADJECTIVE', 'ЧТОБЫ/ДЛЯ ТОГО': 'IN ORDER',
                  'ЗАРЯЖАТЬ ЭНЕРГИЕЙ': 'TO ENERGIZE', 'ПРОСАЧИВАТЬСЯ': 'TO PRECOLATE', 'ЗАИКАТЬСЯ': 'TO STUTTER',
                  'НАХАЛЬНЫЙ': 'SASSY', 'ЦАРАПИНА': 'SCRATCH', 'АВТОМОБИЛЬ-УНИВЕРСАЛ': 'WAGON',
                  'ЗЕВАТЬ': 'TO YAWN', 'ПОЯС ВЕРНОСТИ': 'CHASTITY BELT', 'С ДРУГОЙ СТОРОНЫ..': 'ON THE FLIP SIDE',
                  'БДИТЕЛЬНЫЙ': 'VIGILANT', 'ДЕЖУРНЫЙ': 'HALL MONITOR', 'ЗАПИХИВАТЬ/ЗАСОВЫВАТЬ': 'TO STUFF',
                  'ИСКЛЮЧАТЬ': 'TO PRECLUDE', 'ШЕЙКА МАТКИ': 'CERVIX', 'СПЕЛЫЙ': 'RIPE', 'ЗАБЛУЖДЕНИЕ': 'DELUSION',
                  'ВЫБОИНЫ': 'POTHOLES', 'ОБЕЗБОЛИТЬ(ВВЕСТИ МЕСТНЫЙ НАРКОЗ)': 'TO NUMB UP', 'АИСТ': 'STORK',
                  'СВЕРТОЧНЫЕ НС': 'CONVOLUTIONAL NEURAL NETWORKS',
                  'ЗАВОЕВЫВАТЬ':'TO CONQUER','ПЛАКАТЬ/ПЛАКАЛ':'TO WEEP \ TO WEPT','ТОЧНОСТЬ/АККУРАТНОСТЬ':'EXACTNESS',
                  'ПРОТИВОПОЛОЖНЫЙ/ОБРАТНОЕ':'CONTRARY','ОБЛИГАЦИИ НА ПРЕДЪЯВИТЕЛЯ':'BEARER BONDS',
                  'СЕЙФ':'VAULT','ПРЕДСЕДАТЕЛЬ/ГЛАВА':'CHAIRMAN','МЕНЯТЬ/ИЗМЕНЯТЬ(ЧТО-ТО)':'TO ALTER',
                  'ТРАНСЛИРОВАТЬ/ПЕРЕДАВАТЬ':'TO TRANSMIT','СТРАШНЫЙ/УЖАСНЫЙ':'FRIGHTFUL',
                  'ЛОЖНЫЙ СЛЕД/ГОНЯТЬСЯ ЗА ПРИЗРАКАМИ':'WILD-GOOSE CHASE','ШААРИТЬ/ВОЗИТЬСЯ':'TO FUMBLE',
                  'ЛОЖКА ДЕГТЯ В БОЧКЕ МЕДА':'FLY IN THE OINTMENT','ТРЕБОВАНИЯ О ВЫКУПЕ':'RANSOM DEMANDS',
                  'ГЛУШИТЕЛЬ': 'MUFFLER', 'ВАРЕЖКИ/РУКАВИЦЫ': 'MITTENS', 'НЕГИГИЕНИЧНО': 'UNSANITARY',
                  'ПОВЕСТКА ДНЯ': 'AGENDA',
                  'ЗЕЛЬЕ/ЭЛЕКСИР': 'POTION', 'ВЫДЕЛИТЬ': 'TO ALLOT', 'ДЕДОВЩИНА': 'HAZING', 'ОТСТОЙНЫЙ': 'LAME',
                  'ПРЕДРАССУДОК': 'PREJUDICE', 'ПАПКА-СКОРОСШИВАТЕЛЬ': 'BINDER', 'ОСТАТКИ(ПИЩИ)': 'LEFTOVERS',
                  'ПЕЛЬМЕНИ': 'DUMPLINGS', 'ВЕСЫ': 'SCALES', 'ПРЕСС/КУБИКИ': 'ABS', 'АРКА': 'ARCH',
                  'ОСОБНЯК': 'MANSION',
                  'ЧАЙКА': 'SEAGULL', 'ЛИПКИЙ': 'TACKY', 'ОЖИРЕНИЕ': 'OBESITY', 'НАБИРАТЬ(ВЕС)': 'TO GAIN',
                  'САЧКОВАТЬ/ФИЛОНИТЬ': 'TO SLACK', 'МЕТОД СОБЛАЗНЕНИЯ': 'SEDUCTION METHOD',
                  'ЗНАКОМЫЕ': 'ACQUAINTANCES',
                  'СУМОЧКА/КОШЕЛЕК': 'PURSE', 'ОПРАВДЫВАТЬ/ЗАКРЫВАТЬ ГЛАЗА': 'TO CONDONE',
                  'НАДУТЬ/РАЗДУВАТЬ': 'TO INFLATE',
                  'НЕПРИВЛЕКАТЕЛЬНЫЙ': 'UNAPPEALING', 'УЛОВКА/ХИТРОСТЬ': 'RUSE', 'ЗАСТАВИТЬ/ВЫНУДИТЬ': 'TO FORCE',
                  'ЯЗВА': 'ULCER', 'ВОРОНА': 'CROW', 'СОЛЬНЫЙ КОНЦЕРТ': 'RECITAL', 'КАПЛЯ': 'DRIP',
                  'ИНОГДА': 'ONCE IN A WHILE', 'ПРИМЕРНО/ПРИБЛИЗИТЕЛЬНО': 'APPROXIMATELY', 'СВЯЗИ': 'LIAISONS',
                  'СРЕДНИЙ АБСОЛЮТНЫЙ ПРОЦЕНТ ОШИБОК': 'MEAN ABSOLUTE PERCENTAGE ERROR',
                  'СРЕДНИЙ КВАДРАТ ЛОГАРИФМИЧЕСКИХ ОШИБОК': 'MEAN SQUARED LOGARITHMIC ERROR',
                  'ОКАЗЫВАЕТСЯ/ПОЛУЧАЕТСЯ': 'TURNS OUT', 'ЗАПЯСТЬЕ': 'WRIST', 'ВЕСЕЛЫЙ/СМЕШНОЙ': 'HILARIOUS',
                  'ПЕРЕМАНИТЬ': 'TO POACH', 'СТОЛОВЫЕ ПРИБОРЫ': 'FLATWARE', 'УВЕЛИЧИТЬ': 'TO AUGMENT',
                  'ТОШНОТА': 'QUEASY',
                  'СВИДЕТЕЛЬСКИЕ ПОКАЗАНИЯ': 'TESTIMONY', 'ТРЕЗВЫЙ': 'SOBER', 'ПОКРОВИТЕЛЬСТВОВАТЬ': 'TO PATRONIZE',
                  'ЦЕРЕМОНИЯ ПОСВЯЩЕНИЯ': 'INDUCTION CEREMONY', 'ДНЕВНИК': 'DIARY', 'ЖУТКИЙ': 'EERIE',
                  'ДАВАТЬ ПОКАЗАНИЯ': 'TO TESTIFY', 'КОМОК': 'LUMP', 'ОШИБОЧНЫЙ': 'FLAWED',
                  'КРАЙНЕ/МАКСИМАЛЬНО': 'UTMOST',
                  'ЧТО КАСАЕТСЯ...': 'REGARDING', 'КАНДИДАТ': 'CONTENDER', 'ТЕННИСНАЯ РАКЕТКА': 'PADDLE',
                  'ЗАКУСКИ/АПЕРИТИВ': 'APPETIZERS', 'ЗАПАХ': 'ODOR', 'КОСТЕР': 'BONFIRE', 'ПСИХУШКА': 'ASYLUM',
                  'СВЕРНУТЬСЯ КАЛАЧИКОМ': 'TO CURL UP', 'ЩЕНОК': 'PUPPY', 'ПРЕДПОЧТЕНИЕ': 'PREFERENCE',
                  'СВЕКОЛЬНЫЙ САЛАТ': 'BEET SALAD', 'ЗУД': 'ITCH', 'ИЛИ/ЛИБО': 'EITHER',
                  'ВОЗМЕЩЕНИЕ РАСХОДОВ': 'REIMBURSEMENT',
                  'ИНАЧЕ': 'OTHERWISE', 'ЗАЩИТА СВИДЕТЕЛЕЙ': 'WITNESS PROTECTION', 'ОХЛАЖДЕНИЕ': 'REFRIGERATION',
                  'НЕНУЖНЫЕ': 'NON-ESSENTIAL', 'ГУСЬ': 'GOOSE', 'БУКСИР/РЫВОК': 'TUG',
                  'ПО НАШИМ ДАННЫМ': 'ACCORDING TO OUR RECORDS',
                  'УЛЬТРАСОВРЕМЕННЫЙ': 'CUTTING EDGE', 'МАССАЖ СПИНЫ': 'BACK RUBS', 'ГОРОДСКАЯ АТМОСФЕРА': 'URBAN VIBE',
                  'ПОСЛЕДОВАТЕЛЬНОСТЬ': 'SEQUENTIAL', 'СРЕДНЕКВАДРАТИЧНАЯ ОШИБКА': 'MEAN SQUARED ERROR',
                  'КОМПИЛИРОВАТЬ': 'TO COMPILE', 'ОПТИМИЗАТОР': 'OPTIMIZER', 'ПОТЕРЯ': 'LOSS',
                  'ОБУЧАЮЩАЯ ВЫБОРКА': 'TRAINING SAMPLE', 'НАПАДАЮЩИЙ УДАР В ВОЛЕЙБОЛЕ': 'SPIKE',
                  'РЕКЛАМНЫЕ РОЛИКИ': 'COMMERCIALS', 'НЕТ В НАЛИЧИИ': 'OUT OF STOCK', 'КЛЮЧЕВАЯ СЦЕНА': 'PIVOTAL SCENE',
                  'СТАЩИТЬ/ПОХИЩАТЬ': 'TO SNATCH', 'ДРАНИКИ': 'HASH BROWNS', 'МОЧКА УХА': 'EARLOBE',
                  'ПРАЗДНИК/ПИР': 'FEAST', 'БИНАРНАЯ КРОСС-ЭНТРОПИЯ': 'BINARY CROSSENTROPY',
                  'КАТЕГОРИАЛЬНАЯ КРОСС-ЭНТРОПИЯ': 'CATEGORICAL CROSSENTROPY',
                  'СРЕДНИЙ МОДУЛЬ ОШИБОК': 'MEAN ABSOLUTE ERROR',
                  'КОГОТЬ': 'CLAW', 'КЛОЧЬЯ/КУСКИ': 'SHREDS', 'КАРТОШКА ФРИ': 'FRENCH FRIES',
                  'РЕДАКТИРОВАТЬ': 'TO EDIT',
                  'РЕКЛАМА': 'ADS', 'БОЛТАТЬСЯ/СВИСАТЬ': 'TO DANGLE', 'ПОДГЛЯДЫВАТЬ': 'TO PEEP', 'АРАХИС': 'PEANUT',
                  'НЕДУГ': 'AFFLICTION', 'БЕЗГРАМОТНЫЙ': 'ILLITERATE', 'НЫТИК': 'DOWNER',
                  'СДЕРЖАННЫЙ/ОСТОРОЖНЫЙ': 'DISCREET',
                  'ПОЗОР': 'INFAMY', 'НЕ ДАВИ НА МЕНЯ!': 'DO NOT RUSH ME!', 'СКОРБИТЬ': 'TO GRIEVE', 'ЕНОТ': 'RACOON',
                  'БЕСКОНЕЧНОСТЬ': 'INFINITY', 'КАПИТАЛЬНЫЙ РЕМОНТ/ПЕРЕСТРОЙКА': 'OVERHAUL',
                  'СТАРУХА С КОСОЙ': 'GRIM REAPER',
                  'БОЛЬШИЕ УСПЕХИ': 'GREAT STRIDES', 'ХАМ/БОЛВАН': 'TWERP', 'ПОЧИТАТЬ/ЧТИТЬ': 'TO REVERE',
                  'ЧЕРНИЛА': 'INK',
                  'ГУРМАН': 'GOURMET', 'ОТТАЛКИВАЮЩИЙ/ОТВРАТИТЕЛЬНЫЙ': 'REPULSIVE', 'СУТЬ/СУЩНОСТЬ': 'ESSENCE',
                  'НЕСЧАСТНЫЙ': 'MISERABLE', 'МАКЕТЫ': 'MOCK-UPS', 'ПИЯВКА': 'LEECH', 'ИЗОБРЕТЕНИЕ': 'INVENTION',
                  'РУМЯНЫЕ ЩЕЧКИ': 'RUDDY CHEEKS', 'ХИХИКАТЬ': 'TO GIGGLE', 'СТРИНГИ': 'THONG',
                  'БОЛЬНИЧНЫЙ': 'SICK LEAVE', 'ДЕРЗКИЙ/ПИКАНТНЫЙ': 'SAUCY', 'ПАРИК': 'WIG',
                  'ДВОЙНИК': 'IMPERSONATOR', 'ОТ ДВОЙКИ ДО': 'DEUCE TO', 'МОЮЩЕЕ СРЕДСТВО': 'DETERGENT',
                  'ТИРАН': 'TYRANT', 'РИФМА': 'RHYME', 'ПУСКАТЬ СЛЮНИ': 'TO SALIVATE', 'ЗАКОННО': 'LAWFULLY',
                  'ПОЧЕТНЫЙ ПРОФЕССОР': 'EMERITUS', 'ХВАСТЛИВЫЙ': 'BRAGGY', 'ФОНД/ФУНДАМЕНТ': 'FOUNDATION',
                  'СТУЛ/КАЛ': 'STOOL', 'К СЧАСТЬЮ': 'FORTUNATELY', 'КОНКУРИРОВАТЬ': 'TO COMPETE',
                  'ОБОРОТЕНЬ': 'WEREWOLF',
                  'ДЛЯ УДОБСТВА': 'FOR THE CONVENIENCE', 'УСТАРЕВШИЙ': 'OBSOLETE', 'ОТВАЛИ ОТ МЕНЯ!': 'GET OFF ME!',
                  'ВЫЧИТАТЬ': 'TO SUBSTRACT', 'ДОКАЗАТЕЛЬСТВО': 'PROOF', 'ИЗГНАНИЕ': 'EXILE',
                  'УБРАТЬ/УНИЧТОЖИТЬ': 'TO TAKE OUT',
                  'ПРЯМОЙ ВОПРОС': 'DIRECT QUESTION', 'СБЕРЕГАТЕЛЬНЫЙ СЧЕТ': 'NUMBERED ACCOUNT', 'СЕТИ': 'GRIDS',
                  'СВАРЩИК': 'WELDER', 'ЯКОРЬ': 'ANCHOR', 'ЦЫГАН': 'GIPSY', 'ШИШКА': 'BUMP', 'ВСТРЕЧА': 'APPOINTMENT',
                  'ГНАТЬСЯ/ПРЕСЛЕДОВАТЬ': 'TO CHASE', 'ЗАГВОЗДКА/ЗАМИНКА': 'HITCH',
                  'НА ЮГ/ЮЖНОЕ НАПРАВЛЕНИЕ': 'SOUTHBOUND',
                  'ТОРМОЗИТЬ МЕНЯ': 'TO SLOW ME DOWN', 'ЗАЛОГ': 'COLLATERAL', 'БАЗОВЫЕ ЗНАНИЯ': 'CORE KNOWLEDGE',
                  'ИСКУСТВЕННЫЙ ИНТЕЛЕКТ': 'ARTIFICIAL INTELLIGENCE', 'ЗНАМЕНИТОСТЬ': 'CELEBRITY',
                  'БЕШЕНСТВО': 'RABIES', 'ИСКОРЕНИТЬ': 'TO ERADICATE', 'ПОВОД': 'CAUSE',
                  'КРЕСТЯНИН/ДЕРЕВЕНЩИНА': 'PEASANT',
                  'ЗАМКНУТЫЙ КРУГ': 'VICIOUS CIRCLE', 'НАТИРАТЬСЯ/РАЗДРАЖАТЬСЯ (КОЖА)': 'TO CHAFE',
                  'БУКВАЛЬНО': 'LITERALLY', 'УДОЧКА': 'ROD', 'СПОРТИВНЫЙ КОММЕНТАТОР': 'SPORTSCASTER',
                  'ГЛОТАТЬ': 'TO SWALLOW', 'ХОТЯ, ЕСЛИ ЧЕСТНО': 'THOUGH TO BE FAIR', 'ГИПСОКАРТОН': 'DRYWALL',
                  'СЛАБЫЙ/ТУСКЛЫЙ': 'FAINT', 'ПОДЛИЗЫВАТЬСЯ КО МНЕ': 'TO SUCK UP TO ME',
                  'МЕТАЛЛОЛОМ': 'SCRAP', 'ГРЯЗЬ': 'GUNK', 'РОЗЕТКА': 'SOCKET', 'ДРАГОЦЕННЫЙ': 'PRECIOUS',
                  'ОТКРОЙ КАПОТ': 'TO POP THE HOOD', 'ОБОРВАНЕЦ': 'RAGAMUFFIN', 'ЛИШАТЬ ДЕВСТВЕННОСТИ': 'TO DEFLOWER',
                  'ЧЕРНАЯ ПОЛОСА/ТЯЖЕЛЫЙ ПЕРИОД': 'ROUGH PATCH', 'МАЛЬЧИШНИК': 'BACHELOR PARTY',
                  'ПЕРСОНАЛЬНОЕ ВНИМАНИЕ': 'PERSONALITY MIRRORING', 'АРОМАТ': 'FLAVOR', 'ТЕМ ВРЕМЕНЕМ': 'MEANWHILE',
                  'МОРСКИЕ ПЕХОТИНЦЫ': 'MARINES', 'ЯСТРЕБ': 'HAWK', 'БОЖЬЯ КОРОВКА': 'LADYBUG',
                  'ПРЕУВЕЛИЧЕНИЕ/УТРИРОВАНИЕ': 'EXAGGERATION', 'ШАНТАЖ/ВЫМОГАТЕЛЬСТВО': 'BLACKMAIL',
                  'МАЛЬЧИК НА ПОБЕГУШКАХ': 'BELLBOY', 'ПЛЕМЯННИЦА': 'NIECE', 'ОБМАНУТЬ МЕНЯ': 'FOOL ME',
                  'ПЕТУХ': 'ROOSTER', 'КУКАРЕКАТЬ': 'TO CROW', 'ОТСТУПИТЬ/УЙТИ С ПОСТА': 'TO STEP DOWN',
                  'ДОБИВАТЬСЯ УСПЕХА': 'TO SUCCEED', 'АЛЬФА-САМЕЦ': 'ALPHA MALE', 'ОТБОЙНЫЙ МОЛОТОК': 'JACKHAMMER',
                  'БЕСПОЩАДНЫЙ': 'MERCILESS', 'ДОПОЛНЕНИЕ': 'ADDITION', 'ЭТО МЕНЯ ПУГАЕТ': 'IT CREEPS ME OUT',
                  'НАДОЕДЛИВЫЙ/РАЗДРАЖАЮЩИЙ': 'ANNOYING', 'ПЕТАРДЫ': 'FIRECRACKERS', 'ОСЕЛ': 'DONKEY',
                  'ОЧЕНЬ БОЛЬШОЙ': 'HUGE', 'ОЧЕНЬ ОПАСНЫЙ': 'PERILOUS', 'ОЧЕНЬ СТАРЫЙ': 'FRAIL',
                  'ОЧЕНЬ УВЕРЕННО': 'CERTAIN', 'СИЛЬНО ПЕРЕЖИВАЮЩИЙ': 'DISTRESSED',
                  'БЛУЗКА': 'BLOUSE', 'ЗУБНАЯ НИТЬ': 'FLOSS', 'ИГРА СЛОВ/КАЛАМБУР': 'PUN',
                  'ПОНИЗИТЬ/РАЗЖАЛОВАТЬ': 'TO DEMOTE', 'СОЮЗНИК/ПОМОЩНИК': 'ALLY',
                  'ПРЕДАТЬ': 'TO BETRAY', 'СТАТУЯ/СКУЛЬПТУРА': 'STATUE', 'ТОРГОВЫЙ АВТОМАТ': 'VENDING MACHINE',
                  'ГОРЕ/ПЕЧАЛЬ': 'GRIEF', 'ОТРИЦАНИЕ': 'DENIAL', 'ПРОМЕЖНОСТЬ/ПАХ': 'CROTCH',
                  'ПОСТАВКА/ПАРТИЯ/ГРУЗ': 'SHIPMENT', 'КЛЮВ': 'BEAK', 'ЗАБОЙ': 'TO SLAUGHTER',
                  'ВЗДОР/ЧЕПУХА': 'BALONEY', 'МЕТЛА': 'BROOM', 'ВОЗМУЩЕНИЕ': 'OUTRAGE', 'ПРЕДАТЕЛЬ': 'TRAITOR',
                  'ПРОТИВОСТЯТЬ': 'TO CONFRONT', 'ЗАГРЯЗНЯТЬ': 'TO POLLUTE', 'ОБГОНЯТЬ': 'TO OUTRUN',
                  'Я СВАЛИВАЮ ОТСЮДА': 'I AM OUTTA HERE', 'ТУАЛЕТНАЯ КАБИНКА': 'BATHROOM STALL',
                  'ПОЛДЕНЬ': 'NOON', 'ПАРТИЯ': 'BATCH', 'ЧАСТО ЗАЯВЛЯТЬ О СЕБЕ': 'NAME REPETITION',
                  'СЕСТЬ НА МЕЛЬ': 'TO RUN AGROUND', ',БУЙНЫЙ/ШУМНЫЙ': 'ROWDY', 'РАССТАТЬСЯ': 'TO BREAK UP',
                  'СРОЧНЫЙ(ВОПРОС)': 'URGENT', 'ПРЫГАТЬ/СКАКАТЬ': 'HOP', 'ЛОКОТЬ': 'ELBOW',
                  'СТОЛБ(ЭЛКТРОПЕРЕДАЧ)': 'POLE',
                  'УПОМИНАТЬ': 'TO MENTION', 'ЛЕЧЕНИЕ': 'TREATMENT', 'КАПРИЗНЫЙ': 'FUSSY',
                  'КУРИЦА-ГРИЛЬ': 'ROTISSERIE CHICKEN', 'КОРОЧЕ/КОМПАКТНЕЕ': 'CHUNKIER',
                  'ВТИРАТЬ/НАТИРАТЬ': 'TO RUB', 'НЕСОКРУШИМЫЙ': 'INDESTRUCTIBLE',
                  'ИМИТИРОВАТЬ/ВЫСМЕИВАТЬ': 'TO MOCK', 'ТРЯПКА/СЛАБАК': 'WUSS', 'ЗАЖАТЬ/ЗАЖИМАТЬ': 'TO CLAMP',
                  'СОТРЯСЕНИЕ МОЗГА': 'CONCUSSION', 'БЛЕВОТИНА': 'VOMITY',
                  'ТУПОЙ/ТУСКЛЫЙ': 'DULL', 'ЗАФИКСИРОВАТЬ/СОВЕРШИТЬ': 'TO COMMIT', 'ПОДЧИНЯТЬСЯ': 'TO OBEY',
                  'УСПОКОИТЕЛЬНОЕ': 'CHILL PILL', 'КОСЯК': 'JOINT', 'МИР ВАМ!': 'PEACE OUT!', 'КОСЯЧОК': 'DOOBIE',
                  'ЗАКУСКИ': 'MUNCHIES', 'СГЛАЗ': 'JINX', 'ЖЕСТКИЙ': 'RIGID', 'ПОСЛЕ/НАД': 'UPON',
                  'ЦЕЛЬ/НАЗНАЧЕНИЕ': 'PURPOSE', 'ОТКАЗАТЬСЯ': 'TO REFUSE', 'ПРИСЯГА/КЛЯТВА': 'OATH',
                  'ПОД ПРИСЯГОЙ': 'SWORN IN', 'ПАХ': 'GROIN',
                  'СПАСАТЕЛЬНЫЕ ЖИЛЕТЫ': 'LIFE PRESERVERS', ' ПЕРВОБЫТНЫЙ': 'PRIMAL',
                  'ДРЕВНИЕ ВРЕМЕНА': 'ANCIENT TIMES',
                  'ПОШЛЫЙ/НЕПРИСТОЙНЫЙ': 'FILTHY', 'ЛИЦЕМЕР': 'HYPOCRITE', 'МОШЕННИЧЕСТВО': 'SCAM',
                  'ОСТРОУМНЫЙ': 'WITTY',
                  'ГОЛУБЬ': 'DOVE', 'ПОРОХОВАЯ БОЧКА': 'TINDERBOX', 'РАВНЫЕ/РАВНО': 'EQUAL', 'ТОПОР': 'AXE',
                  'БРОСИТЬ/УЙТИ': 'TO QUIT', 'ВПЕЧАТЛИТЬ': 'TO IMPRESS', 'УВОЛЬНЕНИЕ': 'LAYOFF', 'ПОЛЬЩЕН': 'FLATTERED',
                  'НЕ ПОЙМИТЕ МЕНЯ НЕПРАВИЛЬНО': 'DO NOT GET ME WRONG', 'БОЕВЫЕ ИСКУССТВА': 'MARTIAL ARTS',
                  'МУЧАТЬ': 'TO TORTURE',

                  'ЗАХВАТИТЬ/УГНАТЬ':'TO HIJACK','АВТОМАГИСТРАЛЬ':'EXPRESSWAY','ЗАСОХНУТЬ':'TO WITHER','ХУЛИГАН':'HOODLUM',
                  'ТАПОЧКИ':'SLIPPERS','ВОСПРЯНУТЬ ДУХОМ':'TO PERK UP','НАПРАВЛЯТЬ/УПРАВЛЯТЬ/РУКОВОДИТЬ':'TO STEER',
                  'КРЕВЕТКА':'SHRIMP','ЯМА/КОТЛОВАН':'PIT','СТОГ СЕНА':'HAYSTACK','ИСПАРЕНИЯ':'FUMES','ХОРЕК':'WEASEL',
                  'ПРИМАНКА/ЛОВУШКА':'DECOY','ПАСТИСЬ':'TO GRAZE','ХРУПКИЙ':'FRAGILE','НЕТРОНУТЫЙ':'INTACT',
                  'ОПЕКА/РУКОВОДСТВО':'TUTELAGE','КРУШЕНИЕ/АВАРИЯ':'WRECK','РАЗ ПЛЮНУТЬ!':'PIECE OF CAKE!',
                  'СВИДЕТЕЛЬСТВО/ДОКАЗАТЕЛЬСТВО': 'EVIDENCE', 'ПАСТБИЩЕ': 'PASTURE', 'ПОД ПРЕКРЫТИЕМ': 'UNDERCOVER',
                  'ТРЮК': 'STUNT',
                  'НЕОТСЛЕЖИВАЕМЫЕ': 'UNTRACEABLE', 'ПАПОРОТНИК': 'FERN', 'ПОЛИЦЕЙСКИЙ УЧАСТОК': 'PRECINCT',
                  'ВОПИЮЩИЙ': 'BLATANT',
                  'ЭЛЕГАНТНЫЙ КОД': 'SLEEK CODE', 'ПРОИЗОДИТЕЛЬНЫЙ КОД': 'PERFORMANT CODE',
                  'НИЗКОЗАТРАТНЫЙ КОД': 'LOW-OVERHEAD CODE',
                  'ФУНКЦИИ ВЫСШЕГО ПОРЯДКА': 'HIGHER ORDER FUNCTIONS', 'ДОЛЯ/АКЦИИ': 'EQUITY',
                  'МАСТЕР НА ВСЕ РУКИ': 'JACK OF ALL TRADES','ПРОТОТИП':'PROTOTYPE','ТМИН':'CUMIN',
                  'НАМАЗЫВАТЬ/РАЗМАЗЫВАТЬ':'TO SMEAR',
                  'ВИРУСНЫЙ':'VIRAL','ЧМОШНЫЙ/ОТСТОЙНЫЙ':'DOUCHEY','ВТОРОКУРСНИК':'SOPHOMORE',
                  'ХОРЕК/':'FERRET','ОЦЕНИВАТЬ|ПРОАНАЛИЗИРОВАТЬ':'TO EVALUATE','СИЛЬНЫЕ СТОРОНЫ':'STRENGTHS',
                  'КОНЦЕПЦИЯ':'CONCEPT','ИНИЦИАТИВА':'INITIATIVE','КРИЧАТЬ':'SHOUT OUT','ЗАПУСКАТЬ С':'LAUNCH OFF',
                  'ТРАМПЛИН':'RAMP','СКВЕРНО':'GNARLY','ПРИЗЕМЛЯТЬСЯ':'TO LAND','ЛАСКОВОЕ ОБРАЩЕНИЕ':'TERM OF ENDEARMENT',

                  }

    print('Слов в словаре:', len(vocabulary))
    pickle.dump(vocabulary, file)
    file.close()


main()
