import turtle
turtle.setup(640,480)
turtle.showturtle()
turtle.circle(100)
turtle.forward(50)
turtle.dot()
turtle.forward(25)
turtle.penup()
turtle.forward(25)
turtle.pendown()
turtle.forward(25)
turtle.dot()
turtle.forward(25)
turtle.dot()
turtle.pensize(5)
turtle.pencolor("red")
turtle.circle(50)
turtle.setheading(270)
turtle.pensize(3)
turtle.pencolor("green")
turtle.forward(50)
turtle.bgcolor("grey")
turtle.setheading(180)
turtle.pencolor("white")
turtle.forward(50)
turtle.dot(10,"black")
turtle.pencolor("yellow")
turtle.bgcolor("blue")
turtle.forward(50)
turtle.penup()
turtle.forward(20)
turtle.pendown()
turtle.forward(25)
turtle.pencolor("orange")
turtle.circle(30)
turtle.bgcolor("white")
turtle.clearscreen()
turtle.showturtle()
for i in range(10):
    turtle.bgcolor("yellow")
    turtle.bgcolor("blue")
    turtle.clearscreen()
turtle.clearscreen()
turtle.pensize(7)
turtle.goto(0,100)
turtle.goto(-100,0)
turtle.goto(0,0)
turtle.goto(50,50)
turtle.pos()
turtle.xcor()
turtle.ycor()
turtle.clearscreen()
turtle.goto(0,0)
turtle.speed(1)
turtle.forward(33)
turtle.write("Hello,MAMA!!!")
turtle.setheading(90)
turtle.penup()
turtle.forward(200)
turtle.pendown()
turtle.write('МЫ ВВЕРХУ!')
turtle.penup()
turtle.setheading(270)
turtle.forward(350)
turtle.pendown()
turtle.write('МЫ ВНИЗУ!')
turtle.goto(0,0)
turtle.clearscreen()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.circle(75)
turtle.end_fill()
turtle.setheading(270)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.setheading(360)
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.circle(50)
turtle.end_fill()
turtle.setheading(270)
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.setheading(360)
turtle.fillcolor("green")
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()








turtle.done()